#pragma once

#include "Animation_PoseTask.h"
#include "Animation_TaskSerializer.h"
#include "Animation_BoneMaskPool.h"
#include "Engine/Animation/AnimationBoneMask.h"
#include "Base/Types/Containers_ForwardDecl.h"

//-------------------------------------------------------------------------

namespace EE::TypeSystem { class TypeRegistry; }

//-------------------------------------------------------------------------

namespace EE::Animation
{
    #if EE_DEVELOPMENT_TOOLS
    enum class TaskSystemDebugMode
    {
        Off,
        FinalPose,
        PoseTree,
        DetailedPoseTree
    };
    #endif

    //-------------------------------------------------------------------------

    class TaskSerializer;

    //-------------------------------------------------------------------------

    class EE_ENGINE_API TaskSystem
    {
        friend class AnimationDebugView;

    public:

        static void InitializeTaskTypesList( TypeSystem::TypeRegistry const& typeRegistry );
        static void ShutdownTaskTypesList();
        static TVector<TypeSystem::TypeInfo const*> const* GetTaskTypesList();

    public:

        TaskSystem( Skeleton const* pSkeleton );
        ~TaskSystem();

        void Reset();
        void ResetForNewUpdate();

        // Get the actual final character transform for this frame
        Transform const& GetCharacterWorldTransform() const { return m_taskContext.m_worldTransform; }

        // Pose(s)
        //-------------------------------------------------------------------------

        // Get current final pose buffer
        PoseBuffer const* GetPoseBuffer() const { return m_pFinalPoseBuffer; }

        // Get previous update final pose buffer
        PoseBuffer const* GetPoseBufferForPreviousUpdate() const { return m_pPreviousFinalPoseBuffer; }

        // Get the final primary pose generated by the task system
        Pose const* GetPrimaryPose() const{ return &m_pFinalPoseBuffer->m_poses[0]; }

        // Get the final primary pose generated by the task system for the previous update
        Pose const* GetPrimaryPoseForPreviousUpdate() const { return &m_pPreviousFinalPoseBuffer->m_poses[0]; }

        // Get the final primary pose generated by the task system
        TInlineVector<Pose const*, 1> GetSecondaryPoses() const;

        // Get the final primary pose generated by the task system for the previous update
        TInlineVector<Pose const*, 1> GetSecondaryPosesForPreviousUpdate() const;

        // Set whether we are allowed to sample float channel data
        EE_FORCE_INLINE void SetAllowFloatChannelSampling( bool allowFloatChannelSampling ) { m_taskContext.m_sampleFloatChannels = allowFloatChannelSampling; }

        // Are we allowed to sample float channel data?
        EE_FORCE_INLINE bool IsFloatChannelSamplingAllowed() const { return m_taskContext.m_sampleFloatChannels; }

        // Skeleton(s)
        //-------------------------------------------------------------------------

        // Get the primary skeleton from this task system
        Skeleton const* GetSkeleton() const { return m_posePool.GetPrimarySkeleton(); }

        // Set the skeleton LOD for the result pose
        EE_FORCE_INLINE void SetSkeletonLOD( Skeleton::LOD lod ) { m_taskContext.m_skeletonLOD = lod; }

        // Get the current skeleton LOD we are using
        EE_FORCE_INLINE Skeleton::LOD GetSkeletonLOD() const { return m_taskContext.m_skeletonLOD; }

        // Set the secondary skeletons that we can animate
        void SetSecondarySkeletons( SecondarySkeletonList const& secondarySkeletons );

        // Get the number of secondary skeletons set
        EE_FORCE_INLINE int32_t GetNumSecondarySkeletons() const { return m_posePool.GetNumSecondarySkeletons(); }

        // Get the secondary skeletons
        SecondarySkeletonList const &GetSecondarySkeletons() const { return m_posePool.GetSecondarySkeletons(); }

        // Execution
        //-------------------------------------------------------------------------

        // Do we have any tasks that need execution
        inline bool RequiresUpdate() const { return m_needsUpdate; }

        // Do we have a physics dependency in our registered tasks
        inline bool HasPhysicsDependency() const { return m_hasPhysicsDependency; }

        // Run all pre-physics tasks
        void UpdatePrePhysics( float deltaTime, Transform const& worldTransform, Transform const& worldTransformInverse );

        // Run all post-physics tasks and fill out the final pose buffer
        void UpdatePostPhysics();

        #if EE_DEVELOPMENT_TOOLS
        // Get the time it took for the last update to execute
        Microseconds GetExecutionTime() const { return m_executionTime; }
        #endif

        // Cached Pose storage
        //-------------------------------------------------------------------------

        // Is there a valid cached pose buffer for this ID?
        bool IsValidCachedPose( CachedPoseID cachedPoseID ) const;

        // Create storage for a cached pose - returns the ID for the cached pose storage
        CachedPoseID CreateCachedPose();

        // Get a cached pose buffer
        PoseBuffer* GetCachedPose( CachedPoseID cachedPoseID );

        // Destroy an allocated cached pose buffer - frees the ID to be reused
        void DestroyCachedPose( CachedPoseID cachedPoseID );

        #if EE_DEVELOPMENT_TOOLS
        // Ensure that we have a valid cached pose buffer with the given ID. Needed for restoring from a recorded state
        void EnsureCachedPoseExists( CachedPoseID cachedPoseID );
        #endif

        // Task Registration
        //-------------------------------------------------------------------------

        inline bool HasTasks() const { return m_tasks.size() > 0; }
        inline TVector<PoseTask*> const& GetRegisteredTasks() const { return m_tasks; }

        template< typename T, typename ... ConstructorParams >
        inline int8_t RegisterTask( SourcePath const& sourcePath, ConstructorParams&&... params )
        {
            EE_ASSERT( m_tasks.size() < 0xFF );

            auto pNewTask = m_tasks.emplace_back( EE::New<T>( eastl::forward<ConstructorParams>( params )... ) );
            pNewTask->m_sourcePath = sourcePath;
            m_hasPhysicsDependency |= pNewTask->HasPhysicsDependency();
            m_needsUpdate = true;
            return (int8_t) ( m_tasks.size() - 1 );
        }

        template< typename T, typename ... ConstructorParams >
        inline int8_t RegisterTask( SourcePath&& sourcePath, ConstructorParams&&... params )
        {
            EE_ASSERT( m_tasks.size() < 0xFF );

            auto pNewTask = m_tasks.emplace_back( EE::New<T>( eastl::forward<ConstructorParams>( params )... ) );
            pNewTask->m_sourcePath = eastl::move( sourcePath );
            m_hasPhysicsDependency |= pNewTask->HasPhysicsDependency();
            m_needsUpdate = true;
            return (int8_t) ( m_tasks.size() - 1 );
        }

        int8_t GetCurrentTaskIndexMarker() const { return (int8_t) m_tasks.size(); }
        void RollbackToTaskIndexMarker( int8_t const marker );

        // Task Serialization
        //-------------------------------------------------------------------------

        // Serialized the current executed tasks - NOTE: this can fail since some tasks (i.e. physics) cannot be serialized!
        // Only do this if there are no currently pending tasks!
        void SerializeTasks( TaskSerializationContext const& taskSerializationContext, Blob& outSerializedTopologyData, Blob& outSerializedTaskData ) const;

        // Create a new set of tasks from a serialized set of data
        // Only do this if there are no registered tasks!
        void DeserializeTasks( TaskSerializationContext const& taskSerializationContext, Blob const& inSerializedTopologyData, Blob const& inSerializedTaskData );

        // Debug
        //-------------------------------------------------------------------------

        #if EE_DEVELOPMENT_TOOLS
        void SetDebugMode( TaskSystemDebugMode mode );
        TaskSystemDebugMode GetDebugMode() const { return m_debugMode; }
        void DrawDebug( DebugDrawContext& drawingContext );

        inline TVector<TaskLogEntry> const &GetLog() const { return m_log; }
        #endif

    private:

        bool AddTaskChainToPrePhysicsList( int8_t taskIdx );
        void ExecuteTasks();

        // Debug
        //-------------------------------------------------------------------------

        #if EE_DEVELOPMENT_TOOLS
        void CalculateTaskTreeOffsets( Transform const &worldTransform ) const;
        #endif

    private:

        TVector<PoseTask*>                      m_tasks;
        PoseBufferPool                          m_posePool;
        BoneMaskPool                            m_boneMaskPool;
        TaskContext                             m_taskContext;
        TInlineVector<int8_t, 16>               m_prePhysicsTaskIndices;
        bool                                    m_hasPhysicsDependency = false;
        bool                                    m_hasCodependentPhysicsTasks = false;
        bool                                    m_needsUpdate = false;
        uint32_t                                m_maxBitsForTaskTypeID = 0;
        PoseBuffer*                             m_pFinalPoseBuffer = nullptr;
        PoseBuffer*                             m_pPreviousFinalPoseBuffer = nullptr;
        Microseconds                            m_executionTime = 0.0f;

        //-------------------------------------------------------------------------

        #if EE_DEVELOPMENT_TOOLS
        TaskSystemDebugMode                     m_debugMode = TaskSystemDebugMode::Off;
        TVector<TaskLogEntry>                   m_log;
        #endif
    };
}