#include "ResourceServerApplication.h"
#include "Resources/Resource.h"
#include "EngineTools/_Module/_AutoGenerated/TypeInfo/TypeRegistration.h"
#include "Base/Time/Timers.h"
#include "Base/FileSystem/FileSystemUtils.h"
#include "Base/Imgui/Platform/ImguiPlatform_win32.h"
#include "Base/Platform/PlatformUtils_Win32.h"
#include "Base/Platform/Platform.h"
#include "Base/Settings/IniFile.h"
#include "Base/TypeSystem/TypeRegistry.h"
#include "Base/Render/Settings/Settings_Render.h"
#include "Base/Profiling.h"

#include <tchar.h>
#include <shobjidl_core.h>

//-------------------------------------------------------------------------

namespace EE
{
    constexpr static int32_t const g_shellIconCallbackMessageID = WM_USER + 1;

    //-------------------------------------------------------------------------

    ResourceServerApplication::ResourceServerApplication( HINSTANCE pInstance )
        : Win32Application( pInstance, "Esoterica Resource Server", IDI_RESOURCESERVER, -1, TBitFlags<InitOptions>( Win32Application::InitOptions::StartMinimized, Win32Application::InitOptions::Borderless ) )
        , m_resourceServer( m_typeRegistry )
        , m_resourceServerUI( m_resourceServer )
    {}

    LRESULT ResourceServerApplication::WindowMessageProcessor( HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam )
    {
        switch ( message )
        {
            case g_shellIconCallbackMessageID:
            {
                switch ( LOWORD( lParam ) )
                {
                    case WM_LBUTTONDBLCLK:
                    {
                        ShowApplicationWindow();
                    }
                    break;

                    case WM_RBUTTONDOWN:
                    {
                        if ( !ShowSystemTrayMenu() )
                        {
                            return 0;
                        }
                    }
                    break;
                }
            }
            break;

            //-------------------------------------------------------------------------

            case WM_COMMAND:
            {
                switch ( LOWORD( wParam ) )
                {
                    case ID_REQUEST_EXIT:
                    {
                        if ( OnUserExitRequest() )
                        {
                            RequestApplicationExit();
                        }
                        else
                        {
                            return 0;
                        }
                    }
                    break;
                }
            }
            break;

            //-------------------------------------------------------------------------

            case WM_CLOSE:
            {
                HideApplicationWindow();
                return 0;
            }
            break;
        }

        return Win32Application::WindowMessageProcessor( hWnd, message, wParam, lParam );
    }

    void ResourceServerApplication::ProcessWindowDestructionMessage()
    {
        if ( m_pTaskbarInterface != nullptr )
        {
            m_pTaskbarInterface->SetOverlayIcon( m_windowHandle, nullptr, L"" );
            m_pTaskbarInterface->Release();
            m_pTaskbarInterface = nullptr;
        }
        CoUninitialize();

        m_busyOverlaySet = false;
        DestroyIcon( m_busyOverlayIcon );

        //-------------------------------------------------------------------------

        Win32Application::ProcessWindowDestructionMessage();
    }

    void ResourceServerApplication::ResizeMainWindow( Int2 const& newWindowSize )
    {
        if ( m_renderWindow.GetSwapchainSize() != newWindowSize )
        {
            m_renderSystem.WaitGraphicsQueueIdle();
            m_renderWindow.ResizeSwapchain( m_renderSystem.GetContextRHI(), m_renderSystem.GetGraphicsQueue(), m_renderSystem.GetComputeQueue(), newWindowSize );
        }
    }

    void ResourceServerApplication::OnFirstShowMainWindow()
    {
        Win32Application::OnFirstShowMainWindow();
        HideApplicationWindow();
    }

    bool ResourceServerApplication::OnUserExitRequest()
    {
        // Allow exiting resource server immediately if not connected clients
        if ( m_resourceServer.GetNumConnectedClients() == 0 )
        {
            return true;
        }

        //-------------------------------------------------------------------------

        // Confirm exit if there are still connected clients
        int32_t const closeDialogResult = MessageBox( m_windowHandle, "There are still connected clients!\r\nAre you sure you want to exit the Resource Server?", "Resource Server", MB_YESNO | MB_ICONEXCLAMATION | MB_DEFBUTTON2 | MB_TOPMOST );
        if ( closeDialogResult == IDYES )
        {
            return true;
        }

        return false;
    }

    //-------------------------------------------------------------------------

    void ResourceServerApplication::ShowApplicationWindow()
    {
        ShowWindow( m_windowHandle, SW_RESTORE );
        SetForegroundWindow( m_windowHandle );
        m_applicationWindowHidden = false;
    }

    void ResourceServerApplication::HideApplicationWindow()
    {
        ShowWindow( m_windowHandle, SW_HIDE );
        m_applicationWindowHidden = true;
    }

    bool ResourceServerApplication::CreateSystemTrayIcon( int32_t iconID )
    {
        m_systemTrayIconData.cbSize = sizeof( NOTIFYICONDATA );
        m_systemTrayIconData.hWnd = m_windowHandle;
        m_systemTrayIconData.uID = IDI_TRAY_IDLE;
        m_systemTrayIconData.uFlags = NIF_ICON | NIF_MESSAGE | NIF_TIP;
        m_systemTrayIconData.hIcon = LoadIcon( m_pInstance, (LPCTSTR) MAKEINTRESOURCE( iconID ) );
        m_systemTrayIconData.uCallbackMessage = g_shellIconCallbackMessageID;
        strcpy( m_systemTrayIconData.szTip, "Esoterica Resource Server" );

        if ( !Shell_NotifyIcon( NIM_ADD, &m_systemTrayIconData ) )
        {
            return false;
        }

        m_currentIconID = iconID;
        return true;
    }

    bool ResourceServerApplication::ShowSystemTrayMenu()
    {
        HMENU hMenu, hSubMenu;

        // Get mouse cursor position x and y as lParam has the Message itself
        POINT lpClickPoint;
        GetCursorPos( &lpClickPoint );

        // Load menu resource
        hMenu = LoadMenu( m_pInstance, MAKEINTRESOURCE( IDR_SYSTRAY_MENU ) );
        if ( !hMenu )
        {
            return false;
        }

        hSubMenu = GetSubMenu( hMenu, 0 );
        if ( !hSubMenu )
        {
            DestroyMenu( hMenu );
            return false;
        }

        // Display menu
        SetForegroundWindow( m_windowHandle );
        TrackPopupMenu( hSubMenu, TPM_LEFTALIGN | TPM_LEFTBUTTON | TPM_BOTTOMALIGN, lpClickPoint.x, lpClickPoint.y, 0, m_windowHandle, NULL );
        SendMessage( m_windowHandle, WM_NULL, 0, 0 );

        // Kill off objects we're done with
        DestroyMenu( hMenu );

        return true;
    }

    void ResourceServerApplication::DestroySystemTrayIcon()
    {
        Shell_NotifyIcon( NIM_DELETE, &m_systemTrayIconData );
    }

    void ResourceServerApplication::RefreshSystemTrayIcon( int32_t iconID )
    {
        if ( iconID != m_currentIconID )
        {
            DestroySystemTrayIcon();
            CreateSystemTrayIcon( iconID );
        }
    }

    //-------------------------------------------------------------------------

    bool ResourceServerApplication::Initialize( int32_t argc, char** argv )
    {
        #if EE_ENABLE_LPP
        LivePP_CreateAgent();
        LivePP_EnableModules();
        #endif

        m_busyOverlayIcon = LoadIcon( m_pInstance, MAKEINTRESOURCE( IDI_RESOURCESERVER_BUSYOVERLAY ) );

        CoInitialize( nullptr );
        auto const result = CoCreateInstance( CLSID_TaskbarList, NULL, CLSCTX_INPROC_SERVER, IID_PPV_ARGS( &m_pTaskbarInterface ) );
        if ( result == S_OK )
        {
            m_pTaskbarInterface->HrInit();
        }
        else
        {
            return false;
        }

        //-------------------------------------------------------------------------

        TypeSystem::Reflection::RegisterTypes( m_typeRegistry );

        FileSystem::Path const iniFilePath = FileSystem::GetCurrentProcessPath().Append( "Esoterica.ini" );
        IniFile iniFile( iniFilePath );
        if ( !iniFile.IsValid() )
        {
            InlineString const errorMessage( InlineString::CtorSprintf(), "Failed to load settings from INI file: %s", iniFilePath.c_str() );
            return FatalError( errorMessage.c_str() );
        }

        Render::RenderSettings renderSettings = {};
        renderSettings.LoadSettings( m_typeRegistry, iniFile );

        Int2 const windowDimensions( ( m_windowRect.right - m_windowRect.left ), ( m_windowRect.bottom - m_windowRect.top ) );

        m_renderSystem.Initialize( renderSettings );

        m_renderWindow.SetNativeWindowHandle( Platform::GetMainWindowHandle() );
        m_renderWindow.ResizeSwapchain( m_renderSystem.GetContextRHI(), m_renderSystem.GetGraphicsQueue(), m_renderSystem.GetComputeQueue(), windowDimensions );

        m_renderSystem.RegisterRenderWindow( &m_renderWindow );

        //-------------------------------------------------------------------------

        if ( !m_resourceServer.Initialize( iniFilePath ) )
        {
            return FatalError( "Resource server failed to initialize!" );
        }

        //-------------------------------------------------------------------------

        m_renderSystem.StartResourceUpdates( true );

        m_imguiSystem.Initialize();
        m_imguiRenderer.Initialize( &m_renderWindow, &m_renderSystem );

        m_resourceServerUI.Initialize( m_imguiRenderer.GetImageCache() );

        m_renderSystem.SubmitResourceUpdates( true );

        //-------------------------------------------------------------------------

        CreateSystemTrayIcon( IDI_TRAY_IDLE );
        return true;
    }

    bool ResourceServerApplication::Shutdown()
    {
        EE_ASSERT( WasInitialized() );

        #if EE_ENABLE_LPP
        LivePP_DestroyAgent();
        #endif

        m_renderSystem.WaitAllQueuesIdle();

        m_renderSystem.UnregisterRenderWindow( &m_renderWindow );
        m_renderWindow.DestroySwapchain( m_renderSystem.GetContextRHI() );

        m_resourceServerUI.Shutdown();

        m_imguiRenderer.Shutdown();
        m_imguiSystem.Shutdown();

        m_renderSystem.Shutdown();

        Render::RHI::ReportDeviceMemoryLeaks();

        //-------------------------------------------------------------------------

        m_resourceServer.Shutdown();

        TypeSystem::Reflection::UnregisterTypes( m_typeRegistry );

        //-------------------------------------------------------------------------

        DestroySystemTrayIcon();

        return true;
    }

    //-------------------------------------------------------------------------

    bool ResourceServerApplication::ApplicationLoop()
    {
        #if EE_ENABLE_LPP
        LivePP_UpdateAgent();
        #endif

        //Profiling::StartFrame();

        Milliseconds deltaTime = 0;
        {
            ScopedTimer<PlatformClock> frameTimer( deltaTime );

            // Update resource server
            //-------------------------------------------------------------------------

            bool isServerBusy = false;

            {
                EE_PROFILE_SCOPE( "Resource Server Update" );

                m_resourceServer.Update();

                // Sleep when idle to reduce CPU load
                isServerBusy = m_resourceServer.IsBusy();
                if ( !isServerBusy )
                {
                    Threading::Sleep( 1 );
                }
            }

            // Update task bar
            //-------------------------------------------------------------------------

            EE_ASSERT( m_pTaskbarInterface != nullptr );

            // Showing progress bar
            if ( m_busyOverlaySet )
            {
                // Switch to idle
                if ( !isServerBusy )
                {
                    m_pTaskbarInterface->SetOverlayIcon( m_windowHandle, nullptr, L"" );
                    m_pTaskbarInterface->SetProgressState( m_windowHandle, TBPF_NOPROGRESS );
                    RefreshSystemTrayIcon( IDI_TRAY_IDLE );
                    m_busyOverlaySet = false;
                }
            }
            else // Idle
            {
                if ( isServerBusy )
                {
                    m_pTaskbarInterface->SetOverlayIcon( m_windowHandle, m_busyOverlayIcon, L"" );
                    m_pTaskbarInterface->SetProgressState( m_windowHandle, TBPF_NORMAL );
                    RefreshSystemTrayIcon( IDI_TRAY_BUSY );
                    m_busyOverlaySet = true;
                }
            }

            // Draw UI
            //-------------------------------------------------------------------------

            {
                EE_PROFILE_SCOPE( "Resource Server UI" );

                if ( !IsIconic( m_windowHandle ) )
                {
                    m_imguiSystem.StartFrame( m_deltaTime );
                    m_resourceServerUI.Draw();
                    m_imguiSystem.EndFrame();

                    ImGui::Render();

                    m_renderSystem.WaitForFrameStart();

                    m_renderSystem.StartResourceUpdates( false );
                    m_imguiRenderer.UpdateDeviceResources();
                    m_renderSystem.SubmitResourceUpdates( false );

                    m_renderSystem.StartFrame();
                    m_imguiRenderer.StartFrame();
                    m_imguiRenderer.SubmitFrame( true );
                    m_renderSystem.SubmitFrame();

                    m_imguiRenderer.EndFrame();
                }
            }
        }

        m_deltaTime = deltaTime;
        EngineClock::Update( deltaTime );

        //Profiling::EndFrame();

        return true;
    }
}

//-------------------------------------------------------------------------

int APIENTRY _tWinMain( HINSTANCE hInstance, HINSTANCE hPrevInstance, LPTSTR lpCmdLine, int nCmdShow )
{
    HANDLE pSingletonMutex = CreateMutex( NULL, TRUE, "Esoterica Resource Server" );
    if ( GetLastError() == ERROR_ALREADY_EXISTS )
    {
        MessageBox( nullptr, "Only a single instance of the Resource Server is allowed to run!", "Fatal Error Occurred!", MB_OK | MB_ICONERROR );
        return -1;
    }

    //-------------------------------------------------------------------------

    int result = 0;
    {
        EE::ApplicationGlobalState globalState;
        EE::ResourceServerApplication engineApplication( hInstance );
        result = engineApplication.Run( __argc, __argv );
    }

    //-------------------------------------------------------------------------

    ReleaseMutex( pSingletonMutex );
    CloseHandle( pSingletonMutex );

    return result;
}