#pragma once

#include "Base/Esoterica.h"

//-------------------------------------------------------------------------

#ifdef _WIN32

    typedef unsigned char BYTE;

    #ifdef EE_DEBUG
        #include "_AutoGenerated/CS_PrecomputeDFG_x64_Debug.h"
        #include "_AutoGenerated/PS_Empty_x64_Debug.h"
        #include "_AutoGenerated/PS_Lit_x64_Debug.h"
        #include "_AutoGenerated/PS_Skybox_x64_Debug.h"
        #include "_AutoGenerated/VS_Cube_x64_Debug.h"
        #include "_AutoGenerated/VS_SkinnedPrimitive_x64_Debug.h"
        #include "_AutoGenerated/VS_StaticPrimitive_x64_Debug.h"
        #include "_AutoGenerated/PS_LitPicking_x64_Debug.h"
    #elif EE_RELEASE
        #include "_AutoGenerated/CS_PrecomputeDFG_x64_Release.h"
        #include "_AutoGenerated/PS_Empty_x64_Release.h"
        #include "_AutoGenerated/PS_Lit_x64_Release.h"
        #include "_AutoGenerated/PS_Skybox_x64_Release.h"
        #include "_AutoGenerated/VS_Cube_x64_Release.h"
        #include "_AutoGenerated/VS_SkinnedPrimitive_x64_Release.h"
        #include "_AutoGenerated/VS_StaticPrimitive_x64_Release.h"
        #include "_AutoGenerated/PS_LitPicking_x64_Release.h"
    #elif EE_SHIPPING
        #include "_AutoGenerated/CS_PrecomputeDFG_x64_Shipping.h"
        #include "_AutoGenerated/PS_Empty_x64_Shipping.h"
        #include "_AutoGenerated/PS_Lit_x64_Shipping.h"
        #include "_AutoGenerated/PS_Skybox_x64_Shipping.h"
        #include "_AutoGenerated/VS_Cube_x64_Shipping.h"
        #include "_AutoGenerated/VS_SkinnedPrimitive_x64_Shipping.h"
        #include "_AutoGenerated/VS_StaticPrimitive_x64_Shipping.h"
        #include "_AutoGenerated/PS_LitPicking_x64_Shipping.h"
    #else
        #error 1
    #endif
#endif