#pragma once

#include "Base/Esoterica.h"

//-------------------------------------------------------------------------

#ifdef _WIN32

    typedef unsigned char BYTE;

    #ifdef EE_DEBUG
        #include "_AutoGenerated/PS_imgui_x64_Debug.h"
        #include "_AutoGenerated/VS_imgui_x64_Debug.h"
    #elif EE_RELEASE
        #include "_AutoGenerated/PS_imgui_x64_Release.h"
        #include "_AutoGenerated/VS_imgui_x64_Release.h"
    #elif EE_SHIPPING
        #include "_AutoGenerated/PS_imgui_x64_Shipping.h"
        #include "_AutoGenerated/VS_imgui_x64_Shipping.h"
    #else
        #error 1
    #endif
#endif