#include "EditorApplication_Win32.h"
#include "EngineTools/_Module/_AutoGenerated/TypeInfo/TypeRegistration.h"
#include "EngineTools/Core/SystemDialogs.h"

#include "Resource.h"
#include <tchar.h>
#include <windows.h>

//-------------------------------------------------------------------------

namespace EE
{
    EditorEngine::EditorEngine( TFunction<bool( EE::String const& error )>&& errorHandler )
        : Engine( eastl::forward<TFunction<bool( EE::String const& error )>&&>( errorHandler ) )
    {
        m_modules.emplace_back( EE::New<EngineToolsModule>() );
        m_modules.emplace_back( EE::New<GameModule>() );
        m_modules.emplace_back( EE::New<GameToolsModule>() );
    }

    void EditorEngine::RegisterTypes()
    {
        TypeSystem::Reflection::RegisterTypes( *m_pTypeRegistry );
    }

    void EditorEngine::UnregisterTypes()
    {
        TypeSystem::Reflection::UnregisterTypes( *m_pTypeRegistry );
    }

    void EditorEngine::SetStartupMap( ResourceID const& mapID )
    {
        EE_ASSERT( mapID.IsValid() );
        static_cast<EditorUI*>( m_pToolsUI )->SetStartupMap( mapID );
    }

    //-------------------------------------------------------------------------

    EditorApplication::EditorApplication( HINSTANCE hInstance )
        : Win32Application( hInstance, "Esoterica Editor", IDI_EDITOR_ICON, 102, TBitFlags<InitOptions>( Win32Application::InitOptions::Borderless ) )
        , m_engine( TFunction<bool( String const& error )>( [this] ( String const& error )-> bool  { return FatalError( error ); } ) )
    {}

    void EditorApplication::GetBorderlessTitleBarInfo( Math::ScreenSpaceRectangle& outTitlebarRect, bool& isInteractibleWidgetHovered ) const
    {
        static_cast<EditorUI*>( m_engine.m_pToolsUI )->GetBorderlessTitleBarInfo( outTitlebarRect, isInteractibleWidgetHovered );
    }

    void EditorApplication::ResizeMainWindow( Int2 const& newWindowSize )
    {
        m_engine.ResizeMainWindow( newWindowSize );
    }

    void EditorApplication::ProcessInputMessage( UINT message, WPARAM wParam, LPARAM lParam )
    {
        m_engine.GetInputSystem()->ForwardInputMessageToInputDevices( { message, (uintptr_t) wParam, (uintptr_t) lParam } );
    }

    bool EditorApplication::Initialize( int32_t argc, char** argv )
    {
        #if EE_ENABLE_LPP
        LivePP_CreateAgent();
        LivePP_EnableModules();
        #endif

        Int2 const windowDimensions( ( m_windowRect.right - m_windowRect.left ), ( m_windowRect.bottom - m_windowRect.top ) );
        if ( !m_engine.Initialize( argc, argv, windowDimensions ) )
        {
            return false;
        }

        return true;
    }

    bool EditorApplication::Shutdown()
    {
        #if EE_ENABLE_LPP
        LivePP_DestroyAgent();
        #endif

        return m_engine.Shutdown();
    }

    bool EditorApplication::FatalError( String const& error ) const
    {
        if ( m_engine.m_pToolsUI != nullptr )
        {
            MessageDialog dlg;
            if ( dlg.Confirmation( Severity::FatalError, "Fatal Error Occurred", "A fatal error has occurred and the editor will be shutdown. Do you wish to save any unsaved work?\n\nError: %s", error.c_str() ) )
            {
                auto pEditorUI = static_cast<EditorUI*>( m_engine.m_pToolsUI );
                if ( pEditorUI->HasOpenAndDirtyTools() )
                {
                    pEditorUI->SaveAllDirtyTools();
                }
            }

            return false;
        }
        else
        {
            return Win32Application::FatalError( error );
        }
    }

    bool EditorApplication::ApplicationLoop()
    {
        #if EE_ENABLE_LPP
        LivePP_UpdateAgent();
        #endif

        return m_engine.Update();
    }
}

//-------------------------------------------------------------------------

int APIENTRY _tWinMain( HINSTANCE hInstance, HINSTANCE hPrevInstance, LPTSTR lpCmdLine, int nCmdShow )
{
    int32_t result = 0;
    {
        EE::ApplicationGlobalState globalState;
        EE::EditorApplication editorApplication( hInstance );
        result = editorApplication.Run( __argc, __argv );
    }

    return result;
}