#pragma once

#include "Base/Logging/Log.h"
#include "Base/FileSystem/FileSystemPath.h"
#include <sstream>

//-------------------------------------------------------------------------

namespace EE::Reflection
{
    class Reflector;
    class ReflectedProject;
    class ReflectedShader;

    //-------------------------------------------------------------------------

    class CodeGenerator : public Log
    {
    public:

        CodeGenerator( Reflector& reflector )
            : m_reflector( reflector )
        {}

        virtual ~CodeGenerator() = default;

        virtual bool GenerateCodeForSolution() = 0;

    protected:

        inline void CreateAutogeneratedHeader( std::stringstream &stream, FileSystem::Path const& filePath = FileSystem::Path() ) const
        {
            stream << "//-------------------------------------------------------------------------\n";
            stream << "// This is an auto-generated file - DO NOT edit\n";
            stream << "//-------------------------------------------------------------------------\n";

            if ( filePath.IsValid() )
            {
                stream << "// Generated For: " << filePath.c_str() << "\n\n";
            }
            else
            {
                stream << "\n";
            }
        }

    protected:

        Reflector& m_reflector;
    };
}
