#pragma once
#include "ReflectedProject.h"
#include "Base/FileSystem/FileSystemPath.h"
#include <sstream>

//-------------------------------------------------------------------------

namespace EE::Reflection
{
    class Reflector
    {
    public:

        enum class Output
        {
            ShadersAndTypeInfo,
            Shaders,
            TypeInfo
        };

        enum class Operation
        { 
            IncrementalBuild,
            Rebuild,
            Clean,
            HotReload, // Only valid for shaders!
        };

        EE_FORCE_INLINE static bool IsShaderOutputRequired( Output output ) { return output != Output::TypeInfo; }
        EE_FORCE_INLINE static bool IsTypeInfoOutputRequired( Output output ) { return output != Output::Shaders; }

    public:

        Reflector( FileSystem::Path const& m_solutionPath );

        // Solution
        //-------------------------------------------------------------------------

        FileSystem::Path const& GetSolutionPath() const { return m_solutionPath; }
        FileSystem::Path const& GetSolutionDirectoryPath() const { return m_solutionDirectoryPath; }
        FileSystem::Path const& GetRuntimeTypeRegistrationFilePath() const { return m_runtimeTypeRegistrationFilePath; }
        FileSystem::Path const& GetToolsTypeRegistrationFilePath() const { return m_toolsTypeRegistrationFilePath; }
        FileSystem::Path const& GetTypeInfoDataXMLFilePath() const { return m_typeinfoDataXMLFilePath; }
        FileSystem::Path const& GetShaderRegistrationHeaderFilePath() const { return m_shaderRegistrationHeaderFilePath; }
        FileSystem::Path const& GetShaderRegistrationSourceFilePath() const { return m_shaderRegistrationSourceFilePath; }
        FileSystem::Path const& GetShaderMetadataXMLFilePath() const { return m_shaderMetadataXMLFilePath; }

        TVector<ReflectedProject> const& GetProjects() const { return m_projects; }

        // Execution
        //-------------------------------------------------------------------------

        bool Run( Output desiredOutput, Operation operation );

        // Code Generation
        //-------------------------------------------------------------------------

        void AddGeneratedFile( FileSystem::Path const& path, char const* pFileContents );

    private:

        bool ParseSolution();
        bool ParseProject( ReflectedProject& project );
        bool ParseHeader( ReflectedProject& project, FileSystem::Path const& path );

        bool CleanOutputs( Output desiredOutput, bool silentMode = false );

        bool Reflect( Output desiredOutput, Operation operation );
        bool ReflectShaders( Output desiredOutput );
        bool ReflectTypeInfo();

        bool WriteGeneratedFiles( Output desiredOutput );

        bool ShaderParameterFilesWereUpdated( FileSystem::Path const& directoryPath, TVector<GeneratedFile> const& expectedFiles ) const;

        bool UpdateAutogeneratedDirectory( FileSystem::Path const& directoryPath, TVector<GeneratedFile> const& expectedFiles, bool& wereFilesAddedOrRemoved ) const;

    private:

        FileSystem::Path const                              m_solutionPath;
        FileSystem::Path const                              m_solutionDirectoryPath;

        FileSystem::Path                                    m_runtimeTypeRegistrationFilePath;
        FileSystem::Path                                    m_toolsTypeRegistrationFilePath;
        FileSystem::Path                                    m_typeinfoDataXMLFilePath;
        FileSystem::Path                                    m_shaderMetadataXMLFilePath;

        FileSystem::Path                                    m_shaderRegistrationHeaderFilePath;
        FileSystem::Path                                    m_shaderRegistrationSourceFilePath;

        TVector<ReflectedProject>                           m_projects;
        TVector<GeneratedFile>                              m_miscGeneratedFiles;
        bool                                                m_shaderReflectionRequiresTypeReflection = false;
    };
}