#include "Reflector.h"
#include "ReflectedMacro.h"
#include "ShaderReflection/ShaderReflection_ShaderParser.h"
#include "ShaderReflection/ShaderReflection_ShaderCompiler.h"
#include "ShaderReflection/ShaderReflection_CodeGenerator.h"
#include "ShaderReflection/ShaderReflection_ShaderInputReflector.h"
#include "TypeReflection/TypeReflection_CodeGenerator.h"
#include "TypeReflection/Clang/ClangParser.h"
#include "Base/FileSystem/FileSystem.h"
#include "Base/Utils/TopologicalSort.h"
#include "Base/FileSystem/FileSystemUtils.h"
#include "Base/Time/Timers.h"

#include <iostream>
#include <fstream>
#include <string>

//-------------------------------------------------------------------------

namespace EE::Reflection
{
    static bool CleanDirectory( FileSystem::Path const& directoryPath, bool silentMode )
    {
        if ( FileSystem::IsExistingDirectory( directoryPath ) )
        {
            if ( !FileSystem::EraseDir( directoryPath ) )
            {
                if ( !silentMode )
                {
                    PrintError( "Failed erasing directory: %s", directoryPath.c_str() );
                }

                return false;
            }

            if ( !FileSystem::CreateDir( directoryPath ) )
            {
                if ( !silentMode )
                {
                    PrintError( "Failed creating directory: %s", directoryPath.c_str() );
                }

                return false;
            }
        }

        return true;
    };

    static bool CleanFile( FileSystem::Path const& filePath, char const * const pLabel, bool silentMode )
    {
        if ( FileSystem::Exists( filePath ) )
        {
            if ( FileSystem::EraseFile( filePath ) )
            {
                if ( !silentMode )
                {
                    std::cout << "  Cleaning " << pLabel << " - " << filePath.c_str() << std::endl;
                }
            }
            else
            {
                if ( !silentMode )
                {
                    PrintError( "Failed erasing file: %s", filePath.c_str() );
                }

                return false;
            }
        }

        return true;
    };

    static bool IsShaderParametersFilename( FileSystem::Path const& filePath )
    {
        if ( !filePath.IsValid() || !filePath.IsFilePath() )
        {
            return false;
        }

        String const filename = filePath.GetFilename();
        return StringUtils::EndsWith( filename.c_str(), Settings::g_reflectedParametersFilenameSuffixAndExtension );
    }

    static bool DoTextFileContentsDiffer( FileSystem::Path const& filePath, String const& expectedContents )
    {
        EE_ASSERT( filePath.IsValid() && filePath.IsFilePath() );
        EE_ASSERT( !expectedContents.empty() );

        bool shouldUpdateFile = false;
        if ( Exists( filePath ) )
        {
            String currentFileContents;
            if ( !FileSystem::ReadTextFile( filePath, currentFileContents ) )
            {
                return true;
            }

            if ( currentFileContents != expectedContents )
            {
                return true;
            }

            return false;
        }
        else
        {
            return true;
        }
    }

    static char const* GetStringForOutput( Reflector::Output output )
    {
        static constexpr char const * const outputNames[] =
        {
            "Shaders and TypeInfo",
            "Shaders",
            "TypeInfo",
        };

        return outputNames[int32_t( output )];
    }

    static char const* GetStringForOperation( Reflector::Operation operation )
    {
        static constexpr char const * const operationNames[] =
        {
            "Incremental Build",
            "Rebuild",
            "Clean",
            "Shader Hot-Reload"
        };

        return operationNames[int32_t( operation )];
    }

    //-------------------------------------------------------------------------

    Reflector::Reflector( FileSystem::Path const& solutionPath )
        : m_solutionPath( solutionPath )
        , m_solutionDirectoryPath( solutionPath.GetParentDirectory() )
    {
        EE_ASSERT( m_solutionPath.IsFilePath() && m_solutionPath.Exists() );

        m_runtimeTypeRegistrationFilePath = m_solutionDirectoryPath;
        m_runtimeTypeRegistrationFilePath.Append( Settings::g_runtimeEngineProjectPath, true );
        m_runtimeTypeRegistrationFilePath.Append( Settings::g_moduleDirectoryName, true );
        m_runtimeTypeRegistrationFilePath.Append( Settings::g_autogeneratedDirectoryName, true );
        m_runtimeTypeRegistrationFilePath.Append( Settings::g_autogeneratedTypeInfoDirectoryName, true );
        m_runtimeTypeRegistrationFilePath.Append( Settings::g_typeRegistrationFileName, false );

        m_toolsTypeRegistrationFilePath = m_solutionDirectoryPath;
        m_toolsTypeRegistrationFilePath.Append( Settings::g_toolsEngineProjectPath, true );
        m_toolsTypeRegistrationFilePath.Append( Settings::g_moduleDirectoryName, true );
        m_toolsTypeRegistrationFilePath.Append( Settings::g_autogeneratedDirectoryName, true );
        m_toolsTypeRegistrationFilePath.Append( Settings::g_autogeneratedTypeInfoDirectoryName, true );
        m_toolsTypeRegistrationFilePath.Append( Settings::g_typeRegistrationFileName, false );

        m_typeinfoDataXMLFilePath = m_solutionDirectoryPath.GetAppended( Settings::g_buildFolderPath, true ).GetAppended( Settings::g_typeDataXMLFilename );
        m_shaderMetadataXMLFilePath = m_solutionDirectoryPath.GetAppended( Settings::g_buildFolderPath, true ).GetAppended( Settings::g_shaderMetadataXMLFilename );

        //-------------------------------------------------------------------------

        FileSystem::Path registrationFileBasePath = m_solutionDirectoryPath;
        registrationFileBasePath.Append( Settings::g_runtimeEngineProjectPath, true );
        registrationFileBasePath.Append( Settings::g_moduleDirectoryName, true );
        registrationFileBasePath.Append( Settings::g_autogeneratedDirectoryName, true );
        registrationFileBasePath.Append( Settings::g_autogeneratedShaderDirectoryName, true );
        registrationFileBasePath.Append( Settings::g_shaderRegistrationFileNameNoExtension, false );

        m_shaderRegistrationHeaderFilePath = registrationFileBasePath;
        m_shaderRegistrationHeaderFilePath.Append( ".h", false );

        m_shaderRegistrationSourceFilePath = registrationFileBasePath;
        m_shaderRegistrationSourceFilePath.Append( ".cpp", false );
    }

    bool Reflector::Run( Output desiredOutput, Operation operation )
    {
        system( "cls" );

        std::cout << std::endl;
        std::cout << "*****************************************************" << std::endl;
        std::cout << "*                ESOTERICA REFLECTOR                *" << std::endl;
        std::cout << "*****************************************************" << std::endl;
        std::cout << "  Solution: " << m_solutionPath.c_str() << std::endl;
        std::cout << "  Outputs: " << GetStringForOutput( desiredOutput ) << std::endl;
        std::cout << "  Operation: " << GetStringForOperation( operation ) << std::endl;
        std::cout << "*****************************************************" << std::endl;

        if ( !ParseSolution() )
        {
            return false;
        }

        if ( !Reflect( desiredOutput, operation ) )
        {
            return false;
        }

        return true;
    }

    //-------------------------------------------------------------------------
    // Parsing
    //-------------------------------------------------------------------------

    bool Reflector::ParseSolution()
    {
        m_projects.clear();
        m_shaderReflectionRequiresTypeReflection = false;

        //-------------------------------------------------------------------------

        std::ifstream slnFile( m_solutionPath );
        if ( !slnFile.is_open() )
        {
            return PrintError( "Could not open solution: %s", m_solutionPath.c_str() );
        }

        //-------------------------------------------------------------------------

        auto IsUnderToolsPath = [] ( FileSystem::Path const& path )
        {
            String const& filePathStr = path.GetString();
            for ( auto pToolsProjectName : Settings::g_toolProjectFolderNames )
            {
                InlineString const searchStr( InlineString::CtorSprintf(), "\\%s\\", pToolsProjectName );
                if ( filePathStr.find( searchStr.c_str() ) != String::npos )
                {
                    return true;
                }
            }

            return false;
        };

        static char const* projectPathPrefix = " Path=\"";
        static size_t const projectPathPrefixLength = strlen( projectPathPrefix );

        std::string stdLine;
        while ( std::getline( slnFile, stdLine ) )
        {
            String line( stdLine.c_str() );

            if ( line.find( "<Project" ) != String::npos ) // VS Project UID
            {
                auto projectPathStartIdx = line.find( projectPathPrefix );
                EE_ASSERT( projectPathStartIdx != std::string::npos );
                projectPathStartIdx += projectPathPrefixLength;
                auto projectPathEndIdx = line.find( "\"", projectPathStartIdx );
                EE_ASSERT( projectPathEndIdx != std::string::npos );

                String const projectPathString = line.substr( projectPathStartIdx, projectPathEndIdx - projectPathStartIdx );
                FileSystem::Path const projectPath = m_solutionDirectoryPath + projectPathString;

                //-------------------------------------------------------------------------

                ReflectedProject& project = m_projects.emplace_back();
                project.m_ID = ReflectedProject::GetProjectID( projectPath );
                project.m_path = projectPath;
                project.m_directoryPath = projectPath.GetParentDirectory();
                project.m_isToolsProject = IsUnderToolsPath( projectPath );

                // Generated output paths
                {
                    project.m_autogeneratedDirectoryPath = project.m_directoryPath;
                    project.m_autogeneratedDirectoryPath.Append( Settings::g_moduleDirectoryName, true );
                    project.m_autogeneratedDirectoryPath.Append( Settings::g_autogeneratedDirectoryName, true );

                    project.m_autogeneratedTypeInfoDirectoryPath = project.m_autogeneratedDirectoryPath;
                    project.m_autogeneratedTypeInfoDirectoryPath.Append( Settings::g_autogeneratedTypeInfoDirectoryName, true );

                    project.m_autogeneratedShaderDirectoryPath = project.m_autogeneratedDirectoryPath;
                    project.m_autogeneratedShaderDirectoryPath.Append( Settings::g_autogeneratedShaderDirectoryName, true );

                    project.m_autogeneratedShaderReflectionDirectoryPath = project.m_autogeneratedDirectoryPath;
                    project.m_autogeneratedShaderReflectionDirectoryPath.Append( Settings::g_autogeneratedShaderReflectionDirectoryName, true );
                }

                // Check against shader projects
                for ( char const* const pAllowedShaderProjectName : Settings::g_allowedShaderProjectNames )
                {
                    if ( project.m_path.ToString().find( pAllowedShaderProjectName ) != String::npos )
                    {
                        project.m_isExcludedFromShaderReflection = false;
                        break;
                    }
                }

                // Check against typeinfo projects
                for ( char const* const pAllowedTypeInfoProjectName : Settings::g_allowedTypeInfoProjectNames )
                {
                    if ( project.m_path.ToString().find( pAllowedTypeInfoProjectName ) != String::npos )
                    {
                        project.m_isExcludedFromTypeInfoReflection = false;
                        break;
                    }
                }
            }
        }

        slnFile.close();

        // Parse all relevant projects
        //-------------------------------------------------------------------------

        for ( auto& project : m_projects )
        {
            if ( project.IsRelevantForReflection() )
            {
                if ( !ParseProject( project ) )
                {
                    return false;
                }
            }
            else
            {
                project.m_name = project.m_path.GetFilenameWithoutExtension();
            }
        }

        // Sort projects by dependencies
        //-------------------------------------------------------------------------

        int32_t const numProjects = (int32_t) m_projects.size();
        if ( numProjects > 1 )
        {
            // Create list to sort
            TVector<TopologicalSorter::Node > list;
            for ( auto p = 0; p < numProjects; p++ )
            {
                list.push_back( TopologicalSorter::Node( p ) );
            }

            for ( auto p = 0; p < numProjects; p++ )
            {
                int32_t const numDependencies = (int32_t) m_projects[p].m_dependencies.size();
                for ( auto d = 0; d < numDependencies; d++ )
                {
                    for ( auto pp = 0; pp < numProjects; pp++ )
                    {
                        if ( p != pp && m_projects[pp].m_ID == m_projects[p].m_dependencies[d] )
                        {
                            list[p].m_children.push_back( &list[pp] );
                        }
                    }
                }
            }

            // Try to sort
            if ( !TopologicalSorter::Sort( list ) )
            {
                return false;
            }

            // Update project list
            uint32_t depValue = 0;
            TVector<ReflectedProject> sortedProjects;
            sortedProjects.reserve( numProjects );

            for ( auto& node : list )
            {
                sortedProjects.push_back( m_projects[node.m_ID] );
                sortedProjects.back().m_dependencyCount = depValue++;
            }
            m_projects.swap( sortedProjects );
        }

        return true;
    }

    bool Reflector::ParseProject( ReflectedProject& project )
    {
        std::ifstream prjFile( project.m_path );
        if ( !prjFile.is_open() )
        {
            PrintError( "Could not open project file: %s", project.m_path.c_str() );
            return false;
        }

        TVector<FileSystem::Path> headerFiles;
        TVector<FileSystem::Path> shaderFiles;

        std::string stdLine;
        while ( std::getline( prjFile, stdLine ) )
        {
            String line( stdLine.c_str() );

            // Name
            auto firstIdx = line.find( "<ProjectName>" );
            if ( firstIdx != String::npos )
            {
                firstIdx += 13;
                project.m_name = line.substr( firstIdx, line.find( "</Project" ) - firstIdx );
                continue;
            }

            // Dependencies
            firstIdx = line.find( "<ProjectReference Include=\"" );
            if ( firstIdx != String::npos )
            {
                firstIdx += 27;
                String dependencyPath = line.substr( firstIdx, line.find( "\">" ) - firstIdx );
                dependencyPath = project.m_directoryPath + dependencyPath;
                StringID dependencyID = ReflectedProject::GetProjectID( dependencyPath );
                project.m_dependencies.push_back( dependencyID );
                continue;
            }

            // Header Files
            firstIdx = line.find( "<ClInclude" );
            if ( firstIdx != String::npos )
            {
                firstIdx = line.find( "Include=\"" );
                EE_ASSERT( firstIdx != String::npos );
                firstIdx += 9;
                auto secondIdx = line.find( "\"", firstIdx );
                EE_ASSERT( secondIdx != String::npos );

                String const headerPathStr = line.substr( firstIdx, secondIdx - firstIdx );

                // Ignore auto-generated files
                if ( headerPathStr.find( Settings::g_autogeneratedDirectoryName ) != String::npos )
                {
                    continue;
                }

                headerFiles.emplace_back( project.m_directoryPath + headerPathStr );
            }

            // Shader files
            //-------------------------------------------------------------------------

            firstIdx = line.find( "<None" );
            if ( firstIdx != String::npos )
            {
                firstIdx = line.find( "Include=\"" );
                EE_ASSERT( firstIdx != String::npos );
                firstIdx += 9;
                auto secondIdx = line.find( "\"", firstIdx );
                EE_ASSERT( secondIdx != String::npos );

                String const shaderFilePathStr = line.substr( firstIdx, secondIdx - firstIdx );
                if ( shaderFilePathStr.find( Settings::g_shaderSourceFileExtension ) != String::npos )
                {
                    shaderFiles.emplace_back( project.m_directoryPath + shaderFilePathStr );
                }
            }
        }

        prjFile.close();

        // Name Validation
        //-------------------------------------------------------------------------

        if ( project.m_name.empty() )
        {
            PrintError( "Invalid project file detected: %s", project.m_path.c_str() );
            return false;
        }

        project.m_isBaseProject = ( project.m_name == Settings::g_baseProjectName );

        // Parse Headers
        //-------------------------------------------------------------------------

        project.m_headerFiles.reserve( headerFiles.size() );

        for ( auto const& headerPath : headerFiles )
        {
            // Parse header
            if ( !ParseHeader( project, headerPath ) )
            {
                PrintError( "Error parsing header: %s", headerPath.c_str() );
                return false;
            }
        }

        // Read shaders
        //-------------------------------------------------------------------------

        for ( auto const& shaderPath : shaderFiles )
        {
            ReflectedShader& shader = project.m_shaders.emplace_back();
            shader.m_path = shaderPath;
            shader.m_name = shaderPath.GetFilenameWithoutExtension();

            InlineString filename( InlineString::CtorSprintf(), "%s.cpp", shader.m_name.c_str() );
            shader.m_compiledShaderPath = project.m_autogeneratedShaderDirectoryPath.GetAppended( filename.c_str() );

            filename = InlineString( InlineString::CtorSprintf(), "%s%s", shader.m_name.c_str(), Settings::g_reflectedParametersFilenameSuffixAndExtension );
            shader.m_reflectedParametersFilePath = project.m_autogeneratedShaderDirectoryPath.GetAppended( filename.c_str() );
        }

        return true;
    }

    bool Reflector::ParseHeader( ReflectedProject& project, FileSystem::Path const& path )
    {
        EE_ASSERT( path.IsValid() && path.IsFilePath() );

        // Create reflected header
        ReflectedHeader& header = project.m_headerFiles.emplace_back();
        header.m_path = path;
        header.m_ID = ReflectedHeader::GetHeaderID( header.m_path );
        header.m_projectID = project.m_ID;
        header.m_timestamp = FileSystem::GetFileModifiedTime( header.m_path );
        header.m_isToolsOnlyHeader = project.m_isToolsProject;

        // Check if this is a special header
        enum HeaderType { Default, API, Module };

        HeaderType headerType = HeaderType::Default;

        if ( header.m_path.GetParentDirectory().GetDirectoryName() == Settings::g_moduleDirectoryName )
        {
            if ( header.m_path.IsFilenameEqual( Settings::g_moduleAPIFilename ) )
            {
                headerType = HeaderType::API;
            }
            else if ( StringUtils::EndsWith( header.m_path.GetFilename(), Settings::g_moduleFileSuffix ) )
            {
                headerType = HeaderType::Module;
            }
        }

        // Set up type-info output path
        EE_ASSERT( project.m_autogeneratedTypeInfoDirectoryPath.IsDirectoryPath() );
        InlineString const filenameStr( InlineString::CtorSprintf(), "%s.%s.%s", header.m_path.GetFilenameWithoutExtension().c_str(), Settings::g_typeinfoFileSuffix, "cpp" );
        header.m_typeInfoPath = project.m_autogeneratedTypeInfoDirectoryPath.GetAppended( filenameStr.c_str() );

        //-------------------------------------------------------------------------

        // Open header file
        std::ifstream hdrFile( header.m_path, std::ios::in | std::ios::binary | std::ios::ate );
        if ( !hdrFile.is_open() )
        {
            PrintError( "Could not open header file: %s", header.m_path.c_str() );
            project.m_headerFiles.pop_back();
            return false;
        }

        // Check file size
        uint32_t const size = (uint32_t) hdrFile.tellg();
        if ( size == 0 )
        {
            hdrFile.close();
            project.m_headerFiles.pop_back();
            return true;
        }
        hdrFile.seekg( 0, std::ios::beg );

        // Read file contents
        std::string stdLine;
        while ( std::getline( hdrFile, stdLine ) )
        {
            header.m_fileContents.emplace_back( stdLine.c_str() );
        }
        hdrFile.close();

        //-------------------------------------------------------------------------

        // Check for the EE registration macros
        uint32_t openCommentBlock = 0;

        for ( auto const& line : header.m_fileContents )
        {
            // Check for comment blocks
            if ( line.find( "/*" ) != String::npos ) openCommentBlock++;
            if ( line.find( "*/" ) != String::npos ) openCommentBlock--;

            if ( openCommentBlock == 0 )
            {
                // Check for line comment
                auto const foundCommentIdx = line.find( "//" );

                // Check for registration macros
                for ( auto i = 0u; i < (uint32_t) ReflectionMacro::NumMacros; i++ )
                {
                    ReflectionMacro const macro = (ReflectionMacro) i;
                    auto const foundMacroIdx = line.find( GetReflectionMacroText( macro ) );
                    bool const macroExists = foundMacroIdx != String::npos;
                    bool const uncommentedMacro = foundCommentIdx == String::npos || foundCommentIdx > foundMacroIdx;

                    if ( macroExists && uncommentedMacro )
                    {
                        // We should never have registration macros and the export definition in the same file
                        if ( headerType == HeaderType::API )
                        {
                            PrintError( "EE registration macro found in the module export API header(%)!", header.m_path.c_str() );
                            project.m_headerFiles.pop_back();
                            return false;
                        }

                        // We have a valid registration macro and so this file needs to be processed
                        if ( headerType == HeaderType::Module )
                        {
                            if ( project.m_moduleHeaderID.IsValid() )
                            {
                                PrintError( "Multiple module headers found!" );
                                return false;
                            }

                            project.m_moduleHeaderID = header.m_ID;
                        }
                        return true;
                    }
                }

                // Check header for the module export definition
                if ( headerType == HeaderType::API )
                {
                    auto const foundExportIdx0 = line.find( "__declspec" );
                    auto const foundExportIdx1 = line.find( "dllexport" );
                    if ( foundExportIdx0 != String::npos && foundExportIdx1 != String::npos )
                    {
                        if ( !header.m_exportMacro.empty() )
                        {
                            PrintError( "Duplicate export macro definitions found!", header.m_path.c_str() );
                            return false;
                        }
                        else
                        {
                            auto defineIdx = line.find( "#define" );
                            if ( defineIdx != String::npos )
                            {
                                defineIdx += 8;
                                header.m_exportMacro = line.substr( defineIdx, foundExportIdx0 - 1 - defineIdx );
                            }

                            // Early out for module headers once we've read the export macro
                            if ( !project.m_exportMacro.empty() )
                            {
                                PrintError( "Multiple module API headers found!" );
                                project.m_headerFiles.pop_back();
                                return false;
                            }

                            project.m_headerFiles.pop_back();
                            project.m_exportMacro = header.m_exportMacro;
                            return true;
                        }
                    }
                }
            }
        }

        //-------------------------------------------------------------------------

        project.m_headerFiles.pop_back();
        return true;
    }

    //-------------------------------------------------------------------------
    // Reflection
    //-------------------------------------------------------------------------

    bool Reflector::Reflect( Output desiredOutput, Operation operation )
    {
        if ( operation == Operation::HotReload )
        {
            EE_ASSERT( desiredOutput == Output::Shaders );
        }

        // Clean
        //-------------------------------------------------------------------------

        if ( operation == Operation::Clean || operation == Operation::Rebuild )
        {
            if ( !CleanOutputs( desiredOutput ) )
            {
                return false;
            }
        }

        // Build
        //-------------------------------------------------------------------------

        if ( operation == Operation::IncrementalBuild || operation == Operation::Rebuild || operation == Operation::HotReload )
        {
            // Shaders
            //-------------------------------------------------------------------------

            if ( IsShaderOutputRequired( desiredOutput ) )
            {
                if ( !ReflectShaders( desiredOutput ) )
                {
                    return false;
                }

                // Did the shader reflection result in changes to the engine types requiring us to re-run reflection?
                if ( m_shaderReflectionRequiresTypeReflection )
                {
                    if ( operation == Operation::HotReload )
                    {
                        return PrintError( "Shader Hot-Reload will result in changes to the engine runtime types requiring type reflection. Aborting Hot-Reload!" );
                    }

                    if ( !IsTypeInfoOutputRequired( desiredOutput ) )
                    {
                        // If this was a rebuild, we need to clean all typeinfo
                        if ( operation == Operation::Rebuild )
                        {
                            CleanOutputs( Output::TypeInfo, true );
                        }

                        desiredOutput = Output::ShadersAndTypeInfo;
                    }
                }

                if ( !WriteGeneratedFiles( Output::Shaders ) )
                {
                    return false;
                }
            }

            // TypeInfo
            //-------------------------------------------------------------------------

            if ( IsTypeInfoOutputRequired( desiredOutput ) )
            {
                if ( !ReflectTypeInfo() )
                {
                    return false;
                }

                if ( !WriteGeneratedFiles( Output::TypeInfo ) )
                {
                    return false;
                }
            }
        }

        // Bump Project Files
        //-------------------------------------------------------------------------

        for ( ReflectedProject& project : m_projects )
        {
            if ( project.m_requiresReload )
            {
                String projectFileContents;
                if ( FileSystem::ReadTextFile( project.m_path, projectFileContents ) )
                {
                    if ( !FileSystem::WriteTextFile( project.m_path, projectFileContents ) )
                    {
                        return PrintError( " * Failed to re-save project file: %s", project.m_path.c_str() );
                    }
                }
                else
                {
                    return PrintError( " * Failed to re-save project file: %s", project.m_path.c_str() );
                }
            }
        }

        return true;
    }

    bool Reflector::CleanOutputs( Output desiredOutput, bool silentMode )
    {
        auto CleaningError = [silentMode] ()
        {
            if ( !silentMode )
            {
                std::cout << std::endl;
                std::cout << "  ** Cleaning Failed! **" << std::endl;
            }

            return false;
        };

        //-------------------------------------------------------------------------

        if ( !silentMode )
        {
            std::cout << std::endl;
            std::cout << ">> Cleaning" << std::endl;
            std::cout << "-----------------------------------------------------" << std::endl << std::endl;
        }

        //-------------------------------------------------------------------------

        TVector<FileSystem::Path> generatedFiles;

        // Delete all auto-generated directories for valid projects
        for ( ReflectedProject& prj : m_projects )
        {
            if ( !silentMode )
            {
                std::cout << "  Cleaning Project: " << prj.m_name.c_str() << std::endl;
            }

            if ( IsShaderOutputRequired( desiredOutput ) )
            {
                if ( !CleanDirectory( prj.m_autogeneratedShaderDirectoryPath, silentMode ) )
                {
                    return CleaningError();
                }

                if ( !CleanDirectory( prj.m_autogeneratedShaderReflectionDirectoryPath, silentMode ) )
                {
                    return CleaningError();
                }
            }

            if ( IsTypeInfoOutputRequired( desiredOutput ) )
            {
                if ( !CleanDirectory( prj.m_autogeneratedTypeInfoDirectoryPath, silentMode ) )
                {
                    return CleaningError();
                }
            }

            // Delete all auto-generated directories for excluded projects (just to be safe)
            if ( !prj.IsRelevantForReflection() )
            {
                if ( !CleanDirectory( prj.m_autogeneratedDirectoryPath, silentMode ) )
                {
                    return CleaningError();
                }
            }

            prj.m_requiresReload = true;
        }

        // Registration Files
        //-------------------------------------------------------------------------

        if ( IsShaderOutputRequired( desiredOutput ) )
        {
            if ( !CleanFile( m_shaderRegistrationHeaderFilePath, "Shader Registration Header", silentMode ) )
            {
                return CleaningError();
            }

            if ( !CleanFile( m_shaderRegistrationSourceFilePath, "Shader Registration Source", silentMode ) )
            {
                return CleaningError();
            }
        }

        if ( IsTypeInfoOutputRequired( desiredOutput ) )
        {
            if ( !CleanFile( m_runtimeTypeRegistrationFilePath, "Runtime Type Registration", silentMode ) )
            {
                return CleaningError();
            }

            if ( !CleanFile( m_toolsTypeRegistrationFilePath, "Tools Type Registration", silentMode ) )
            {
                return CleaningError();
            }

            if ( !CleanFile( m_typeinfoDataXMLFilePath, "XML Reflection Data", silentMode ) )
            {
                return CleaningError();
            }
        }

        //-------------------------------------------------------------------------

        if ( !silentMode )
        {
            std::cout << std::endl;
            std::cout << "  ** Cleaning Success! **" << std::endl;
        }

        return true;
    }

    bool Reflector::ReflectShaders( Output desiredOutput )
    {
        EE_ASSERT( IsShaderOutputRequired( desiredOutput ) );

        m_shaderReflectionRequiresTypeReflection = false;

        // Parse Shaders
        //-------------------------------------------------------------------------

        std::cout << std::endl;
        std::cout << ">> Parsing Shaders" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        Milliseconds time = 0;

        {
            ScopedTimer<PlatformClock> timer( time );

            for ( ReflectedProject& project : m_projects )
            {
                if ( project.m_isExcludedFromShaderReflection )
                {
                    continue;
                }

                std::cout << "  Project: " << project.m_name.c_str() << " - ";

                if ( !project.m_shaders.empty() )
                {
                    ShaderParser shaderParser( project.m_shaders );
                    if ( !shaderParser.ParseShaders() )
                    {
                        return false;
                    }

                    std::cout << "Parsed! ( " << project.m_shaders.size() << " shader(s) found! )" << std::endl;
                }
                else
                {
                    std::cout << "  Project Ignored! ( No shaders found! )" << std::endl;
                }
            }
        }

        std::cout << std::endl;
        std::cout << "  ** Shader Parsing Success! ( " << time.ToFloat() << "ms ) **" << std::endl;

        // Shader List
        //-------------------------------------------------------------------------

        std::cout << std::endl;
        std::cout << ">> Shaders" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        for ( ReflectedProject& project : m_projects )
        {
            for ( ReflectedShader& shader : project.m_shaders )
            {
                std::cout << "  Shader: " << shader.m_name.c_str() << std::endl;
            }
        }

        // Write shader reflection
        //-------------------------------------------------------------------------

        std::cout << std::endl;
        std::cout << ">> Shader Input Reflection" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        {
            ScopedTimer<PlatformClock> timer( time );
            ShaderInputReflector inputReflector( m_projects );
            if ( !inputReflector.Reflect() )
            {
                return PrintError( inputReflector.GetErrorMessage() );
            }
        }

        std::cout << "  ** Shader Input Reflection Success! ( " << time.ToFloat() << "ms ) **" << std::endl;

        // Compile shaders
        //-------------------------------------------------------------------------

        int32_t const numPhysicalCores = Threading::GetNumPhysicalCores();

        std::cout << std::endl;
        std::cout << ">> Compiling Shaders ( using " << numPhysicalCores << " cores )" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        {
            ScopedTimer<PlatformClock> timer( time );
            ShaderCompiler compiler( m_solutionDirectoryPath, m_projects, numPhysicalCores );
            if ( !compiler.CompileShaders() )
            {
                return PrintError( compiler.GetErrorMessage() );
            }

            if ( compiler.HasWarnings() )
            {
                std::cout << "  * Warnings Occurred:" << std::endl;

                for ( auto const& warning : compiler.GetWarnings() )
                {
                    std::cout << "    " << warning.c_str() << std::endl;
                }

            }
        }

        std::cout << "  ** Shader Compilation Success! ( " << time.ToFloat() << "ms ) **" << std::endl;

        // Generate Code
        //-------------------------------------------------------------------------

        ShaderCodeGenerator generator( *this );

        std::cout << std::endl;
        std::cout << ">> Generating Shader Code" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        {
            ScopedTimer<PlatformClock> codeGenTimer( time );
            generator.GenerateCodeForSolution();
        }

        // Dump Log
        for ( auto const& entry : generator.GetLogEntries() )
        {
            if ( entry.m_severity == Severity::Error )
            {
                PrintError( entry.m_message.c_str() );
            }
            else
            {
                PrintWarning( entry.m_message.c_str() );
            }
        }

        if ( generator.HasErrors() )
        {
            std::cout << "  ** Shader Code Generation Failed! **" << std::endl;
            return false;
        }
        else
        {
            std::cout << "  ** Shader Code Generation Success! ( " << time.ToFloat() << "ms ) **" << std::endl;
        }

        // Detect whether shader reflection requires a typeinfo generation step
        //-------------------------------------------------------------------------

        if ( desiredOutput == Output::Shaders )
        {
            for ( auto const& project : m_projects )
            {
                if ( project.m_isExcludedFromShaderReflection )
                {
                    continue;
                }

                if ( ShaderParameterFilesWereUpdated( project.m_autogeneratedShaderDirectoryPath, project.m_generatedShaderFiles ) )
                {
                    m_shaderReflectionRequiresTypeReflection = true;
                    break;
                }
            }
        }
        else // Gonna generate typeinfo anyways so it doesnt hurt
        {
            m_shaderReflectionRequiresTypeReflection = true;
        }

        return true;
    }

    bool Reflector::ReflectTypeInfo()
    {
        // Parse headers
        //-------------------------------------------------------------------------

        std::cout << std::endl;
        std::cout << ">> Parsing Headers" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        TVector<ReflectedHeader*> headersToParse;
        for ( ReflectedProject& project : m_projects )
        {
            if ( project.m_isExcludedFromTypeInfoReflection )
            {
                continue;
            }

            // Add auto-generated shader headers
            if ( !project.m_isExcludedFromShaderReflection )
            {
                TVector<FileSystem::Path> generatedShaderParameterFiles;

                if ( project.m_autogeneratedShaderDirectoryPath.Exists() )
                {
                    if ( !FileSystem::GetDirectoryContents( project.m_autogeneratedShaderDirectoryPath, generatedShaderParameterFiles, FileSystem::DirectoryReaderOutput::OnlyFiles, FileSystem::DirectoryReaderMode::NoRecursion, { "h" } ) )
                    {
                        PrintError( "Error occurred while trying to find auto-generated shader parameter files" );
                        return false;
                    }
                }

                for ( FileSystem::Path const& headerPath : generatedShaderParameterFiles )
                {
                    String const filename = headerPath.GetFilename();
                    if ( !StringUtils::EndsWith( filename.c_str(), Settings::g_reflectedParametersFilenameSuffixAndExtension ) )
                    {
                        continue;
                    }

                    if ( !ParseHeader( project, headerPath ) )
                    {
                        PrintError( "Error parsing header: %s", headerPath.c_str() );
                        return false;
                    }
                }
            }

            //-------------------------------------------------------------------------

            std::cout << "  Project: " << project.m_name.c_str() << " - ";

            if ( !project.m_moduleHeaderID.IsValid() )
            {
                std::cout << "Ignored! ( Module not registered! )" << std::endl;
                continue;
            }

            if ( project.m_headerFiles.empty() )
            {
                std::cout << "Ignored! ( No headers found! )" << std::endl;
                continue;
            }

            std::cout << "Parsed! ( " << project.m_headerFiles.size() << " header(s) found! )" << std::endl;

            // Add all dirty headers to the list of file to be parsed
            bool moduleHeaderAdded = false;
            for ( ReflectedHeader& headerInfo : project.m_headerFiles )
            {
                headersToParse.push_back( &headerInfo );
            }
        }

        //-------------------------------------------------------------------------

        if ( headersToParse.empty() )
        {
            std::cout << std::endl;
            std::cout << "  ** No headers found - Nothing to do! **" << std::endl;
            return true;
        }

        // Reflect C++
        //-------------------------------------------------------------------------

        std::cout << std::endl;
        std::cout << ">> Reflecting C++ Code - First Pass (With Dev Tools)" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        ReflectionDatabase database( m_projects );
        ClangParser clangParser( m_solutionDirectoryPath, &database );
        if ( !clangParser.Parse( headersToParse, ClangParser::DevToolsPass ) )
        {
            return PrintError( clangParser.GetErrorMessage().c_str() );
        }

        Milliseconds clangParsingTime = clangParser.GetParsingTime();
        Milliseconds clangVisitingTime = clangParser.GetVisitingTime();
        std::cout << "  ** Pass Complete! ( P:" << (float) clangParsingTime << "ms, V:" << (float) clangVisitingTime << "ms ) **" << std::endl;

        //-------------------------------------------------------------------------

        std::cout << std::endl;
        std::cout << ">> Reflecting C++ Code - Second Pass (No Dev Tools)" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        // Second parse to detect dev-only types
        if ( !clangParser.Parse( headersToParse, ClangParser::NoDevToolsPass ) )
        {
            return PrintError( clangParser.GetErrorMessage().c_str() );
        }

        clangParsingTime = clangParser.GetParsingTime();
        clangVisitingTime = clangParser.GetVisitingTime();
        std::cout << "  ** Pass Complete! ( P:" << (float) clangParsingTime << "ms, V:" << (float) clangVisitingTime << "ms ) **" << std::endl;

        // Update Database
        //-------------------------------------------------------------------------

        std::cout << std::endl;
        std::cout << ">> Update Type Reflection DB" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        bool databaseValidationSuccess = false;

        Milliseconds time = 0;
        {
            ScopedTimer<PlatformClock> timer( time );
            if ( database.ValidateDataFileRegistrations() )
            {
                if ( database.ProcessAndValidateReflectedProperties() )
                {
                    databaseValidationSuccess = true;
                }
            }
        }

        // Dump log
        for ( auto const& entry : database.GetLogEntries() )
        {
            if ( entry.m_severity == Severity::Error )
            {
                PrintError( entry.m_message.c_str() );
            }
            else
            {
                PrintWarning( entry.m_message.c_str() );
            }
        }

        if ( database.HasErrors() || database.HasWarnings() )
        {
            std::cout << std::endl;
        }

        if ( !databaseValidationSuccess )
        {
            std::cout << "  ** Database Validation Failed **" << std::endl;
            return false;
        }

        database.CleanupResourceHierarchy();

        std::cout << "  ** Database Updated Success! ( " << time.ToFloat() << "ms ) **" << std::endl;

        // Generate Code
        //-------------------------------------------------------------------------

        TypeInfoCodeGenerator generator( *this, database );

        std::cout << std::endl;
        std::cout << ">> Generating Type Info Code" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        {
            ScopedTimer<PlatformClock> timer( time );
            generator.GenerateCodeForSolution();
        }

        // Dump Log
        for ( auto const& entry : generator.GetLogEntries() )
        {
            if ( entry.m_severity == Severity::Error )
            {
                PrintError( entry.m_message.c_str() );
            }
            else
            {
                PrintWarning( entry.m_message.c_str() );
            }
        }

        if ( generator.HasErrors() )
        {
            std::cout << "  ** Type Info Code Generation Failed! **" << std::endl;
            return false;
        }
        else
        {
            std::cout << "  ** Type Info Code Generation Success! ( " << time.ToFloat() << "ms ) **" << std::endl;
        }

        return true;
    }

    bool Reflector::ShaderParameterFilesWereUpdated( FileSystem::Path const& directoryPath, TVector<GeneratedFile> const& expectedFiles ) const
    {
        EE_ASSERT( directoryPath.IsValid() && directoryPath.IsDirectoryPath() );

        //-------------------------------------------------------------------------

        if ( !directoryPath.Exists() )
        {
            return true;
        }

        // Get directory contents
        TVector<FileSystem::Path> directoryContents;
        if ( !FileSystem::GetDirectoryContents( directoryPath, directoryContents ) )
        {
            return true;
        }

        // Compare list of existing files with expected files and delete any files that shouldn't exist
        //-------------------------------------------------------------------------

        for ( FileSystem::Path const& existingFile : directoryContents )
        {
            if ( !VectorContains( expectedFiles, existingFile, [] ( GeneratedFile const& lhs, FileSystem::Path const& rhs ) { return lhs.m_path == rhs; } ) )
            {
                // If this was a parameters file, then we need to re-run the type reflection
                if ( IsShaderParametersFilename( existingFile ) )
                {
                    return true;
                }
            }
        }

        // Check the generated files for differences
        //-------------------------------------------------------------------------

        for ( GeneratedFile const& generatedFile : expectedFiles )
        {
            if ( IsShaderParametersFilename( generatedFile.m_path ) )
            {
                if ( !generatedFile.m_path.Exists() )
                {
                    return true;
                }

                if ( DoTextFileContentsDiffer( generatedFile.m_path, generatedFile.m_contents ) )
                {
                    return true;
                }
            }
        }

        return false;
    }

    bool Reflector::UpdateAutogeneratedDirectory( FileSystem::Path const& directoryPath, TVector<GeneratedFile> const& expectedFiles, bool& wereFilesAddedOrRemoved ) const
    {
        EE_ASSERT( directoryPath.IsValid() && directoryPath.IsDirectoryPath() );

        wereFilesAddedOrRemoved = false;

        //-------------------------------------------------------------------------

        if ( !directoryPath.EnsureDirectoryExists() )
        {
            return PrintError( "Failed to ensure that directory exists: %s", directoryPath.c_str() );
        }

        // Get directory contents
        TVector<FileSystem::Path> directoryContents;
        if ( !FileSystem::GetDirectoryContents( directoryPath, directoryContents ) )
        {
            return PrintError( "Failed to get directory contents: %s", directoryPath.c_str() );
        }

        // There should be no directories inside the auto-generated folders
        for ( int32_t i = int32_t( directoryContents.size() ) - 1; i >= 0; i-- )
        {
            if ( directoryContents[i].IsDirectoryPath() )
            {
                if ( !FileSystem::EraseDir( directoryContents[i] ) )
                {
                    return PrintError( " * Error erasing directory: %s", directoryContents[i].c_str() );
                }

                directoryContents.erase_unsorted( directoryContents.begin() + i );
            }
        }

        // Compare list of existing files with expected files and delete any files that shouldn't exist
        //-------------------------------------------------------------------------

        for ( FileSystem::Path const& existingFile : directoryContents )
        {
            if ( !VectorContains( expectedFiles, existingFile, [] ( GeneratedFile const& lhs, FileSystem::Path const& rhs ) { return lhs.m_path == rhs; } ) )
            {
                wereFilesAddedOrRemoved = true;

                if ( !FileSystem::EraseFile( existingFile ) )
                {
                    return PrintError( " * Error erasing file: %s", existingFile.c_str() );
                }
            }
        }

        // Write out any files that have actually changed
        //-------------------------------------------------------------------------

        for ( GeneratedFile const& generatedFile : expectedFiles )
        {
            if ( !generatedFile.m_path.Exists() )
            {
                wereFilesAddedOrRemoved = true;
            }

            if ( !FileSystem::UpdateTextFile( generatedFile.m_path, generatedFile.m_contents ) )
            {
                return PrintError( " * Error creating generated file: %s", generatedFile.m_path.c_str() );
            }
        }

        return true;
    }

    bool Reflector::WriteGeneratedFiles( Output desiredOutput )
    {
        EE_ASSERT( desiredOutput != Output::ShadersAndTypeInfo );

        auto WritingError = [] ()
        {
            std::cout << "  ** Writing Failed! **" << std::endl;
            return false;
        };

        //-------------------------------------------------------------------------

        Milliseconds fileWriteTime = 0;

        std::cout << std::endl;
        std::cout << ">> Writing Generated Files (" << GetStringForOutput( desiredOutput ) << ")" << std::endl;
        std::cout << "-----------------------------------------------------" << std::endl << std::endl;

        {
            ScopedTimer<PlatformClock> codeGenTimer( fileWriteTime );

            // Delete all auto-generated directories for excluded projects (just to be safe)
            //-------------------------------------------------------------------------

            for ( auto& project : m_projects )
            {
                if ( !project.IsRelevantForReflection() )
                {
                    if ( !CleanDirectory( project.m_autogeneratedDirectoryPath, false ) )
                    {
                        return WritingError();
                    }
                }
            }

            // Get list of files in all known auto-generated directories
            //-------------------------------------------------------------------------

            for ( ReflectedProject& prj : m_projects )
            {
                if ( IsShaderOutputRequired( desiredOutput ) )
                {
                    bool wereFilesAddedOrRemoved = false;
                    if ( !UpdateAutogeneratedDirectory( prj.m_autogeneratedShaderDirectoryPath, prj.m_generatedShaderFiles, wereFilesAddedOrRemoved ) )
                    {
                        return WritingError();
                    }

                    prj.m_requiresReload |= wereFilesAddedOrRemoved;
                }

                if ( IsTypeInfoOutputRequired( desiredOutput ) )
                {
                    bool wereFilesAddedOrRemoved = false;
                    if ( !UpdateAutogeneratedDirectory( prj.m_autogeneratedTypeInfoDirectoryPath, prj.m_generatedTypeInfoFiles, wereFilesAddedOrRemoved ) )
                    {
                        return WritingError();
                    }

                    prj.m_requiresReload |= wereFilesAddedOrRemoved;
                }
            }

            // Write misc files out
            //-------------------------------------------------------------------------

            for ( auto const& generatedFile : m_miscGeneratedFiles )
            {
                if ( !FileSystem::UpdateTextFile( generatedFile.m_path, generatedFile.m_contents ) )
                {
                    return WritingError();
                }
            }
        }

        //-------------------------------------------------------------------------

        std::cout << "  ** Writing of Generated Files Complete! ( " << (float) fileWriteTime << "ms ) **" << std::endl;
        return true;
    }

    //-------------------------------------------------------------------------
    // Code Generation
    //-------------------------------------------------------------------------

    void Reflector::AddGeneratedFile( FileSystem::Path const& path, char const* pFileContents )
    {
        for ( auto& project : m_projects )
        {
            if ( path.IsUnderDirectory( project.m_autogeneratedShaderDirectoryPath ) )
            {
                GeneratedFile& file = project.m_generatedShaderFiles.emplace_back();
                file.m_contents = pFileContents;
                file.m_path = path;
                return;
            }

            if ( path.IsUnderDirectory( project.m_autogeneratedTypeInfoDirectoryPath ) )
            {
                GeneratedFile& file = project.m_generatedTypeInfoFiles.emplace_back();
                file.m_contents = pFileContents;
                file.m_path = path;
                return;
            }
        }

        GeneratedFile& file = m_miscGeneratedFiles.emplace_back();
        file.m_contents = pFileContents;
        file.m_path = path;
    }
}