#pragma once
#include "ReflectedHeader.h"
#include "ReflectorSettings.h"
#include "ReflectedShader.h"

//-------------------------------------------------------------------------

namespace EE::Reflection
{
    class ReflectedProject
    {
    public:

        inline static StringID GetProjectID( FileSystem::Path const& projectFilePath )
        {
            String lowercasePath = projectFilePath.GetString();
            lowercasePath.make_lower();
            return StringID( lowercasePath.c_str() );
        }

    public:

        ReflectedProject() = default;

        inline bool IsBaseModule() const { return m_isBaseProject; }
        inline bool IsRelevantForReflection() const { return !m_isExcludedFromShaderReflection || !m_isExcludedFromTypeInfoReflection; }

        ReflectedHeader const* GetModuleHeader() const;

        // Type Info
        //-------------------------------------------------------------------------

        // Get the module's type-info registration header file path
        inline FileSystem::Path const GetTypeInfoHeaderFilePath() const { return GetTypeInfoSourceFilePath( true ); }

        // Get the module's type-info registration source file path
        inline FileSystem::Path const GetTypeInfoSourceFilePath() const { return GetTypeInfoSourceFilePath( false ); }

    private:

        inline FileSystem::Path const GetTypeInfoSourceFilePath( bool isHeader ) const
        {
            FileSystem::Path const directoryPath = m_autogeneratedTypeInfoDirectoryPath;
            ReflectedHeader const* pModuleHeader = GetModuleHeader();
            InlineString const filenameStr( InlineString::CtorSprintf(), "%s.%s.%s", pModuleHeader->m_path.GetFilenameWithoutExtension().c_str(), Settings::g_typeinfoFileSuffix, isHeader ? "h" : "cpp" );
            return directoryPath.GetAppended( filenameStr.c_str() );
        }

    public:

        StringID                                        m_ID;
        String                                          m_name;
        FileSystem::Path                                m_path;
        FileSystem::Path                                m_directoryPath;
        FileSystem::Path                                m_autogeneratedDirectoryPath;
        FileSystem::Path                                m_autogeneratedTypeInfoDirectoryPath;
        FileSystem::Path                                m_autogeneratedShaderDirectoryPath;
        FileSystem::Path                                m_autogeneratedShaderReflectionDirectoryPath;
        String                                          m_exportMacro;
        uint32_t                                        m_dependencyCount = 0;
        TVector<StringID>                               m_dependencies;

        StringID                                        m_moduleHeaderID;
        TVector<ReflectedHeader>                        m_headerFiles;
        mutable String                                  m_moduleClassName;
        bool                                            m_includeInAutogenerateModuleRegistrationList = true;

        TVector<ReflectedShader>                        m_shaders;

        TVector<GeneratedFile>                          m_generatedShaderFiles;
        TVector<GeneratedFile>                          m_generatedTypeInfoFiles;

        bool                                            m_isBaseProject = false;
        bool                                            m_isToolsProject = false;
        bool                                            m_isExcludedFromShaderReflection = true;
        bool                                            m_isExcludedFromTypeInfoReflection = true;
        bool                                            m_requiresReload = false; // Do we need to bump this project so that the IDE reloads it
    };
}