#include "EngineTools/_Module/_AutoGenerated/TypeInfo/TypeRegistration.h"
#include "Base/TypeSystem/TypeRegistry.h"
#include "Base/Application/ApplicationGlobalState.h"
#include "Base/Serialization/TypeSerialization.h"
#include "Base/FileSystem/FileSystemUtils.h"
#include "EngineTools/Resource/ResourceDescriptor.h"
#include "Base/FileSystem/DataPath.h"
#include "Base/TypeSystem/TypeInstance.h"
#include "EngineTools/Core/Test/Component_SerializationTest.h"
#include "EngineTools/Entity/EntitySerializationTools.h"

#include <iostream>

//-------------------------------------------------------------------------

using namespace EE;

//-------------------------------------------------------------------------

int main( int argc, char *argv[] )
{
    {
        EE::ApplicationGlobalState State;
        TypeSystem::TypeRegistry typeRegistry;
        TypeSystem::Reflection::RegisterTypes( typeRegistry );

        //-------------------------------------------------------------------------

        //-------------------------------------------------------------------------

        TypeSystem::Reflection::UnregisterTypes( typeRegistry );
    }

    return 0;
}