#include "ResourceCompilerApplication.h"
#include "EngineTools/_Module/_AutoGenerated/TypeInfo/TypeRegistration.h"
#include "EngineTools/Resource/ResourceCompilerRegistry.h"
#include "Base/Application/ApplicationGlobalState.h"
#include "Base/Utils/CommandLineParser.h"
#include "Base/Network/Clients/NetworkClient_WebSockets.h"
#include "Base/Network/NetworkSystem.h"
#include "Base/Resource/Settings/Settings_Resource.h"
#include "Base/FileSystem/FileSystemUtils.h"
#include <iostream>

//-------------------------------------------------------------------------
// Application Entry Point
//-------------------------------------------------------------------------

namespace EE::Resource
{
    struct CommandLine
    {
        CommandLine( int argc, char* argv[] )
        {
            CommandLineParser cl;
            cl.AddOptionalStringArg( "compile", "Compile resource" );
            cl.AddOptionalBoolArg( "force", "Force compilation", false );
            cl.AddOptionalBoolArg( "package", "Compile resource for packaged build.", false );
            cl.AddOptionalIntArg( "worker", "worker ID", 0 );

            if ( cl.Parse( argc, argv ) )
            {
                if ( cl.HasIntArg( "worker" ) )
                {
                    m_uniqueID = cl.GetIntArg( "worker" );
                    m_isValid = m_uniqueID != 0;
                    m_isStandaloneCompile = false;
                }
                else
                {
                    m_isStandaloneCompile = true;
                    m_isForcedCompilation = cl.GetBoolArg( "force" );
                    m_isForPackagedBuild = cl.GetBoolArg( "package" );

                    // Get compile argument
                    String rawDataPath = cl.GetStringArg( "compile" ).c_str();
                    if ( DataPath::IsValidPath( rawDataPath ) )
                    {
                        DataPath const resourcePath( rawDataPath );
                        if ( resourcePath.IsValid() )
                        {
                            m_resourceID = ResourceID( resourcePath );

                            if ( m_resourceID.IsValid() )
                            {
                                m_isValid = true;
                            }
                            else
                            {
                                EE_LOG_ERROR( LogCategory::Resource, "Resource Compiler", "Invalid compile request: %s\n", m_resourceID.c_str() );
                            }

                            return;
                        }
                    }
                }
            }
        }

        bool IsValid() const { return m_isValid; }

    public:

        ResourceID          m_resourceID;
        bool                m_isForPackagedBuild = false;
        bool                m_isForcedCompilation = false;
        bool                m_isStandaloneCompile = true;
        int64_t             m_uniqueID = 0;
        bool                m_isValid = false;
    };
}

int main( int argc, char* argv[] )
{
    EE::ApplicationGlobalState State;

    // Read CMD line arguments and process request
    //-------------------------------------------------------------------------

    EE::Resource::CommandLine argParser( argc, argv );

    if ( !argParser.IsValid() )
    {
        for ( int i = 0; i < argc; i++ )
        {
            std::cout << argv[i] << std::endl;
        }

        EE_LOG_ERROR( EE::LogCategory::Resource, "Resource Compiler", "Invalid command line arguments" );
        return -1;
    }

    // Run Application
    //-------------------------------------------------------------------------

    int32_t result = 0;
    EE::Resource::ResourceCompilerApplication application;
    if ( application.Initialize( argParser, EE::FileSystem::GetCurrentProcessPath().Append( "Esoterica.ini" ) ) )
    {
        result = application.Run();
    }
    application.Shutdown();

    return result;
}

//-------------------------------------------------------------------------
// Resource Compiler
//-------------------------------------------------------------------------

namespace EE::Resource
{
    ResourceCompilerApplication::ResourceCompilerApplication()
        : m_settingsRegistry( m_typeRegistry )
    {}

    ResourceCompilerApplication::~ResourceCompilerApplication()
    {
        EE_ASSERT( m_pCompilerRegistry == nullptr );
        EE_ASSERT( m_pSettings == nullptr );
    }

    bool ResourceCompilerApplication::Initialize( CommandLine& cmdLine, FileSystem::Path const& iniFilePath )
    {
        EE_ASSERT( cmdLine.IsValid() );

        // Register Types
        //-------------------------------------------------------------------------

        TypeSystem::Reflection::RegisterTypes( m_typeRegistry );

        // Initialize Settings
        //-------------------------------------------------------------------------

        if ( !m_settingsRegistry.Initialize( iniFilePath ) )
        {
            return false;
        }

        m_pSettings = m_settingsRegistry.GetSettings<Resource::ResourceSettings>();
        EE_ASSERT( m_pSettings != nullptr );

        // Connect database
        //-------------------------------------------------------------------------

        if ( !m_compiledResourceDB.Connect( m_pSettings->m_compiledResourceDatabasePath ) )
        {
            EE_LOG_ERROR( LogCategory::Resource, "Resource Compiler", "Database connection error: %s", m_compiledResourceDB.GetError().c_str() );
            return false;
        }

        // Create compiler registry
        //-------------------------------------------------------------------------

        m_pCompilerRegistry = EE::New<CompilerRegistry>( m_typeRegistry, m_pSettings->m_sourceDataDirectoryPath );

        // Setup compiler and arguments
        //-------------------------------------------------------------------------

        m_isStandaloneCompile = cmdLine.m_isStandaloneCompile;

        if ( m_isStandaloneCompile )
        {
            std::cout << Resource::Compiler::s_logDelimiter;

            m_resourceToCompile = cmdLine.m_resourceID;
            m_isForPackagedBuild = cmdLine.m_isForPackagedBuild;
            m_forceCompilation = cmdLine.m_isForcedCompilation;
        }

        // Start Network Server
        //-------------------------------------------------------------------------

        else // Worker Mode
        {
            m_uniqueID = cmdLine.m_uniqueID;
            EE_ASSERT( m_uniqueID != 0 );

            m_taskSystem.Initialize();

            Network::NetworkSystem::Initialize();
            m_networkClient.Start( m_pSettings->m_resourceServerNetworkAddress.c_str(), m_pSettings->m_resourceServerPort );

            m_IDTimer.Start( 0.0f );
        }

        return true;
    }

    void ResourceCompilerApplication::Shutdown()
    {
        if ( !m_isStandaloneCompile )
        {
            m_taskSystem.WaitForAll();
            m_taskSystem.Shutdown();

            m_networkClient.Stop();
            Network::NetworkSystem::Shutdown();
        }

        //-------------------------------------------------------------------------

        EE::Delete( m_pCompilerRegistry );

        if ( m_compiledResourceDB.IsConnected() )
        {
            m_compiledResourceDB.Disconnect();
        }

        m_pSettings = nullptr;
        m_settingsRegistry.Shutdown();

        TypeSystem::Reflection::UnregisterTypes( m_typeRegistry );
    }

    int32_t ResourceCompilerApplication::Run()
    {
        if ( m_isStandaloneCompile )
        {
            return (int32_t) RunStandaloneCompile();
        }
        else
        {
            return RunWorker() ? 0 : 1;
        }
    }

    //-------------------------------------------------------------------------
    // STANDALONE
    //-------------------------------------------------------------------------

    CompilationResult ResourceCompilerApplication::RunStandaloneCompile()
    {
        auto pCompiler = m_pCompilerRegistry->GetCompilerForResourceType( m_resourceToCompile.GetResourceTypeID() );
        if ( pCompiler == nullptr )
        {
            EE_LOG_ERROR( LogCategory::Resource, "Resource Compiler", "Failed to find a compiler for this resource type: %s", m_resourceToCompile.GetResourceTypeID().ToString().c_str() );
            return CompilationResult::Failure;
        }

        //-------------------------------------------------------------------------

        CompileContext compileContext
        (
            m_resourceToCompile,
            m_typeRegistry,
            m_compiledResourceDB,
            *m_pCompilerRegistry,
            m_pSettings->m_sourceDataDirectoryPath,
            m_isForPackagedBuild ? m_pSettings->m_packagedBuildCompiledResourceDirectoryPath : m_pSettings->m_compiledResourceDirectoryPath,
            Platform::Target::PC,
            m_isForPackagedBuild
        );

        compileContext.m_forceCompilation = m_forceCompilation;
        compileContext.m_isStandaloneCompile = true;

        pCompiler->PerformUpToDateCheck( compileContext );
        if ( compileContext.m_result == CompilationResult::Failure )
        {
            return compileContext.m_result;
        }

        if ( compileContext.m_requiresCompilation )
        {
            pCompiler->CompileResource( compileContext );
        }

        return compileContext.m_result;
    }

    //-------------------------------------------------------------------------
    // WORKER MODE
    //-------------------------------------------------------------------------

    void ResourceCompilerApplication::HandleNetworkMessage( Network::Message const& message )
    {
        switch ( (NetworkResourceWorkerMessageID) message.GetMessageID() )
        {
            case NetworkResourceWorkerMessageID::CompileResource:
            {
                NetworkResourceCompilerRequest networkRequestMessage = message.GetPayload<NetworkResourceCompilerRequest>();
                for ( NetworkResourceCompilerRequest::Request const& networkRequest : networkRequestMessage.m_requests )
                {
                    auto pNewRequest = m_requests.emplace_back( EE::New<Request>
                    (
                        networkRequest.m_resourceID,
                        m_typeRegistry,
                        m_compiledResourceDB,
                        *m_pCompilerRegistry,
                        m_pSettings->m_sourceDataDirectoryPath,
                        networkRequest.m_isForPackagedBuild ? m_pSettings->m_packagedBuildCompiledResourceDirectoryPath : m_pSettings->m_compiledResourceDirectoryPath,
                        Platform::Target::PC,
                        networkRequest.m_isForPackagedBuild
                    ) );

                    EE_ASSERT( networkRequest.m_taskID.IsValid() );

                    pNewRequest->m_forceCompilation = networkRequest.m_forceCompilation;
                    pNewRequest->m_sourceTaskID = networkRequest.m_taskID;
                    pNewRequest->m_heartbeatTimer.Start( 0.0f );

                    // Check compiler
                    auto pCompiler = pNewRequest->TryGetCompiler();
                    if ( pCompiler != nullptr )
                    {
                        m_upToDateCheckQueue.emplace_back( pNewRequest );
                    }
                    else
                    {
                        pNewRequest->LogError( "Failed to find a compiler for this resource type: %s", pNewRequest->m_resourceID.GetResourceTypeID().ToString().c_str() );
                        pNewRequest->m_result = CompilationResult::Failure;
                        m_completedQueue.enqueue( pNewRequest );
                        continue;
                    }
                }
            }
            break;

            default:
            break;
        };
    }

    void ResourceCompilerApplication::AsyncCompileTask::Execute()
    {
        Request* pRequest = nullptr;
        while ( m_pApp->m_compileQueue.try_dequeue( pRequest ) )
        {
            EE_ASSERT( pRequest->m_requiresCompilation );
            auto pCompiler = pRequest->TryGetCompiler();
            EE_ASSERT( pCompiler != nullptr );
            pCompiler->CompileResource( *pRequest );

            // Add to completed queue
            m_pApp->m_completedQueue.enqueue( pRequest );
        }
    }

    bool ResourceCompilerApplication::RunWorker()
    {
        while ( true )
        {
            // Update network
            //-------------------------------------------------------------------------

            m_networkClient.Update( [this] ( Network::Message const& message ) { HandleNetworkMessage( message ); } );

            if ( m_networkClient.IsDisconnected() || m_networkClient.HasConnectionFailed() )
            {
                return false;
            }

            if ( m_networkClient.IsConnecting() )
            {
                Threading::Sleep( 1 );
                continue;
            }

            // Send ID
            //-------------------------------------------------------------------------

            if ( m_IDTimer.Update() )
            {
                m_networkClient.SendNetworkMessage( Network::Message( (int32_t) NetworkResourceWorkerMessageID::ID, NetworkResourceCompilerID( m_uniqueID ) ) );
                m_networkClient.SendOutgoingMessages();
                m_IDTimer.Start( s_identificationResendCooldownSeconds );
            }

            // Process any new requests sequentially
            //-------------------------------------------------------------------------

            Milliseconds const upToDateProcessStartTime = PlatformClock::GetTimeInMilliseconds();

            for ( int32_t i = 0; i < m_upToDateCheckQueue.size(); i++ )
            {
                // Run check
                Request* pRequest = m_upToDateCheckQueue[i];
                auto pCompiler = pRequest->TryGetCompiler();
                EE_ASSERT( pCompiler != nullptr );

                pCompiler->PerformUpToDateCheck( *pRequest );

                if ( pRequest->m_requiresCompilation )
                {
                    m_compileQueue.enqueue( pRequest );
                }
                else
                {
                    m_completedQueue.enqueue( pRequest );
                }

                // Remove from queue
                m_upToDateCheckQueue.erase( m_upToDateCheckQueue.begin() + i );
                i--;

                // Check time spent
                Milliseconds const elapsedTime = PlatformClock::GetTimeInMilliseconds() - upToDateProcessStartTime;
                if ( elapsedTime.ToFloat() > s_maxUpToDateLoopProcessingTimeMilliseconds )
                {
                    break;
                }
            }

            // Process completed requests
            //-------------------------------------------------------------------------

            Milliseconds const completionProcessStartTime = PlatformClock::GetTimeInMilliseconds();

            Request* pCompletedRequest = nullptr;
            while ( m_completedQueue.try_dequeue( pCompletedRequest ) )
            {
                // Ensure that the output has actually been writing for successful compilations
                if ( pCompletedRequest->m_result != CompilationResult::Failure )
                {
                    EE_ASSERT( FileSystem::Exists( pCompletedRequest->GetOutputPath() ) );
                }

                NetworkResourceCompilerResponse::Result& result = m_responseMessageData.m_results.emplace_back();

                result.m_taskID = pCompletedRequest->m_sourceTaskID;
                result.m_resourceID = pCompletedRequest->m_resourceID;
                result.m_upToDateCheckTimeMS = ( pCompletedRequest->m_createDependencyTreeTime + pCompletedRequest->m_upToDateCheckTime ).ToFloat();
                result.m_compilationTimeMS = pCompletedRequest->m_compilationTime.ToFloat();
                result.m_compilationResult = pCompletedRequest->m_result;

                result.m_log.append( Compiler::s_logDelimiter );
                pCompletedRequest->m_log.SaveLogToString( result.m_log );

                m_requests.erase_first( pCompletedRequest ); 
                EE::Delete( pCompletedRequest );

                // Check time spent
                Milliseconds const elapsedTime = PlatformClock::GetTimeInMilliseconds() - completionProcessStartTime;
                if ( elapsedTime.ToFloat() > s_maxCompletionLoopProcessingTimeMilliseconds )
                {
                    break;
                }
            }

            if ( !m_responseMessageData.m_results.empty() )
            {
                Network::Message completionMessage( (int32_t) NetworkResourceWorkerMessageID::CompileRequestComplete, m_responseMessageData );
                m_networkClient.SendNetworkMessage( eastl::move( completionMessage ) );
                m_responseMessageData.Clear();
            }

            // Send request heartbeats
            //-------------------------------------------------------------------------

            for ( Request* pRequest : m_requests )
            {
                if ( pRequest->m_heartbeatTimer.Update() )
                {
                    m_requestHeartbeatsMessageData.m_requests.emplace_back( pRequest->m_resourceID, pRequest->m_sourceTaskID );
                    pRequest->m_heartbeatTimer.Start( s_heartbeatSendIntervalSeconds );
                }
            }

            if ( !m_requestHeartbeatsMessageData.m_requests.empty() )
            {
                Network::Message acknowledgeMessage( (int32_t) NetworkResourceWorkerMessageID::CompileRequestHeartbeat, m_requestHeartbeatsMessageData );
                m_networkClient.SendNetworkMessage( eastl::move( acknowledgeMessage ) );
                m_requestHeartbeatsMessageData.Clear();
            }

            m_networkClient.SendOutgoingMessages();

            // Kick off compilation job
            //-------------------------------------------------------------------------

            if ( m_asyncCompileTask.GetIsComplete() && m_compileQueue.size_approx() > 0 )
            {
                m_taskSystem.ScheduleTask( &m_asyncCompileTask );
            }

            if ( m_asyncCompileTask.GetIsComplete() && m_upToDateCheckQueue.empty() )
            {
                Threading::Sleep( 1 );
            }
        }
    }
}