#include "RenderSystem.h"
#include "Engine/Render/RenderViewport.h"
#include "Engine/Render/RenderGeometry.h"
#include "Engine/_Module/_AutoGenerated/Shaders/ShaderRegistration.h"
#include "Base/Threading/Threading.h"
#include "Base/Render/RHI.h"
#include "Base/Render/RenderWindow.h"
#include "Base/Render/Settings/Settings_Render.h"
#include "Base/Profiling.h"

#include "EASTL/sort.h"

#include "Engine/Render/Shaders/MeshData.esh"
#include "Engine/Render/Shaders/CommonSamplers.esh"

//-------------------------------------------------------------------------

namespace EE::Render
{
    //-------------------------------------------------------------------------------------------------------

    void RenderSystem::Initialize( RenderSettings const& settings )
    {
        RHI::ContextParameters contextParameters = {};
        contextParameters.m_pApplicationName = "EsotericaGame";
        contextParameters.m_pEngineName = "EsotericaEngine";
        contextParameters.m_enableHostValidation = settings.m_enableHostValidation;
        contextParameters.m_enableDeviceValidation = settings.m_enableDeviceValidation;
        contextParameters.m_enableDeviceBreadcrumbs = settings.m_enableDeviceBreadcrumbs;
        contextParameters.m_enableRenderDoc = settings.m_enableRenderDoc;
        contextParameters.m_enablePix = settings.m_enablePix;
        contextParameters.m_enableAmdAgs = settings.m_enableAmdAgs;

        #ifdef EE_DEBUG
        // Always enable host validation in debug, there is no downside for that.
        contextParameters.m_enableHostValidation = true;
        #endif

        if ( settings.m_deviceIndex >= 0 )
        {
            contextParameters.m_deviceIndex = settings.m_deviceIndex;
            contextParameters.m_deviceSelection = RHI::DeviceSelectionPreference::UseProvidedIndex;
        }

        m_pContextRHI = RHI::CreateContext( contextParameters );

        RHI::QueueParameters graphicsQueueParameters = {};
        graphicsQueueParameters.m_queueType = RHI::QueueType::Graphics;
        graphicsQueueParameters.m_debugName = "GraphicsQueue";

        m_pGraphicsQueue = RHI::CreateQueue( m_pContextRHI, graphicsQueueParameters );

        RHI::QueueParameters computeQueueParameters = {};
        computeQueueParameters.m_queueType = RHI::QueueType::Compute;
        computeQueueParameters.m_debugName = "AsyncComputeQueue";

        m_pComputeQueue = RHI::CreateQueue( m_pContextRHI, computeQueueParameters );

        RHI::QueueParameters transferQueueParameters = {};
        transferQueueParameters.m_queueType = RHI::QueueType::Transfer;
        transferQueueParameters.m_debugName = "AsyncTransferQueue";

        m_pTransferQueue = RHI::CreateQueue( m_pContextRHI, transferQueueParameters );

        // Staging buffer and allocator
        //---------------------------------------------------------------------------------------------------

        uint64_t stagingAllocatorSize = Math::RoundUpToNearestMultiple32( settings.m_stagingBufferSize, StagingBufferAlignment );

        RHI::BufferParameters stagingBufferParameters = {};
        stagingBufferParameters.m_bufferSize = stagingAllocatorSize;
        stagingBufferParameters.m_memoryType = RHI::ResourceMemoryType::HostToDevice;
        stagingBufferParameters.m_nodeIndex = m_pTransferQueue->m_nodeIndex;
        stagingBufferParameters.m_queueType = RHI::QueueType::Transfer;
        stagingBufferParameters.m_flags.SetMultipleFlags( RHI::BufferFlags::NoDescriptors, RHI::BufferFlags::PersistentMap, RHI::BufferFlags::SubAllocations );
        stagingBufferParameters.m_debugName = "StagingBuffer";

        m_pStagingBuffer = RHI::CreateBuffer( m_pContextRHI, stagingBufferParameters );

        // Shaders
        //---------------------------------------------------------------------------------------------------

        InitializeShaders();

        // Command buffers
        //---------------------------------------------------------------------------------------------------

        for ( uint32_t frameIndex = 0; frameIndex < RHI::MaxPendingFrames; ++frameIndex )
        {
            RHI::CommandPoolParameters commandPoolParameters = {};
            commandPoolParameters.m_pQueue = m_pGraphicsQueue;
            commandPoolParameters.m_debugName.sprintf( "RenderSystem Common Command Pool %i", frameIndex );

            m_frameCommandPools[frameIndex] = RHI::CreateCommandPool( m_pContextRHI, commandPoolParameters );

            RHI::CommandBufferParameters commandBufferParameters = {};
            commandBufferParameters.m_pCommandPool = m_frameCommandPools[frameIndex];
            commandBufferParameters.m_debugName.sprintf( "RenderSystem Common Command Buffer %i", frameIndex );

            m_frameCommandBuffers[frameIndex] = RHI::CreateCommandBuffer( m_pContextRHI, commandBufferParameters );
        }

        for ( uint32_t asyncTransferIndex = 0; asyncTransferIndex < MaxPendingTransfers; ++asyncTransferIndex )
        {
            RHI::CommandPoolParameters commandPoolParameters = {};
            commandPoolParameters.m_pQueue = m_pTransferQueue;
            commandPoolParameters.m_debugName.sprintf( "RenderSystem Transfer Command Pool %i", asyncTransferIndex );

            m_asyncTransferCommandPools[asyncTransferIndex] = RHI::CreateCommandPool( m_pContextRHI, commandPoolParameters );

            RHI::CommandBufferParameters commandBufferParameters = {};
            commandBufferParameters.m_pCommandPool = m_asyncTransferCommandPools[asyncTransferIndex];
            commandBufferParameters.m_debugName.sprintf( "RenderSystem Transfer Command Buffer %i", asyncTransferIndex );

            m_asyncTransferCommandBuffers[asyncTransferIndex] = RHI::CreateCommandBuffer( m_pContextRHI, commandBufferParameters );
        }

        // Common samplers
        //---------------------------------------------------------------------------------------------------

        RHI::SamplerParameters samplerParameters = {};

        m_commonSamplers[COMMON_SAMPLER_POINT_WRAP] = RHI::CreateSampler( m_pContextRHI, samplerParameters );

        samplerParameters.m_minFilter = RHI::FilterType::Linear;
        samplerParameters.m_magFilter = RHI::FilterType::Linear;

        m_commonSamplers[COMMON_SAMPLER_LINEAR_WRAP] = RHI::CreateSampler( m_pContextRHI, samplerParameters );

        samplerParameters.m_addressModeU = RHI::AddressMode::ClampToEdge;
        samplerParameters.m_addressModeV = RHI::AddressMode::ClampToEdge;
        samplerParameters.m_addressModeW = RHI::AddressMode::ClampToEdge;

        samplerParameters.m_minFilter = RHI::FilterType::Point;
        samplerParameters.m_magFilter = RHI::FilterType::Point;

        m_commonSamplers[COMMON_SAMPLER_POINT_CLAMP] = RHI::CreateSampler( m_pContextRHI, samplerParameters );

        samplerParameters.m_minFilter = RHI::FilterType::Linear;
        samplerParameters.m_magFilter = RHI::FilterType::Linear;

        m_commonSamplers[COMMON_SAMPLER_LINEAR_CLAMP] = RHI::CreateSampler( m_pContextRHI, samplerParameters );

        samplerParameters.m_filterMode = RHI::FilterMode::Compare;
        samplerParameters.m_compareMode = RHI::CompareMode::GreaterEqual;

        m_commonSamplers[COMMON_SAMPLER_LINEAR_CLAMP_COMPARE] = RHI::CreateSampler( m_pContextRHI, samplerParameters );

        samplerParameters.m_minFilter = RHI::FilterType::Linear;
        samplerParameters.m_magFilter = RHI::FilterType::Linear;
        samplerParameters.m_filterMode = RHI::FilterMode::Max;
        samplerParameters.m_compareMode = RHI::CompareMode::Never;

        m_commonSamplers[COMMON_SAMPLER_LINEAR_CLAMP_MAX] = RHI::CreateSampler( m_pContextRHI, samplerParameters );

        // Ensure all samplers are initialized
        for ( RHI::Sampler* sampler : m_commonSamplers )
        {
            EE_ASSERT( sampler );
        }

        // Shaders
        //---------------------------------------------------------------------------------------------------

        m_shaderDataAllocator.Initialize( 1 );

        // Pre-allocate shader data buffer
        RHI::BufferParameters shaderDataBufferParameters = {};
        shaderDataBufferParameters.m_bufferSize = m_shaderDataAllocator.GetCapacityInBytes();
        shaderDataBufferParameters.m_descriptorTypes.SetMultipleFlags( RHI::DescriptorTypeFlags::Buffer, RHI::DescriptorTypeFlags::Raw );
        shaderDataBufferParameters.m_debugName = "System_Renderer ShaderDataBuffer";

        m_pShaderDataBuffer = RHI::CreateBuffer( m_pContextRHI, shaderDataBufferParameters );

        // Meshes
        //---------------------------------------------------------------------------------------------------

        m_meshAllocator.Initialize( 1 );

        RHI::BufferParameters meshBufferParameters = {};
        meshBufferParameters.m_bufferSize = m_meshAllocator.GetCapacityInBytes();
        meshBufferParameters.m_bufferStride = sizeof( ShaderTypes::Mesh );
        meshBufferParameters.m_debugName = "System_Renderer MeshBuffer";

        m_pMeshBuffer = RHI::CreateBuffer( m_pContextRHI, meshBufferParameters );

        m_meshClusterAllocator.Initialize( 1 );

        RHI::BufferParameters clusterBufferParameters = {};
        clusterBufferParameters.m_bufferSize = m_meshClusterAllocator.GetCapacityInBytes();
        clusterBufferParameters.m_bufferStride = sizeof( ShaderTypes::MeshCluster );
        clusterBufferParameters.m_debugName = "System_Renderer ClusterBuffer";

        m_pMeshClusterBuffer = RHI::CreateBuffer( m_pContextRHI, clusterBufferParameters );
    }

    void RenderSystem::Shutdown()
    {
        EE_ASSERT( m_registeredRenderWindows.empty() );
        EE_ASSERT( m_renderViewports.empty() );

        for ( uint32_t frameIndex = 0; frameIndex < RHI::MaxPendingFrames; ++frameIndex )
        {
            RHI::DestroyCommandPool( m_pContextRHI, eastl::move( m_frameCommandPools[frameIndex] ) );
            RHI::DestroyCommandBuffer( m_pContextRHI, eastl::move( m_frameCommandBuffers[frameIndex] ) );
        }

        for ( uint32_t asyncTransferIndex = 0; asyncTransferIndex < MaxPendingTransfers; ++asyncTransferIndex )
        {
            RHI::DestroyCommandPool( m_pContextRHI, eastl::move( m_asyncTransferCommandPools[asyncTransferIndex] ) );
            RHI::DestroyCommandBuffer( m_pContextRHI, eastl::move( m_asyncTransferCommandBuffers[asyncTransferIndex] ) );
        }

        for ( auto& bufferDelete : m_resourceDeleteQueue_Buffer )
        {
            RHI::DestroyBuffer( m_pContextRHI, eastl::move( bufferDelete.first ) );
        }
        m_resourceDeleteQueue_Buffer.clear();

        for ( auto& textureDelete : m_resourceDeleteQueue_Texture )
        {
            RHI::DestroyTexture( m_pContextRHI, eastl::move( textureDelete.first ) );
        }
        m_resourceDeleteQueue_Texture.clear();

        for ( auto& meshDelete : m_resourceDeleteQueue_Mesh )
        {
            DeleteMesh( eastl::move( meshDelete.first.first ), eastl::move( meshDelete.first.second ) );
        }
        m_resourceDeleteQueue_Mesh.clear();

        for ( auto& shaderDataDelete : m_resourceDeleteQueue_ShaderData )
        {
            DeleteShaderData( eastl::move( shaderDataDelete.first ) );
        }
        m_resourceDeleteQueue_ShaderData.clear();

        for ( auto& materialParameterInstanceDelete : m_resourceDeleteQueue_MaterialParametersInstance )
        {
            DeleteShaderParameters( eastl::move( materialParameterInstanceDelete.first ) );
        }
        m_resourceDeleteQueue_MaterialParametersInstance.clear();

        for ( auto &stagingDelete : m_resourceDeleteQueue_StagingAllocation )
        {
            RHI::BufferSubDeallocate( m_pStagingBuffer, eastl::move( stagingDelete.first ) );
        }
        m_resourceDeleteQueue_StagingAllocation.clear();

        m_meshAllocator.Shutdown();
        m_meshClusterAllocator.Shutdown();
        m_shaderDataAllocator.Shutdown();

        for ( RHI::Sampler*& pSampler : m_commonSamplers )
        {
            RHI::DestroySampler( m_pContextRHI, eastl::move( pSampler ) );
        }

        RHI::DestroyBuffer( m_pContextRHI, eastl::move( m_pShaderDataBuffer ) );
        RHI::DestroyBuffer( m_pContextRHI, eastl::move( m_pMeshBuffer ) );
        RHI::DestroyBuffer( m_pContextRHI, eastl::move( m_pMeshClusterBuffer ) );

        ShutdownShaders();

        for ( AsyncBufferUpdate* pBufferUpdate : m_asyncBufferUpdateQueue )
        {
            if ( pBufferUpdate->m_stagingAllocation.IsValid() )
            {
                RHI::BufferSubDeallocate( m_pStagingBuffer, eastl::move( pBufferUpdate->m_stagingAllocation ) );
            }
            EE::Delete( pBufferUpdate );
        }
        m_asyncBufferUpdateQueue.clear();

        for ( AsyncTextureUpdate* pTextureUpdate : m_asyncTextureUpdateQueue )
        {
            RHI::BufferSubDeallocate( m_pStagingBuffer, eastl::move( pTextureUpdate->m_stagingAllocation ) );
            EE::Delete( pTextureUpdate );
        }
        m_asyncTextureUpdateQueue.clear();

        RHI::DestroyBuffer( m_pContextRHI, eastl::move( m_pStagingBuffer ) );

        RHI::DestroyQueue( m_pContextRHI, eastl::move( m_pGraphicsQueue ) );
        RHI::DestroyQueue( m_pContextRHI, eastl::move( m_pComputeQueue ) );
        RHI::DestroyQueue( m_pContextRHI, eastl::move( m_pTransferQueue ) );
        RHI::DestroyContext( eastl::move( m_pContextRHI ) );
    }

    void RenderSystem::InitializeShaders()
    {
        Shaders::Initialize( m_pContextRHI, m_materialShaders, m_surfaceShaders, m_computeShaders );
    }

    void RenderSystem::ShutdownShaders()
    {
        for ( MaterialShader& materialShader : m_materialShaders )
        {
            materialShader.Shutdown( m_pContextRHI );
        }
        m_materialShaders.clear();

        for ( SurfaceShader& surfaceShader : m_surfaceShaders )
        {
            surfaceShader.Shutdown( m_pContextRHI );
        }
        m_surfaceShaders.clear();

        for ( ComputeShader& computeShader : m_computeShaders )
        {
            computeShader.Shutdown( m_pContextRHI );
        }
        m_computeShaders.clear();
    }

    void RenderSystem::WaitForFrameStart()
    {
        EE_PROFILE_FUNCTION_RENDER();
        EE_ASSERT( m_internalStage[m_frameIndex] == InternalStage::None );

        RHI::QueueHostWait( m_pGraphicsQueue, m_frameSemaphores[m_frameIndex] );
    }

    void RenderSystem::StartResourceUpdates( bool wait )
    {
        EE_PROFILE_FUNCTION_RENDER();
        EE_ASSERT( m_internalStage[m_frameIndex] == InternalStage::None );

        #if EE_DEVELOPMENT_TOOLS
        m_internalStage[m_frameIndex] = InternalStage::ResourceUpdate;
        #endif

        if ( wait )
        {
            WaitGraphicsQueueIdle();
        }

        //---------------------------------------------------------------------------------------------------

        RHI::CommandPool* pFrameCommandPool = m_frameCommandPools[m_frameIndex];
        RHI::ResetCommandPool( m_pContextRHI, pFrameCommandPool );

        RHI::CommandBuffer* pFrameCommandBuffer = m_frameCommandBuffers[m_frameIndex];
        RHI::BeginCommandBuffer( pFrameCommandBuffer );

        {
            Threading::ScopeLockWrite lock( m_asyncResourceUpdateMutex );

            // Async mesh updates
            //-------------------------------------------------------------------------
            for ( size_t asyncMeshUpdateIndex = 0; asyncMeshUpdateIndex < m_asyncMeshUpdateQueue.size(); ++asyncMeshUpdateIndex )
            {
                AsyncMeshUpdate* pMeshUpdate = m_asyncMeshUpdateQueue[asyncMeshUpdateIndex];
                AsyncResourceUpdateState updateState = pMeshUpdate->m_updateState.load();

                switch ( updateState )
                {
                    case AsyncResourceUpdateState::AllocatePending:
                    {
                        pMeshUpdate->m_meshUpdate = CreateMesh( pMeshUpdate->m_numMeshes, pMeshUpdate->m_numClustersForAllMeshes );
                        pMeshUpdate->m_updateState.store( AsyncResourceUpdateState::UpdatePending );
                    }
                    break;

                    case AsyncResourceUpdateState::SubmitPending:
                    {
                        QueueMeshUpdate( pMeshUpdate->m_meshUpdate.m_meshHandle, pMeshUpdate->m_meshUpdate.m_clustersHandle );

                        //pMeshUpdate->m_updateState.store( AsyncResourceUpdateState::TransferPending );
                        pMeshUpdate->m_updateState.store( AsyncResourceUpdateState::CompletePending );
                    }
                    break;

                    case AsyncResourceUpdateState::TransferPending:
                    case AsyncResourceUpdateState::UpdatePending:
                    case AsyncResourceUpdateState::CompletePending:
                    {
                        // Do nothing, waiting for external updates
                    }
                    break;

                    case AsyncResourceUpdateState::Completed:
                    {
                        EE::Delete( pMeshUpdate );
                        VectorEraseUnordered( m_asyncMeshUpdateQueue, asyncMeshUpdateIndex-- );
                    }
                    break;
                }
            }

            // Async shader data updates
            //-------------------------------------------------------------------------
            for ( size_t asyncShaderDataUpdateIndex = 0; asyncShaderDataUpdateIndex < m_asyncShaderDataUpdateQueue.size(); ++asyncShaderDataUpdateIndex )
            {
                AsyncShaderDataUpdate* pShaderDataUpdate = m_asyncShaderDataUpdateQueue[asyncShaderDataUpdateIndex];
                AsyncResourceUpdateState updateState = pShaderDataUpdate->m_updateState.load();

                switch ( updateState )
                {
                    case AsyncResourceUpdateState::AllocatePending:
                    {
                        pShaderDataUpdate->m_shaderDataHandle = CreateShaderData( pShaderDataUpdate->m_shaderDataSizeInBytes );
                        pShaderDataUpdate->m_updateState.store( AsyncResourceUpdateState::UpdatePending );
                    }
                    break;

                    case AsyncResourceUpdateState::SubmitPending:
                    {
                        QueueShaderDataUpdate( pShaderDataUpdate->m_shaderDataHandle );

                        //pShaderDataUpdate->m_updateState.store( AsyncResourceUpdateState::TransferPending );
                        pShaderDataUpdate->m_updateState.store( AsyncResourceUpdateState::CompletePending );
                    }
                    break;

                    case AsyncResourceUpdateState::TransferPending:
                    case AsyncResourceUpdateState::UpdatePending:
                    case AsyncResourceUpdateState::CompletePending:
                    {
                        // Do nothing, waiting for external updates
                    }
                    break;

                    case AsyncResourceUpdateState::Completed:
                    {
                        EE::Delete( pShaderDataUpdate );
                        VectorEraseUnordered( m_asyncShaderDataUpdateQueue, asyncShaderDataUpdateIndex-- );
                    }
                    break;
                }
            }

            // Async material parameters updates
            //-------------------------------------------------------------------------
            for ( size_t asyncMaterialParametersUpdateIndex = 0; asyncMaterialParametersUpdateIndex < m_asyncMaterialParametersUpdateQueue.size(); ++asyncMaterialParametersUpdateIndex )
            {
                AsyncMaterialParametersUpdate* pMaterialParametersUpdate = m_asyncMaterialParametersUpdateQueue[asyncMaterialParametersUpdateIndex];
                AsyncResourceUpdateState updateState = pMaterialParametersUpdate->m_updateState.load();

                switch ( updateState )
                {
                    case AsyncResourceUpdateState::AllocatePending:
                    {
                        pMaterialParametersUpdate->m_materialShaderParameters = CreateShaderParameters( pMaterialParametersUpdate->m_shaderIndex );
                        pMaterialParametersUpdate->m_updateState.store( AsyncResourceUpdateState::UpdatePending );
                    }
                    break;

                    case AsyncResourceUpdateState::SubmitPending:
                    {
                        QueueShaderParametersUpdate( pMaterialParametersUpdate->m_materialShaderParameters );

                        //pMaterialParametersUpdate->m_updateState.store( AsyncResourceUpdateState::TransferPending );
                        pMaterialParametersUpdate->m_updateState.store( AsyncResourceUpdateState::CompletePending );
                    }
                    break;

                    case AsyncResourceUpdateState::TransferPending:
                    case AsyncResourceUpdateState::UpdatePending:
                    case AsyncResourceUpdateState::CompletePending:
                    {
                        // Do nothing, waiting for external updates
                    }
                    break;

                    case AsyncResourceUpdateState::Completed:
                    {
                        EE::Delete( pMaterialParametersUpdate );
                        VectorEraseUnordered( m_asyncMaterialParametersUpdateQueue, asyncMaterialParametersUpdateIndex );
                    }
                    break;
                }
            }
        }
    }

    void RenderSystem::SubmitResourceUpdates( bool wait )
    {
        EE_PROFILE_FUNCTION_RENDER();
        EE_ASSERT( m_internalStage[m_frameIndex] == InternalStage::ResourceUpdate );

        //---------------------------------------------------------------------------------------------------

        RHI::CommandBuffer* pCommonCommandBuffer = m_frameCommandBuffers[m_frameIndex];

        if ( m_hasCopyBarriers[m_frameIndex] )
        {
            RHI::CmdBarrier( pCommonCommandBuffer, RHI::PipelineStage::Copy, RHI::PipelineStage::All, RHI::ResourceAccess::CopyDestination, RHI::ResourceAccess::Common );

            m_hasCopyBarriers[m_frameIndex] = false;
        }

        RHI::EndCommandBuffer( pCommonCommandBuffer );

        //---------------------------------------------------------------------------------------------------

        // Submit queue
        m_resourceUpdateSemaphores[m_frameIndex] = RHI::QueueSubmit( m_pGraphicsQueue, { &pCommonCommandBuffer, 1 } );

        if ( wait )
        {
            WaitGraphicsQueueIdle();
        }

        #if EE_DEVELOPMENT_TOOLS
        m_internalStage[m_frameIndex] = InternalStage::None;
        #endif
    }

    void RenderSystem::StartAsyncResourceUpdates( bool wait )
    {
        EE_PROFILE_FUNCTION_RENDER();
        EE_ASSERT( m_internalStage[m_frameIndex] == InternalStage::None );

        #if EE_DEVELOPMENT_TOOLS
        m_internalStage[m_frameIndex] = InternalStage::AsyncResourceUpdate;
        #endif

        if ( wait )
        {
            WaitTransferQueueIdle();
        }

        RHI::QueueHostWait( m_pTransferQueue, m_asyncTransferSemaphores[m_asyncTransferIndex] );

        //---------------------------------------------------------------------------------------------------

        RHI::CommandPool* pTransferCommandPool = m_asyncTransferCommandPools[m_asyncTransferIndex];
        RHI::ResetCommandPool( m_pContextRHI, pTransferCommandPool );

        RHI::CommandBuffer* pTransferCommandBuffer = m_asyncTransferCommandBuffers[m_asyncTransferIndex];
        RHI::BeginCommandBuffer( pTransferCommandBuffer );
    }

    void RenderSystem::SubmitAsyncResourceUpdates( bool wait )
    {
        EE_PROFILE_FUNCTION_RENDER();
        EE_ASSERT( m_internalStage[m_frameIndex] == InternalStage::AsyncResourceUpdate );

        //---------------------------------------------------------------------------------------------------

        if ( wait )
        {
            WaitTransferQueueIdle();
        }

        //---------------------------------------------------------------------------------------------------


        RHI::CommandBuffer* pTransferCommandBuffer = m_asyncTransferCommandBuffers[m_asyncTransferIndex];

        bool hasCopies = false;
        {
            uint64_t transferSignalSemaphore = RHI::QueueGetCurrentSemaphore( m_pTransferQueue ) + 1;
            uint64_t transferCompletedSemaphore = RHI::QueueGetCompletedSemaphore( m_pTransferQueue );

            EE_ASSERT( transferSignalSemaphore > transferCompletedSemaphore );

            Threading::ScopeLockWrite lock( m_asyncResourceUpdateMutex );

            for ( size_t asyncBufferUpdateIndex = 0; asyncBufferUpdateIndex < m_asyncBufferUpdateQueue.size(); ++asyncBufferUpdateIndex )
            {
                AsyncBufferUpdate* pBufferUpdate = m_asyncBufferUpdateQueue[asyncBufferUpdateIndex];
                AsyncResourceUpdateState updateState = pBufferUpdate->m_updateState.load();

                switch ( updateState )
                {
                    case AsyncResourceUpdateState::AllocatePending:
                    {
                        EE_ASSERT( !pBufferUpdate->m_stagingAllocation.IsValid() );

                        // TODO: Handle UMA for async buffer updates
                        RHI::BufferSubAllocation stagingAllocation = RHI::BufferSubAllocate( m_pStagingBuffer, pBufferUpdate->m_bufferParameters.m_bufferSize, StagingBufferAlignment );
                        if ( !stagingAllocation.IsValid() )
                        {
                            continue;
                        }

                        pBufferUpdate->m_pDstBuffer = RHI::CreateBuffer( m_pContextRHI, pBufferUpdate->m_bufferParameters );
                        pBufferUpdate->m_dstSize = pBufferUpdate->m_bufferParameters.m_bufferSize;
                        pBufferUpdate->m_dstOffset = 0;
                        pBufferUpdate->m_pDstMemory_WriteCombined = static_cast<uint8_t*>( m_pStagingBuffer->m_pMappedAddress_WriteCombined ) + stagingAllocation.m_offset;
                        pBufferUpdate->m_stagingAllocation = eastl::move( stagingAllocation );

                        pBufferUpdate->m_updateState.store( AsyncResourceUpdateState::UpdatePending );
                    }
                    break;

                    case AsyncResourceUpdateState::SubmitPending:
                    {
                        RHI::CmdCopyBuffer
                        (
                            pTransferCommandBuffer,
                            pBufferUpdate->m_pDstBuffer, pBufferUpdate->m_dstOffset,
                            m_pStagingBuffer, pBufferUpdate->m_stagingAllocation.m_offset,
                            pBufferUpdate->m_dstSize
                        );
                        hasCopies = true;

                        pBufferUpdate->m_waitSemaphore = transferSignalSemaphore;
                        pBufferUpdate->m_updateState.store( AsyncResourceUpdateState::TransferPending );
                    }
                    break;

                    case AsyncResourceUpdateState::TransferPending:
                    {
                        if ( transferCompletedSemaphore > pBufferUpdate->m_waitSemaphore )
                        {
                            if ( pBufferUpdate->m_stagingAllocation.IsValid() )
                            {
                                RHI::BufferSubDeallocate( m_pStagingBuffer, eastl::move( pBufferUpdate->m_stagingAllocation ) );
                            }

                            pBufferUpdate->m_updateState.store( AsyncResourceUpdateState::CompletePending );
                        }
                    }
                    break;

                    case AsyncResourceUpdateState::UpdatePending:
                    case AsyncResourceUpdateState::CompletePending:
                    {
                        // Do nothing, waiting for external updates
                    }
                    break;

                    case AsyncResourceUpdateState::Completed:
                    {
                        if ( transferCompletedSemaphore > pBufferUpdate->m_waitSemaphore )
                        {
                            EE_ASSERT( !pBufferUpdate->m_stagingAllocation.IsValid() );

                            EE::Delete( pBufferUpdate );
                            VectorEraseUnordered( m_asyncBufferUpdateQueue, asyncBufferUpdateIndex-- );
                        }
                    }
                    break;
                }
            }

            for ( size_t asyncTextureUpdateIndex = 0; asyncTextureUpdateIndex < m_asyncTextureUpdateQueue.size(); ++asyncTextureUpdateIndex )
            {
                AsyncTextureUpdate* pTextureUpdate = m_asyncTextureUpdateQueue[asyncTextureUpdateIndex];
                AsyncResourceUpdateState updateState = pTextureUpdate->m_updateState.load();

                switch ( updateState )
                {
                    case AsyncResourceUpdateState::AllocatePending:
                    {
                        EE_ASSERT( pTextureUpdate->m_textureParameters.m_initialState == RHI::TextureState::Common );

                        if ( pTextureUpdate->m_pDstTexture == nullptr )
                        {
                            pTextureUpdate->m_pDstTexture = RHI::CreateTexture( m_pContextRHI, pTextureUpdate->m_textureParameters );
                        }

                        RHI::TextureCopyRegion dstTextureRegion = {};
                        dstTextureRegion.m_width = pTextureUpdate->m_textureParameters.m_width;
                        dstTextureRegion.m_height = pTextureUpdate->m_textureParameters.m_height;
                        dstTextureRegion.m_depth = pTextureUpdate->m_textureParameters.m_depth;

                        size_t sizeInBytes = 0;
                        for ( uint32_t arrayLayer = 0; arrayLayer < pTextureUpdate->m_textureParameters.m_arrayLayers; ++arrayLayer )
                        {
                            for ( uint32_t mipLevel = 0; mipLevel < pTextureUpdate->m_textureParameters.m_mipLevels; ++mipLevel )
                            {
                                RHI::TextureCopyRegion mipRegion = dstTextureRegion.SkipTo( mipLevel, arrayLayer );

                                size_t const numSrcRows = RHI::ComputeFormatNumRows( pTextureUpdate->m_textureParameters.m_format, mipRegion.m_height );
                                size_t const dstRowStride = RHI::GetTextureCopyRowStride( pTextureUpdate->m_pDstTexture, mipLevel, arrayLayer );
                                sizeInBytes += numSrcRows * dstRowStride * mipRegion.m_depth;
                            }
                        }

                        EE_ASSERT( !pTextureUpdate->m_stagingAllocation.IsValid() );

                        RHI::BufferSubAllocation stagingAllocation = RHI::BufferSubAllocate( m_pStagingBuffer, sizeInBytes, StagingBufferAlignment );
                        if ( !stagingAllocation.IsValid() )
                        {
                            continue;
                        }

                        pTextureUpdate->m_dstCopyRegion = dstTextureRegion;
                        pTextureUpdate->m_numArrayLayers = pTextureUpdate->m_textureParameters.m_arrayLayers;
                        pTextureUpdate->m_numMipLevels = pTextureUpdate->m_textureParameters.m_mipLevels;
                        pTextureUpdate->m_pDstMemory_WriteCombined = static_cast<uint8_t*>( m_pStagingBuffer->m_pMappedAddress_WriteCombined ) + stagingAllocation.m_offset;
                        pTextureUpdate->m_stagingAllocation = eastl::move( stagingAllocation );
                        pTextureUpdate->m_dstTextureState = pTextureUpdate->m_textureParameters.m_initialState;

                        pTextureUpdate->m_updateState.store( AsyncResourceUpdateState::UpdatePending );
                    }
                    break;

                    case AsyncResourceUpdateState::SubmitPending:
                    {
                        size_t dstCopyOffset = 0;
                        for ( uint32_t arrayLayer = pTextureUpdate->m_dstCopyRegion.m_arrayLayer; arrayLayer < ( pTextureUpdate->m_dstCopyRegion.m_arrayLayer + pTextureUpdate->m_numArrayLayers ); ++arrayLayer )
                        {
                            for ( uint32_t mipLevel = pTextureUpdate->m_dstCopyRegion.m_mipLevel; mipLevel < ( pTextureUpdate->m_dstCopyRegion.m_mipLevel + pTextureUpdate->m_numMipLevels ); ++mipLevel )
                            {
                                RHI::TextureCopyRegion dstCopyRegion = pTextureUpdate->m_dstCopyRegion.SkipTo( mipLevel, arrayLayer );
                                EE_ASSERT( dstCopyRegion.m_width >= 4 && dstCopyRegion.m_height >= 4 );

                                RHI::CmdCopyTexture
                                (
                                    pTransferCommandBuffer, pTextureUpdate->m_pDstTexture, dstCopyRegion,
                                    m_pStagingBuffer, dstCopyOffset + pTextureUpdate->m_stagingAllocation.m_offset
                                );

                                size_t const numSrcRows = RHI::ComputeFormatNumRows( pTextureUpdate->m_pDstTexture->m_format, dstCopyRegion.m_height );
                                size_t const dstRowStride = RHI::GetTextureCopyRowStride( pTextureUpdate->m_pDstTexture, mipLevel, arrayLayer );
                                dstCopyOffset += dstRowStride * numSrcRows * dstCopyRegion.m_depth;
                            }
                        }

                        hasCopies = true;

                        pTextureUpdate->m_waitSemaphore = transferSignalSemaphore;
                        pTextureUpdate->m_updateState.store( AsyncResourceUpdateState::TransferPending );
                    }
                    break;

                    case AsyncResourceUpdateState::TransferPending:
                    {
                        if ( transferCompletedSemaphore > pTextureUpdate->m_waitSemaphore )
                        {
                            EE_ASSERT( pTextureUpdate->m_stagingAllocation.IsValid() );
                            RHI::BufferSubDeallocate( m_pStagingBuffer, eastl::move( pTextureUpdate->m_stagingAllocation ) );

                            pTextureUpdate->m_updateState.store( AsyncResourceUpdateState::CompletePending );
                        }
                    }
                    break;

                    case AsyncResourceUpdateState::UpdatePending:
                    case AsyncResourceUpdateState::CompletePending:
                    {
                        // Do nothing, waiting for external updates
                    }
                    break;

                    case AsyncResourceUpdateState::Completed:
                    {
                        if ( transferCompletedSemaphore > pTextureUpdate->m_waitSemaphore )
                        {
                            EE_ASSERT( !pTextureUpdate->m_stagingAllocation.IsValid() );

                            EE::Delete( pTextureUpdate );
                            VectorEraseUnordered( m_asyncTextureUpdateQueue, asyncTextureUpdateIndex-- );
                        }
                    }
                    break;
                }
            }
        }

        if ( hasCopies )
        {
            RHI::CmdBarrier( pTransferCommandBuffer, RHI::PipelineStage::Copy, RHI::PipelineStage::All, RHI::ResourceAccess::CopyDestination, RHI::ResourceAccess::Common );
        }

        RHI::EndCommandBuffer( pTransferCommandBuffer );

        Memory::WriteCombinedBarrier();

        // Submit queue
        m_asyncTransferSemaphores[m_asyncTransferIndex] = RHI::QueueSubmit( m_pTransferQueue, { &pTransferCommandBuffer, 1 } );

        m_asyncTransferIndex = ( m_asyncTransferIndex + 1 ) % MaxPendingTransfers;

        //---------------------------------------------------------------------------------------------------

        if ( wait )
        {
            WaitTransferQueueIdle();
        }

        #if EE_DEVELOPMENT_TOOLS
        m_internalStage[m_frameIndex] = InternalStage::None;
        #endif
    }

    void RenderSystem::StartFrame()
    {
        EE_PROFILE_FUNCTION_RENDER();

        EE_ASSERT( Threading::IsMainThread() );
        EE_ASSERT( m_internalStage[m_frameIndex] == InternalStage::None );

        #if EE_DEVELOPMENT_TOOLS
        m_internalStage[m_frameIndex] = InternalStage::GraphicsUpdate;
        #endif

        //---------------------------------------------------------------------------------------------------

        for ( Window* pRenderWindow : m_registeredRenderWindows )
        {
            pRenderWindow->StartFrame( m_pContextRHI, m_frameIndex );

            RHI::CommandBuffer* pCommandBuffer = pRenderWindow->GetActiveCommandBuffer( m_frameIndex );

            RHI::CmdBarrier
            (
                pCommandBuffer, pRenderWindow->GetCurrentRenderTarget(),
                RHI::PipelineStage::All, RHI::PipelineStage::All,
                RHI::ResourceAccess::Present, RHI::ResourceAccess::RenderTarget,
                RHI::TextureState::Present, RHI::TextureState::RenderTarget,
                {}, {}
            );
        }

        // Resolve pending resource deletes
        //---------------------------------------------------------------------------------------------------
        {
            Threading::ScopeLockWrite lock( m_resourceDeleteMutex );

            for ( size_t pendingResourceDeleteIndex = 0; pendingResourceDeleteIndex < m_resourceDeleteQueue_Buffer.size(); ++pendingResourceDeleteIndex )
            {
                TPair<RHI::Buffer*, int32_t>& pendingResourceDelete = m_resourceDeleteQueue_Buffer[pendingResourceDeleteIndex];
                pendingResourceDelete.second--;

                if ( pendingResourceDelete.second < 0 )
                {
                    RHI::DestroyBuffer( m_pContextRHI, eastl::move( pendingResourceDelete.first ) );
                    VectorEraseUnordered( m_resourceDeleteQueue_Buffer, pendingResourceDeleteIndex-- );
                }
            }

            for ( size_t pendingResourceDeleteIndex = 0; pendingResourceDeleteIndex < m_resourceDeleteQueue_Texture.size(); ++pendingResourceDeleteIndex )
            {
                TPair<RHI::Texture*, int32_t>& pendingResourceDelete = m_resourceDeleteQueue_Texture[pendingResourceDeleteIndex];
                pendingResourceDelete.second--;

                if ( pendingResourceDelete.second < 0 )
                {
                    RHI::DestroyTexture( m_pContextRHI, eastl::move( pendingResourceDelete.first ) );
                    VectorEraseUnordered( m_resourceDeleteQueue_Texture, pendingResourceDeleteIndex-- );
                }
            }

            // TODO: This doesn't need to be locked
            for ( size_t pendingResourceDeleteIndex = 0; pendingResourceDeleteIndex < m_resourceDeleteQueue_StagingAllocation.size(); ++pendingResourceDeleteIndex )
            {
                TPair<RHI::BufferSubAllocation, int32_t>& pendingResourceDelete = m_resourceDeleteQueue_StagingAllocation[pendingResourceDeleteIndex];
                pendingResourceDelete.second--;

                if ( pendingResourceDelete.second < 0 )
                {
                    RHI::BufferSubDeallocate( m_pStagingBuffer, eastl::move( pendingResourceDelete.first ) );
                    VectorEraseUnordered( m_resourceDeleteQueue_StagingAllocation, pendingResourceDeleteIndex-- );
                }
            }

            for ( size_t pendingResourceDeleteIndex = 0; pendingResourceDeleteIndex < m_resourceDeleteQueue_Mesh.size(); ++pendingResourceDeleteIndex )
            {
                TPair<TPair<MeshHandle, ClustersHandle>, int32_t>& pendingResourceDelete = m_resourceDeleteQueue_Mesh[pendingResourceDeleteIndex];
                pendingResourceDelete.second--;

                if ( pendingResourceDelete.second < 0 )
                {
                    DeleteMesh( eastl::move( pendingResourceDelete.first.first ), eastl::move( pendingResourceDelete.first.second ) );
                    VectorEraseUnordered( m_resourceDeleteQueue_Mesh, pendingResourceDeleteIndex-- );
                }
            }

            for ( size_t pendingResourceDeleteIndex = 0; pendingResourceDeleteIndex < m_resourceDeleteQueue_ShaderData.size(); ++pendingResourceDeleteIndex )
            {
                TPair<ShaderDataHandle, int32_t>& pendingResourceDelete = m_resourceDeleteQueue_ShaderData[pendingResourceDeleteIndex];
                pendingResourceDelete.second--;

                if ( pendingResourceDelete.second < 0 )
                {
                    DeleteShaderData( eastl::move( pendingResourceDelete.first ) );
                    VectorEraseUnordered( m_resourceDeleteQueue_ShaderData, pendingResourceDeleteIndex-- );
                }
            }

            for ( size_t pendingResourceDeleteIndex = 0; pendingResourceDeleteIndex < m_resourceDeleteQueue_MaterialParametersInstance.size(); ++pendingResourceDeleteIndex )
            {
                TPair<MaterialShaderParametersInstance, int32_t>& pendingResourceDelete = m_resourceDeleteQueue_MaterialParametersInstance[pendingResourceDeleteIndex];
                pendingResourceDelete.second--;

                if ( pendingResourceDelete.second < 0 )
                {
                    DeleteShaderParameters( eastl::move( pendingResourceDelete.first ) );
                    VectorEraseUnordered( m_resourceDeleteQueue_MaterialParametersInstance, pendingResourceDeleteIndex-- );
                }
            }
        }
    }

    void RenderSystem::SubmitFrame()
    {
        EE_PROFILE_FUNCTION_RENDER();

        EE_ASSERT( Threading::IsMainThread() );
        EE_ASSERT( m_internalStage[m_frameIndex] == InternalStage::GraphicsUpdate );

        #if EE_DEVELOPMENT_TOOLS
        m_internalStage[m_frameIndex] = InternalStage::None;
        #endif

        for ( Window* pRenderWindow : m_registeredRenderWindows )
        {
            // Issue final barrier and end command buffer
            RHI::CommandBuffer* pCommandBuffer = pRenderWindow->GetActiveCommandBuffer( m_frameIndex );

            RHI::CmdBarrier
            (
                pCommandBuffer,
                pRenderWindow->GetCurrentRenderTarget(),
                RHI::PipelineStage::All, RHI::PipelineStage::All,
                RHI::ResourceAccess::RenderTarget, RHI::ResourceAccess::Present,
                RHI::TextureState::RenderTarget, RHI::TextureState::Present,
                {}, {}
            );

            RHI::EndCommandBuffer( pCommandBuffer );

            Memory::WriteCombinedBarrier();

            // Submit queue
            RHI::QueueSubmit( m_pGraphicsQueue, { &pCommandBuffer, 1 } );

            // Present queue
            m_frameSemaphores[m_frameIndex] = RHI::QueuePresent( m_pGraphicsQueue, pRenderWindow->GetSwapchain(), pRenderWindow->GetCurrentImageIndex() );
        }

        m_frameIndex = ( m_frameIndex + 1 ) % RHI::MaxPendingFrames;
    }

    void RenderSystem::WaitAllQueuesIdle()
    {
        EE_ASSERT( Threading::IsMainThread() );

        RHI::WaitQueueIdle( m_pGraphicsQueue );
        RHI::WaitQueueIdle( m_pComputeQueue );
        RHI::WaitQueueIdle( m_pTransferQueue );
    }

    void RenderSystem::WaitGraphicsQueueIdle()
    {
        EE_ASSERT( Threading::IsMainThread() );

        RHI::WaitQueueIdle( m_pGraphicsQueue );
    }

    void RenderSystem::WaitComputeQueueIdle()
    {
        EE_ASSERT( Threading::IsMainThread() );

        RHI::WaitQueueIdle( m_pComputeQueue );
    }

    void RenderSystem::WaitTransferQueueIdle()
    {
        EE_ASSERT( Threading::IsMainThread() );

        RHI::WaitQueueIdle( m_pTransferQueue );
    }

    //-------------------------------------------------------------------------------------------------------

    void RenderSystem::RegisterRenderWindow( Window* pRenderWindow )
    {
        m_registeredRenderWindows.push_back( pRenderWindow );
    }

    void RenderSystem::UnregisterRenderWindow( Window* pRenderWindow )
    {
        auto foundWindow = VectorFind( m_registeredRenderWindows, pRenderWindow );
        EE_ASSERT( foundWindow != m_registeredRenderWindows.end() );

        m_registeredRenderWindows.erase( foundWindow );
    }

    TArrayView<Window* const> RenderSystem::GetRegisteredRenderWindows() const
    {
        return m_registeredRenderWindows;
    }

    bool RenderSystem::IsSingleRenderWindow()const
    {
        EE_ASSERT( !m_registeredRenderWindows.empty() );
        return m_registeredRenderWindows.size() == 1;
    }

    // Viewports
    //-------------------------------------------------------------------------------------------------------

    Viewport* RenderSystem::CreateViewport( Render::Window* pRenderWindow )
    {
        EE_ASSERT( pRenderWindow != nullptr );

        RenderViewport* pRenderViewport = EE::New<RenderViewport>();
        pRenderViewport->Initialize( GetContextRHI(), pRenderWindow );
        m_renderViewports.emplace_back( pRenderViewport );
        return pRenderViewport;
    }

    void RenderSystem::DestroyViewport( Viewport* pViewport )
    {
        for ( int32_t i = int32_t( m_renderViewports.size() ) - 1; i >= 0; i-- )
        {
            if ( m_renderViewports[i] == pViewport )
            {
                RenderViewport* pRenderViewport = static_cast<RenderViewport*>( pViewport );
                pRenderViewport->Shutdown( GetContextRHI() );

                EE::Delete( pRenderViewport );

                m_renderViewports.erase_unsorted( m_renderViewports.begin() + i );
                return;
            }
        }

        EE_UNREACHABLE_CODE();
    }

    // Meshes
    //-------------------------------------------------------------------------------------------------------

    MeshUpdate RenderSystem::CreateMesh( size_t numMeshes, size_t numClustersForAllMeshes )
    {
        EE_ASSERT( Threading::IsMainThread() );

        MeshHandle                              meshHandle = m_meshAllocator.Allocate( uint16_t( numMeshes ) );
        TArrayView<ShaderTypes::Mesh>           outMeshes = { reinterpret_cast<ShaderTypes::Mesh*>( m_meshAllocator.GetData() + meshHandle.m_handle.m_offset ), numMeshes };

        ClustersHandle                          clustersHandle = m_meshClusterAllocator.Allocate( uint32_t( numClustersForAllMeshes ) );
        TArrayView<ShaderTypes::MeshCluster>    outMeshClusters = { m_meshClusterAllocator.GetData() + clustersHandle.m_handle.m_offset, numClustersForAllMeshes };

        return { meshHandle, clustersHandle, outMeshes, outMeshClusters };
    }

    void RenderSystem::WriteCommonMeshData( MeshUpdate const& meshUpdate, size_t dstMesh, size_t dstCluster, Geometry const& geometry ) const
    {
        ShaderTypes::Mesh& deviceMesh = meshUpdate.m_deviceMeshes[dstMesh];

        deviceMesh.m_vertexStride = geometry.GetClusterVertexStride();

        AABB meshAABB = geometry.GetBounds().GetAABB();
        meshAABB.m_center.StoreFloat3( deviceMesh.m_aabbCenterLocal );
        meshAABB.m_halfExtents.StoreFloat3( deviceMesh.m_aabbHalfExtentsLocal );

        uint32_t meshClusterOffset = uint32_t( meshUpdate.m_clustersHandle.m_handle.m_offset + dstCluster );

        deviceMesh.m_clusterOffset = meshClusterOffset;
        deviceMesh.m_numClusters = geometry.GetNumClusters();

        ShaderTypes::MeshCluster const* pSrcClusters = reinterpret_cast<ShaderTypes::MeshCluster const*>( geometry.GetClusters().data() );
        for ( size_t clusterIndex = 0; clusterIndex < geometry.GetNumClusters(); ++clusterIndex )
        {
            ShaderTypes::MeshCluster cluster = pSrcClusters[clusterIndex];

            #if 0 // TODO: memcopy
            auto pMaterial = meshData.GetSectionMaterial( cluster.m_sectionIndex );
            if ( pMaterial == nullptr )
            {
                pMaterial = GetPlaceholderMaterial();
            }

            uint32_t shaderParametersOffsetIn32ByteBlocks = pMaterial->GetShaderParametersOffsetIn32ByteBlocks();
            cluster.m_shaderParametersOffsetIn32ByteBlocks = shaderParametersOffsetIn32ByteBlocks;
            #endif

            meshUpdate.m_deviceClusters[dstCluster + clusterIndex] = cluster;
        }
    }

    void RenderSystem::DeleteMesh( MeshHandle&& meshHandle, ClustersHandle&& clustersHandle )
    {
        EE_ASSERT( Threading::IsMainThread() );

        m_meshAllocator.Deallocate( eastl::move( meshHandle ) );
        m_meshClusterAllocator.Deallocate( eastl::move( clustersHandle ) );
    }

    void RenderSystem::QueueMeshUpdate( MeshHandle const& meshHandle, ClustersHandle const& clustersHandle )
    {
        EE_ASSERT( Threading::IsMainThread() );
        EE_ASSERT( m_internalStage[m_frameIndex] == InternalStage::ResourceUpdate );

        size_t meshBufferSize = m_meshAllocator.GetCapacityInBytes();
        void const* pMeshMemory = m_meshAllocator.GetData();

        size_t clusterBufferSize = m_meshClusterAllocator.GetCapacityInBytes();
        void const* pClusterMemory = m_meshClusterAllocator.GetData();

        if ( meshHandle.m_handle.m_size > 0 )
        {
            if ( !m_pMeshBuffer || m_pMeshBuffer->m_size < meshBufferSize )
            {
                if ( m_pMeshBuffer )
                {
                    QueueResourceDelete( eastl::move( m_pMeshBuffer ) );
                }

                RHI::BufferParameters bufferParameters = {};
                bufferParameters.m_bufferSize = meshBufferSize;
                bufferParameters.m_bufferStride = sizeof( ShaderTypes::Mesh );
                bufferParameters.m_debugName = "System_Renderer MeshBuffer";

                auto CopyBufferMemory = [pMeshMemory, meshBufferSize] ( uint8_t* pDstMemory_WriteCombined, size_t dstSize )
                {
                    EE_ASSERT( dstSize >= meshBufferSize );
                    Memory::CopyToWriteCombined( pDstMemory_WriteCombined, pMeshMemory, meshBufferSize );
                };
                m_pMeshBuffer = QueueBufferCreate( CopyBufferMemory, bufferParameters );
            }
            else
            {
                auto CopyBufferMemory = [this, meshHandle] ( uint8_t* pDstMemory_WriteCombined, size_t dstSize )
                {
                    Memory::CopyToWriteCombined( pDstMemory_WriteCombined, m_meshAllocator.GetData() + meshHandle.m_handle.m_offset, meshHandle.m_handle.m_size * sizeof( ShaderTypes::Mesh ) );
                };
                QueueBufferUpdate( CopyBufferMemory, m_pMeshBuffer, meshHandle.m_handle.m_offset * sizeof( ShaderTypes::Mesh ), meshHandle.m_handle.m_size * sizeof( ShaderTypes::Mesh ) );
            }
        }

        if ( clustersHandle.m_handle.m_size > 0 )
        {
            if ( !m_pMeshClusterBuffer || m_pMeshClusterBuffer->m_size < clusterBufferSize )
            {
                if ( m_pMeshClusterBuffer )
                {
                    QueueResourceDelete( eastl::move( m_pMeshClusterBuffer ) );
                }

                RHI::BufferParameters bufferParameters = {};
                bufferParameters.m_bufferSize = clusterBufferSize;
                bufferParameters.m_bufferStride = sizeof( ShaderTypes::MeshCluster );
                bufferParameters.m_debugName = "System_Renderer ClusterBuffer";

                auto CopyBufferMemory = [pClusterMemory, clusterBufferSize] ( uint8_t* pDstMemory_WriteCombined, size_t dstSize )
                {
                    EE_ASSERT( dstSize >= clusterBufferSize );
                    Memory::CopyToWriteCombined( pDstMemory_WriteCombined, pClusterMemory, clusterBufferSize );
                };
                m_pMeshClusterBuffer = QueueBufferCreate( CopyBufferMemory, bufferParameters );
            }
            else
            {
                auto CopyBufferMemory = [this, clustersHandle] ( uint8_t* pDstMemory_WriteCombined, size_t dstSize )
                {
                    Memory::CopyToWriteCombined( pDstMemory_WriteCombined, m_meshClusterAllocator.GetData() + clustersHandle.m_handle.m_offset, clustersHandle.m_handle.m_size * sizeof( ShaderTypes::MeshCluster ) );
                };
                QueueBufferUpdate( CopyBufferMemory, m_pMeshClusterBuffer, clustersHandle.m_handle.m_offset * sizeof( ShaderTypes::MeshCluster ), clustersHandle.m_handle.m_size * sizeof( ShaderTypes::MeshCluster ) );
            }
        }
    }

    RHI::BufferHandle RenderSystem::GetMeshBufferHandle() const
    {
        return RHI::GetBufferHandle( m_pMeshBuffer, RHI::DescriptorTypeFlags::Buffer );
    }

    RHI::BufferHandle RenderSystem::GetClusterBufferHandle() const
    {
        return RHI::GetBufferHandle( m_pMeshClusterBuffer, RHI::DescriptorTypeFlags::Buffer );
    }

    // Shaders
    //-------------------------------------------------------------------------------------------------------

    MaterialShader const* RenderSystem::FindMaterialShader( StringID const& shaderID ) const
    {
        auto const itr = VectorFind( m_materialShaders, shaderID, [] ( MaterialShader const& shader, StringID const& id )
        {
            return id == shader.m_shaderName;
        } );
        EE_ASSERT( itr != m_materialShaders.end() );
        return itr;
    }

    SurfaceShader const* RenderSystem::FindSurfaceShader( StringID const& shaderID ) const
    {
        auto const itr = VectorFind( m_surfaceShaders, shaderID, [] ( SurfaceShader const& shader, StringID const& id )
        {
            return id == shader.m_shaderName;
        } );
        EE_ASSERT( itr != m_surfaceShaders.end() );
        return itr;
    }

    ComputeShader const* RenderSystem::FindComputeShader( StringID const& shaderID ) const
    {
        auto const itr = VectorFind( m_computeShaders, shaderID, [] ( ComputeShader const& shader, StringID const& id )
        {
            return id == shader.m_shaderName;
        } );
        EE_ASSERT( itr != m_computeShaders.end() );
        return itr;
    }

    int32_t RenderSystem::FindMaterialShaderIndex( StringID const& shaderID ) const
    {
        return VectorFindIndex( m_materialShaders, shaderID, [] ( MaterialShader const& shader, StringID const& id )
        {
            return id == shader.m_shaderName;
        } );
    }

    MaterialShaderParametersInstance RenderSystem::CreateShaderParameters( size_t shaderIndex )
    {
        MaterialShader const& shaderInstance = m_materialShaders[shaderIndex];

        size_t parametersSizeInBytes = 0;
        for ( MaterialShaderParameterInfo const& parameterInfo : shaderInstance.m_parameterInfo )
        {
            parametersSizeInBytes += parameterInfo.m_parameterStrideInBytes;
        }

        EE_ASSERT( ( parametersSizeInBytes % 32 ) == 0 );

        uint32_t parametersSizeIn32ByteBlocks = uint32_t( parametersSizeInBytes / 32 );

        ShaderDataHandle handle = m_shaderDataAllocator.Allocate( parametersSizeIn32ByteBlocks );

        MaterialShaderParametersInstance parametersInstance = {};
        parametersInstance.m_handle = handle;
        parametersInstance.m_parameterInfo = TArrayView<MaterialShaderParameterInfo const>( shaderInstance.m_parameterInfo.data(), shaderInstance.m_parameterInfo.size() );
        parametersInstance.m_parametersMemory = { reinterpret_cast<uint8_t*>( handle.m_data.data() ), parametersSizeInBytes };

        parametersInstance.InitializeDefaultResourceHandles();

        return parametersInstance;
    }

    void RenderSystem::DeleteShaderParameters( MaterialShaderParametersInstance&& parameters )
    {
        EE_ASSERT( Threading::IsMainThread() );

        m_shaderDataAllocator.Deallocate( eastl::move( parameters.m_handle ) );
        parameters = {};
    }

    void RenderSystem::QueueShaderParametersUpdate( MaterialShaderParametersInstance const& parameters )
    {
        QueueShaderDataUpdate( parameters.m_handle );
    }

    // Shader data
    //-------------------------------------------------------------------------------------------------------

    ShaderDataHandle RenderSystem::CreateShaderData( uint32_t shaderDataSizeInBytes )
    {
        EE_ASSERT( Threading::IsMainThread() );

        ShaderDataHandle instanceDataHandle = m_shaderDataAllocator.Allocate( ( shaderDataSizeInBytes + 31 ) / 32 );
        return instanceDataHandle;
    }

    void RenderSystem::DeleteShaderData( ShaderDataHandle&& instanceDataHandle )
    {
        EE_ASSERT( Threading::IsMainThread() );

        m_shaderDataAllocator.Deallocate( eastl::move( instanceDataHandle ) );
        instanceDataHandle = {};
    }

    void RenderSystem::QueueShaderDataUpdate( ShaderDataHandle const& handle )
    {
        EE_ASSERT( Threading::IsMainThread() );
        EE_ASSERT( m_internalStage[m_frameIndex] == InternalStage::ResourceUpdate );

        size_t shaderDataBufferSize = m_shaderDataAllocator.GetCapacityInBytes();
        void const* pShaderDataMemory = m_shaderDataAllocator.GetData();

        if ( !m_pShaderDataBuffer || m_pShaderDataBuffer->m_size < shaderDataBufferSize )
        {
            if ( m_pShaderDataBuffer )
            {
                QueueResourceDelete( eastl::move( m_pShaderDataBuffer ) );
            }

            RHI::BufferParameters bufferParameters = {};
            bufferParameters.m_bufferSize = shaderDataBufferSize;
            bufferParameters.m_descriptorTypes.SetMultipleFlags( RHI::DescriptorTypeFlags::Buffer, RHI::DescriptorTypeFlags::Raw );
            bufferParameters.m_debugName = "System_Renderer ShaderDataBuffer";

            auto CopyBufferMemory = [pShaderDataMemory, shaderDataBufferSize] ( uint8_t* pDstMemory_WriteCombined, size_t dstSize )
            {
                EE_ASSERT( dstSize >= shaderDataBufferSize );
                Memory::CopyToWriteCombined( pDstMemory_WriteCombined, pShaderDataMemory, shaderDataBufferSize );
            };
            m_pShaderDataBuffer = QueueBufferCreate( CopyBufferMemory, bufferParameters );
        }
        else
        {
            auto CopyBufferMemory = [handle] ( uint8_t* pDstMemory_WriteCombined, size_t dstSize )
            {
                Memory::CopyToWriteCombined( pDstMemory_WriteCombined, handle.m_data.data(), handle.m_data.size_bytes() );
            };
            QueueBufferUpdate( CopyBufferMemory, m_pShaderDataBuffer, handle.m_handle.m_offset * 32, handle.m_data.size_bytes() );
        }
    }

    RHI::BufferHandle RenderSystem::GetShaderDataBufferHandle() const
    {
        return RHI::GetBufferHandle( m_pShaderDataBuffer, RHI::DescriptorTypeFlags::Buffer );
    }

    // Async resource updates
    //-------------------------------------------------------------------------------------------------------

    AsyncBufferUpdate* RenderSystem::CreateBufferAsync( RHI::BufferParameters const& bufferParameters )
    {
        AsyncBufferUpdate* pBufferUpdate = EE::New<AsyncBufferUpdate>();
        pBufferUpdate->m_bufferParameters = bufferParameters;

        {
            Threading::ScopeLockWrite lock( m_asyncResourceUpdateMutex );
            m_asyncBufferUpdateQueue.push_back( pBufferUpdate );
        }

        return pBufferUpdate;
    }

    AsyncTextureUpdate* RenderSystem::CreateTextureAsync( RHI::TextureParameters const& textureParameters )
    {
        AsyncTextureUpdate* pTextureUpdate = EE::New<AsyncTextureUpdate>();
        pTextureUpdate->m_textureParameters = textureParameters;

        {
            Threading::ScopeLockWrite lock( m_asyncResourceUpdateMutex );
            m_asyncTextureUpdateQueue.push_back( pTextureUpdate );
        }

        return pTextureUpdate;
    }

    AsyncMeshUpdate* RenderSystem::CreateMeshAsync( size_t numMeshes, size_t numClustersForAllMeshes )
    {
        AsyncMeshUpdate* pMeshUpdate = EE::New<AsyncMeshUpdate>();
        pMeshUpdate->m_numMeshes = numMeshes;
        pMeshUpdate->m_numClustersForAllMeshes = numClustersForAllMeshes;

        {
            Threading::ScopeLockWrite lock( m_asyncResourceUpdateMutex );
            m_asyncMeshUpdateQueue.push_back( pMeshUpdate );
        }

        return pMeshUpdate;
    }

    AsyncMaterialParametersUpdate* RenderSystem::CreateMaterialParametersAsync( size_t shaderIndex )
    {
        AsyncMaterialParametersUpdate* pMaterialParametersUpdate = EE::New<AsyncMaterialParametersUpdate>();
        pMaterialParametersUpdate->m_shaderIndex = shaderIndex;

        {
            Threading::ScopeLockWrite lock( m_asyncResourceUpdateMutex );
            m_asyncMaterialParametersUpdateQueue.push_back( pMaterialParametersUpdate );
        }

        return pMaterialParametersUpdate;
    }

    AsyncShaderDataUpdate* RenderSystem::CreateShaderDataAsync( uint32_t shaderDataSizeInBytes )
    {
        AsyncShaderDataUpdate* pShaderDataUpdate = EE::New<AsyncShaderDataUpdate>();
        pShaderDataUpdate->m_shaderDataSizeInBytes = shaderDataSizeInBytes;

        {
            Threading::ScopeLockWrite lock( m_asyncResourceUpdateMutex );
            m_asyncShaderDataUpdateQueue.push_back( pShaderDataUpdate );
        }

        return pShaderDataUpdate;
    }
}
