#ifdef _WIN32
#include "EngineApplication_win32.h"
#include "Engine/_Module/_AutoGenerated/TypeInfo/TypeRegistration.h"

#include "Resource.h"
#include <tchar.h>
#include <windows.h>

//-------------------------------------------------------------------------

namespace EE
{
    StandaloneEngine::StandaloneEngine( TFunction<bool( EE::String const& error )>&& errorHandler )
        : Engine( eastl::forward<TFunction<bool( EE::String const& error )>&&>( errorHandler ) )
    {
        m_modules.emplace_back( EE::New<GameModule>() );
    }

    void StandaloneEngine::RegisterTypes()
    {
        TypeSystem::Reflection::RegisterTypes( *m_pTypeRegistry );
    }

    void StandaloneEngine::UnregisterTypes()
    {
        TypeSystem::Reflection::UnregisterTypes( *m_pTypeRegistry );
    }

    void StandaloneEngine::PostInitialize()
    {
        m_pGameViewport = m_pEntityWorldManager->GetGameWorld()->CreateViewport( m_pRenderWindow );
        Float2 const newViewportDimensions( m_pRenderWindow->GetSwapchainSize() );
        m_pGameViewport->Resize( Float2::Zero, newViewportDimensions );
    }

    void StandaloneEngine::PreShutdown()
    {
        if ( m_pGameViewport != nullptr )
        {
            m_pEntityWorldManager->GetGameWorld()->DestroyViewport( m_pGameViewport );
        }
    }

    void StandaloneEngine::ResizeMainWindow( Int2 newMainWindowDimensions )
    {
        Engine::ResizeMainWindow( newMainWindowDimensions );

        //-------------------------------------------------------------------------

        if ( m_pGameViewport != nullptr )
        {
            Float2 const newWindowDimensions = Float2( newMainWindowDimensions );
            Int2 const newViewportDimensions( Math::CeilingToInt32( newWindowDimensions.m_x ), Math::CeilingToInt32( newWindowDimensions.m_y ) ); // Ensure we also have valid dimensions
            EE_ASSERT( newViewportDimensions.m_x > 0 && newViewportDimensions.m_y > 0 );
            m_pGameViewport->Resize( Float2::Zero, newViewportDimensions );
        }
    }

    //-------------------------------------------------------------------------

    EngineApplication::EngineApplication( HINSTANCE hInstance )
        : Win32Application( hInstance, "Esoterica Engine", IDI_ENGINE_ICON, IDB_SPLASHSCREEN )
        , m_engine( TFunction<bool( EE::String const& error )>( [this] ( String const& error )-> bool { return FatalError( error ); } ) )
    {}

    void EngineApplication::ResizeMainWindow( Int2 const& newWindowSize )
    {
        m_engine.ResizeMainWindow( newWindowSize );
    }

    void EngineApplication::ProcessInputMessage( UINT message, WPARAM wParam, LPARAM lParam )
    {
        m_engine.GetInputSystem()->ForwardInputMessageToInputDevices( { message, (uintptr_t) wParam, (uintptr_t) lParam } );
    }

    bool EngineApplication::Initialize( int32_t argc, char** argv )
    {
        #if EE_ENABLE_LPP
        LivePP_CreateAgent();
        LivePP_EnableModules();
        #endif

        Int2 const windowDimensions( ( m_windowRect.right - m_windowRect.left ), ( m_windowRect.bottom - m_windowRect.top ) );
        if ( !m_engine.Initialize( argc, argv, windowDimensions ) )
        {
            return FatalError( "Failed to initialize engine" );
        }

        return true;
    }

    bool EngineApplication::Shutdown()
    {
        #if EE_ENABLE_LPP
        LivePP_DestroyAgent();
        #endif

        return m_engine.Shutdown();
    }

    bool EngineApplication::ApplicationLoop()
    {
        #if EE_ENABLE_LPP
        LivePP_UpdateAgent();
        #endif

        return m_engine.Update();
    }
}

//-------------------------------------------------------------------------

int APIENTRY _tWinMain( HINSTANCE hInstance, HINSTANCE hPrevInstance, LPTSTR lpCmdLine, int nCmdShow )
{
    int result = 0;
    {
        EE::ApplicationGlobalState globalState;
        EE::EngineApplication engineApplication( hInstance );
        result = engineApplication.Run( __argc, __argv );
    }

    return result;
}

#endif