#include "ShaderReflection_ShaderCompiler.h"
#include "Applications/Reflector/ReflectedProject.h"

//-------------------------------------------------------------------------

namespace EE::Reflection
{
    #define DXC_ARG_HLSL_VERSION_2021 L"-HV", L"2021"
    #define DXC_ARG_ENABLE_16_BIT_TYPES L"-enable-16bit-types"
    #define DXC_ARG_ENTRY_POINT( X ) L"-E", X
    #define DXC_ARG_TARGET( X ) L"-T", X
    #define DXC_ARG_INCLUDE_DIRECTORY( X ) L"-I", X
    #define DXC_ARG_DEBUG_NAME( X ) DXC_ARG_DEBUG_NAME_FOR_SOURCE, X
    #define DXC_ARG_DEFINE( X ) L"-D", X
    #define DXC_ARG_EMBED_DEBUG L"-Qembed_debug"

    #define COMMON_DXC_ARGUMENTS_DEBUG( filename ) DXC_ARG_DEBUG, DXC_ARG_EMBED_DEBUG, DXC_ARG_DEBUG_NAME( filename.c_str() ), DXC_ARG_DEFINE( L"EE_DEVELOPMENT_TOOLS" )

    #define COMMON_DXC_ARGUMENTS( filename, sourceDir, codeDir )\
            COMMON_DXC_ARGUMENTS_DEBUG( filename ),\
            DXC_ARG_HLSL_VERSION_2021,\
            DXC_ARG_WARNINGS_ARE_ERRORS,\
            DXC_ARG_OPTIMIZATION_LEVEL3,\
            DXC_ARG_ENABLE_16_BIT_TYPES,\
            DXC_ARG_INCLUDE_DIRECTORY( sourceDir.c_str() ),\
            DXC_ARG_INCLUDE_DIRECTORY( codeDir.c_str() )

    //-------------------------------------------------------------------------

    ShaderCompiler::ShaderCompiler( FileSystem::Path const& solutionDirectoryPath, TVector<ReflectedProject>& projects, int32_t numCoresToUse )
        : m_projects( projects )
        , m_taskSystem( numCoresToUse )
        , m_compilationTask( [this] ( TaskSetPartition range, uint32_t threadNum ) { CompilationTask( range, threadNum ); } )
        , m_codeDirectoryPath( WString::CtorConvert(), solutionDirectoryPath.GetAppended( Settings::g_codeFolderPath, true ).c_str() )
    {
        m_taskSystem.Initialize();
    }

    ShaderCompiler::~ShaderCompiler()
    {
        m_taskSystem.WaitForAll();
        m_taskSystem.Shutdown();
    }

    bool ShaderCompiler::LogError( char const* pFormat, ... ) const
    {
        Threading::ScopeLock const l( m_mutex );

        va_list args;
        va_start( args, pFormat );
        m_errorMessage.append_sprintf_va_list( pFormat, args );
        m_errorMessage.append( "\n" );
        va_end( args );

        return false;
    }

    void ShaderCompiler::LogWarning( char const* pFormat, ... ) const
    {
        Threading::ScopeLock const l( m_mutex );

        va_list args;
        va_start( args, pFormat );
        String& str = m_warnings.emplace_back();
        str.append_sprintf_va_list( pFormat, args );
        va_end( args );
    }

    bool ShaderCompiler::CompileShaders()
    {
        // Generate list of shaders to compile
        //-------------------------------------------------------------------------

        m_shadersToCompile.clear();

        for ( ReflectedProject& project : m_projects )
        {
            if ( project.m_isExcludedFromShaderReflection )
            {
                continue;
            }

            for ( ReflectedShader& shader : project.m_shaders )
            {
                auto& item = m_shadersToCompile.emplace_back();
                item.m_pShader = &shader;
                item.m_outputPath = project.m_autogeneratedDirectoryPath;
            }
        }

        // Kick off task
        //-------------------------------------------------------------------------

        #if 0 // Single Threaded compilation for debug
        CompilationTask( TaskSetPartition( 0, (uint32_t) m_shadersToCompile.size() ), 0 );
        #else
        m_compilationTask.m_SetSize = (uint32_t) m_shadersToCompile.size();
        m_taskSystem.ScheduleTask( &m_compilationTask );
        m_taskSystem.WaitForAll();
        #endif

        return !HasErrors();
    }

    //-------------------------------------------------------------------------

    bool ShaderCompiler::CompileShaderStage( ReflectedShader& shader, String const& shaderStageID, ComPtr<IDxcCompiler3> &compiler, ComPtr<IDxcIncludeHandler> &includeHandler, TInlineVector<wchar_t const*, 20>& args ) const
    {
        DxcBuffer sourceBuffer = {};
        sourceBuffer.Ptr = shader.m_rawSourceText.c_str();
        sourceBuffer.Size = shader.m_rawSourceText.size();
        sourceBuffer.Encoding = 0;

        //-------------------------------------------------------------------------

        ComPtr<IDxcResult> dxcResult = {};
        if ( FAILED( compiler->Compile( &sourceBuffer, args.data(), UINT( args.size() ), includeHandler.Get(), IID_PPV_ARGS( dxcResult.ReleaseAndGetAddressOf() ) ) ) )
        {
            return LogError( "Compilation of '%s' failed", shader.m_path.c_str() );
        }

        HRESULT compileResult = S_OK;
        if ( FAILED( dxcResult->GetStatus( &compileResult ) ) )
        {
            return LogError( "Compilation of '%s' failed: unknown result", shader.m_path.c_str() );
        }

        if ( FAILED( compileResult ) )
        {
            ComPtr<IDxcBlobEncoding> errorBlob = {};
            if ( FAILED( dxcResult->GetErrorBuffer( errorBlob.ReleaseAndGetAddressOf() ) ) )
            {
                return false;
            }

            return LogError( "Compilation of '%s' failed: %hs", shader.m_path.c_str(), errorBlob->GetBufferPointer() );
        }

        // Try get warnings
        ComPtr<IDxcBlobUtf8> warningBlob;
        dxcResult->GetOutput( DXC_OUT_ERRORS, IID_PPV_ARGS( warningBlob.GetAddressOf() ), nullptr );
        if ( warningBlob && warningBlob->GetStringLength() > 0 )
        {
            LogWarning( "Compilation of '%s' succeeded with warnings: %hs", shader.m_path.c_str(), warningBlob->GetBufferPointer() );
        }

        //-------------------------------------------------------------------------

        ComPtr<IDxcBlob> compiledBlob = {};
        if ( FAILED( dxcResult->GetResult( compiledBlob.ReleaseAndGetAddressOf() ) ) )
        {
            return LogError( "Failed to retrieve compiled shader data for '%s'", shader.m_path.c_str() );
        }

        shader.m_compiledData.emplace_back( shaderStageID, static_cast<uint8_t const*>( compiledBlob->GetBufferPointer() ), compiledBlob->GetBufferSize() );

        return true;
    }

    bool ShaderCompiler::CompileMaterialShader( ReflectedShader& shader, ComPtr<IDxcCompiler3> &compiler, ComPtr<IDxcIncludeHandler> &includeHandler ) const
    {
        WString const shaderFilename( WString::CtorConvert(), shader.m_path.GetFilename().c_str() );
        WString const shaderDir( WString::CtorConvert(), shader.m_path.GetParentDirectory().c_str() );

        // MS/VS
        //-------------------------------------------------------------------------

        TInlineVector<wchar_t const*, 20> argumentsVS =
        {
            COMMON_DXC_ARGUMENTS( shaderFilename, shaderDir, m_codeDirectoryPath ),
            DXC_ARG_ENTRY_POINT( L"MS_main" ),
            DXC_ARG_TARGET( L"ms_6_6" )
        };

        if ( !CompileShaderStage( shader, "MS", compiler, includeHandler, argumentsVS ) )
        {
            return false;
        }

        shader.m_shaderStageToolMetadata.emplace_back( "MS_main", "MS", "" );

        // PS Default
        //-------------------------------------------------------------------------

        TInlineVector<wchar_t const*, 20> argumentsPS =
        {
            COMMON_DXC_ARGUMENTS( shaderFilename, shaderDir, m_codeDirectoryPath ),
            DXC_ARG_ENTRY_POINT( L"PS_main" ),
            DXC_ARG_TARGET( L"ps_6_6" ),
            DXC_ARG_DEFINE( L"PERMUTATION_DEFAULT" )
        };

        if ( !CompileShaderStage( shader, "PS_Default", compiler, includeHandler, argumentsPS ) )
        {
            return false;
        }

        shader.m_shaderStageToolMetadata.emplace_back( "PS_main", "PS", "PERMUTATION_DEFAULT;" );

        // PS AlphaTest
        //-------------------------------------------------------------------------

        TInlineVector<wchar_t const*, 20> argumentsPS_AT =
        {
            COMMON_DXC_ARGUMENTS( shaderFilename, shaderDir, m_codeDirectoryPath ),
            DXC_ARG_ENTRY_POINT( L"PS_main" ),
            DXC_ARG_TARGET( L"ps_6_6" ),
            DXC_ARG_DEFINE( L"PERMUTATION_ALPHA_TEST" )
        };

        if ( !CompileShaderStage( shader, "PS_AlphaTest", compiler, includeHandler, argumentsPS_AT ) )
        {
            return false;
        }

        shader.m_shaderStageToolMetadata.emplace_back( "PS_main", "PS", "PERMUTATION_ALPHA_TEST;" );

        // PS DepthOnly_AlphaTest
        //-------------------------------------------------------------------------

        TInlineVector<wchar_t const*, 20> argumentsPS_DO_AT =
        {
            COMMON_DXC_ARGUMENTS( shaderFilename, shaderDir, m_codeDirectoryPath ),
            DXC_ARG_ENTRY_POINT( L"PS_main" ),
            DXC_ARG_TARGET( L"ps_6_6" ),
            DXC_ARG_DEFINE( L"PERMUTATION_DEPTH_ONLY" ),
            DXC_ARG_DEFINE( L"PERMUTATION_ALPHA_TEST" )

        };

        if ( !CompileShaderStage( shader, "PS_DepthOnly_AlphaTest", compiler, includeHandler, argumentsPS_DO_AT ) )
        {
            return false;
        }

        shader.m_shaderStageToolMetadata.emplace_back( "PS_main", "PS", "PERMUTATION_DEFAULT;PERMUTATION_ALPHA_TEST;" );

        return true;
    }

    bool ShaderCompiler::CompileSurfaceShader( ReflectedShader& shader, ComPtr<IDxcCompiler3> &compiler, ComPtr<IDxcIncludeHandler> &includeHandler ) const
    {
        WString const shaderFilename( WString::CtorConvert(), shader.m_path.GetFilename().c_str() );
        WString const shaderDir( WString::CtorConvert(), shader.m_path.GetParentDirectory().c_str() );

        //-------------------------------------------------------------------------

        if ( !shader.m_useMeshShader )
        {
            TInlineVector<wchar_t const*, 20> argumentsVS =
            {
                COMMON_DXC_ARGUMENTS( shaderFilename, shaderDir, m_codeDirectoryPath ),
                DXC_ARG_ENTRY_POINT( L"VS_main" ),
                DXC_ARG_TARGET( L"vs_6_6" )
            };

            if ( !CompileShaderStage( shader, "VS", compiler, includeHandler, argumentsVS ) )
            {
                return false;
            }

            shader.m_shaderStageToolMetadata.emplace_back( "VS_main", "VS", "" );
        }
        else
        {
            TInlineVector<wchar_t const*, 20> argumentsMS =
            {
                COMMON_DXC_ARGUMENTS( shaderFilename, shaderDir, m_codeDirectoryPath ),
                DXC_ARG_ENTRY_POINT( L"MS_main" ),
                DXC_ARG_TARGET( L"ms_6_6" )
            };

            if ( !CompileShaderStage( shader, "MS", compiler, includeHandler, argumentsMS ) )
            {
                return false;
            }

            shader.m_shaderStageToolMetadata.emplace_back( "MS_main", "MS", "" );

            if ( shader.m_useTaskShader )
            {
                TInlineVector<wchar_t const*, 20> argumentsTS =
                {
                    COMMON_DXC_ARGUMENTS( shaderFilename, shaderDir, m_codeDirectoryPath ),
                    DXC_ARG_ENTRY_POINT( L"TS_main" ),
                    DXC_ARG_TARGET( L"as_6_6" )
                };

                if ( !CompileShaderStage( shader, "TS", compiler, includeHandler, argumentsTS ) )
                {
                    return false;
                }

                shader.m_shaderStageToolMetadata.emplace_back( "TS_main", "TS", "" );
            }
        }

        //-------------------------------------------------------------------------

        TInlineVector<wchar_t const*, 20> argumentsPS =
        {
            COMMON_DXC_ARGUMENTS( shaderFilename, shaderDir, m_codeDirectoryPath ),
            DXC_ARG_ENTRY_POINT( L"PS_main" ),
            DXC_ARG_TARGET( L"ps_6_6" )
        };

        if ( !CompileShaderStage( shader, "PS", compiler, includeHandler, argumentsPS ) )
        {
            return false;
        }

        shader.m_shaderStageToolMetadata.emplace_back( "PS_main", "PS", "" );

        return true;
    }

    bool ShaderCompiler::CompileComputeShader( ReflectedShader& shader, ComPtr<IDxcCompiler3> &compiler, ComPtr<IDxcIncludeHandler> &includeHandler ) const
    {
        DxcBuffer sourceBuffer = {};
        sourceBuffer.Ptr = shader.m_rawSourceText.c_str();
        sourceBuffer.Size = shader.m_rawSourceText.size();
        sourceBuffer.Encoding = 0;

        //-------------------------------------------------------------------------

        WString const shaderFilename( WString::CtorConvert(), shader.m_path.GetFilename().c_str() );
        WString const shaderDir( WString::CtorConvert(), shader.m_path.GetParentDirectory().c_str() );

        TInlineVector<wchar_t const*, 20> dxcArguments =
        {
            COMMON_DXC_ARGUMENTS( shaderFilename, shaderDir, m_codeDirectoryPath ),
            DXC_ARG_ENTRY_POINT( L"CS_main" ),
            DXC_ARG_TARGET( L"cs_6_6" )
        };

        if ( !CompileShaderStage( shader, "CS", compiler, includeHandler, dxcArguments ) )
        {
            return false;
        }

        shader.m_shaderStageToolMetadata.emplace_back( "CS_main", "CS", "" );

        return true;
    }

    void ShaderCompiler::CompilationTask( TaskSetPartition range, uint32_t threadNum )
    {
        ComPtr<IDxcUtils> dxcUtils = {};
        HRESULT hr = DxcCreateInstance( CLSID_DxcUtils, IID_PPV_ARGS( dxcUtils.ReleaseAndGetAddressOf() ) );
        if ( FAILED( hr ) )
        {
            LogError( "DXC utils creation failed with hr = %d", hr );
            return;
        }

        ComPtr<IDxcIncludeHandler> dxcIncludeHandler = {};
        hr = dxcUtils->CreateDefaultIncludeHandler( dxcIncludeHandler.ReleaseAndGetAddressOf() );
        if ( FAILED( hr ) )
        {
            LogError( "DXC Include handler creation failed with hr = %d", hr );
            return;
        }

        ComPtr<IDxcCompiler3> dxcCompiler = {};
        hr = DxcCreateInstance( CLSID_DxcCompiler, IID_PPV_ARGS( dxcCompiler.ReleaseAndGetAddressOf() ) );
        if ( FAILED( hr ) )
        {
            LogError( "DXC compiler creation failed with hr = %d", hr );
            return;
        }

        // Compile all shaders in range
        //-------------------------------------------------------------------------

        for ( uint32_t i = range.start; i < range.end; i++ )
        {
            ReflectedShader& shader = *m_shadersToCompile[i].m_pShader;

            bool shaderCompilationSuccess = false;

            switch ( shader.m_type )
            {
                case Render::ShaderType::Material:
                {
                    shaderCompilationSuccess = CompileMaterialShader( shader, dxcCompiler, dxcIncludeHandler );
                }
                break;

                case Render::ShaderType::Surface:
                {
                    shaderCompilationSuccess = CompileSurfaceShader( shader, dxcCompiler, dxcIncludeHandler );
                }
                break;

                case Render::ShaderType::Compute:
                {
                    shaderCompilationSuccess = CompileComputeShader( shader, dxcCompiler, dxcIncludeHandler );
                }
                break;

                default:
                {
                    EE_UNREACHABLE_CODE();
                    return;
                }
                break;
            }

            // Early out on failure
            if ( !shaderCompilationSuccess )
            {
                return;
            }
        }
    }
}