#include "ShaderReflection_CodeGenerator.h"
#include "Applications/Reflector/Reflector.h"
#include "Base/ThirdParty/lzav/lzav.h"
#include "Base/Encoding/Encoding.h"
#include "Base/Serialization/XmlSerialization.h"
#include "Base/ThirdParty/pugixml/src/pugixml.hpp"
#include "Base/FileSystem/FileSystem.h"

#include <sstream>

//-------------------------------------------------------------------------

namespace EE::Reflection
{
    bool ShaderCodeGenerator::GenerateCodeForSolution()
    {
        for ( ReflectedProject const& project : m_reflector.GetProjects() )
        {
            if ( project.m_isExcludedFromShaderReflection )
            {
                continue;
            }

            // Generate Shader Files
            //-------------------------------------------------------------------------

            for ( ReflectedShader const& shader : project.m_shaders )
            {
                // Write shader parameter struct - needed for typeinfo reflection
                if ( shader.m_type == Render::ShaderType::Material )
                {
                    GenerateReflectedParametersFile( project, shader );
                }

                // Write compiled shader byte code
                GenerateShaderFile( project, shader );
            }
        }

        // Generate Project Registration File
        //-------------------------------------------------------------------------

        GenerateShaderRegistrationFiles();

        //-------------------------------------------------------------------------

        GenerateXML();

        //-------------------------------------------------------------------------

        return !HasErrors();
    }

    bool ShaderCodeGenerator::GenerateReflectedParametersFile( ReflectedProject const& project, ReflectedShader const& shader )
    {
        std::stringstream stream;
        stream.str( std::string() );
        stream.clear();
        CreateAutogeneratedHeader( stream, shader.m_path );

        // Includes
        //-------------------------------------------------------------------------

        stream << "#pragma once\n\n";

        stream << "#include \"Base/TypeSystem/ReflectedType.h\"\n";
        stream << "#include \"Base/Types/BitFlags.h\"\n";
        stream << "#include \"Base/Resource/ResourcePtr.h\"\n";
        stream << "#include \"Base/Render/RHI.esh\"\n";
        stream << "#include \"Engine/Render/Shaders/EngineShader.h\"\n";
        stream << "#include \"Engine/Render/RenderTexture.h\"\n";

        // Namespace
        //-------------------------------------------------------------------------

        stream << "\n//-------------------------------------------------------------------------\n\n";
        stream << "namespace EE::Render::Shaders\n";
        stream << "{";

        // Parameter struct
        //-------------------------------------------------------------------------

        stream << "\n";
        stream << "    struct " << shader.m_name.c_str() << "Parameters : public IReflectedType\n";
        stream << "    {\n";
        stream << "        EE_REFLECT_TYPE( " << shader.m_name.c_str() << "Parameters );\n\n";
        stream << "    public:\n";

        for ( ReflectedShader::ParameterInfo const& parameterInfo : shader.m_parameters )
        {
            if ( parameterInfo.m_type == "esf_padding_t" )
            {
                // Don't care about the padding or reserved fields
                continue;
            }

            if ( parameterInfo.m_name == "m_shaderIndex" )
            {
                // Special case, filled at runtime
                continue;
            }

            //-------------------------------------------------------------------------

            if ( parameterInfo.m_type == "Texture1D" || parameterInfo.m_type == "Texture2D" || parameterInfo.m_type == "Texture3D" || parameterInfo.m_type == "TextureCube" )
            {
                stream << "\n";
                stream << "        EE_REFLECT();\n";
                stream << "        TResourcePtr<TextureResource> " << parameterInfo.m_name.c_str();

                // Add annotation data
                for ( auto const& annotation : parameterInfo.m_annotations )
                {
                    if ( annotation.m_type == "ESF_DEFAULT_VALUE" )
                    {
                        stream << " = ResourceID( " << annotation.m_value.c_str() << " )";
                    }
                }

                stream << ";\n";
            }
            else if ( parameterInfo.m_isHandle )
            {
                // TODO: Not implemented in the UI yet.
            }
            else // Other types
            {
                stream << "\n";
                stream << "        EE_REFLECT();\n";
                stream << "        " << parameterInfo.m_type.c_str() << " " << parameterInfo.m_name.c_str();

                // Add annotation data
                for ( auto const& annotation : parameterInfo.m_annotations )
                {
                    if ( annotation.m_type == "ESF_DEFAULT_VALUE" )
                    {
                        stream << " = " << annotation.m_value.c_str();
                    }
                }

                stream << ";\n";
            }
        }

        stream << "    };\n";

        // Namespace
        //-------------------------------------------------------------------------

        stream << "}";

        // File
        //-------------------------------------------------------------------------

        m_reflector.AddGeneratedFile( shader.m_reflectedParametersFilePath, stream.str().c_str() );

        return true;
    }

    bool ShaderCodeGenerator::GenerateShaderFile( ReflectedProject const& project, ReflectedShader const& shader )
    {
        std::stringstream stream;
        stream.str( std::string() );
        stream.clear();
        CreateAutogeneratedHeader( stream, shader.m_path );

        // Includes
        //-------------------------------------------------------------------------

        stream << "#include \"Engine/Render/Shaders/EngineShader.h\"\n";

        // Namespace
        //-------------------------------------------------------------------------

        stream << "\n//-------------------------------------------------------------------------\n\n";
        stream << "namespace EE::Render::Shaders\n";
        stream << "{";

        // Byte code
        //-------------------------------------------------------------------------

        stream << "\n";
        stream << "    // LZAV Compressed Byte Code in Base85\n";
        stream << "    //-------------------------------------------------------------------------\n";

        TVector<uint8_t> compressedData;

        for ( ReflectedShader::CompiledData const& cd : shader.m_compiledData )
        {
            EE_ASSERT( !shader.m_name.empty() );

            int32_t const maxSize = lzav_compress_bound_hi( int32_t( cd.m_byteCode.size() ) );
            compressedData.resize( maxSize );
            int32_t const compressedSize = lzav_compress_hi( cd.m_byteCode.data(), compressedData.data(), int32_t( cd.m_byteCode.size() ), int32_t( compressedData.size() ) );
            compressedData.resize( compressedSize );

            if ( compressedSize == 0 )
            {
                LogError( "Failed to compress shader data: %s", shader.m_name.c_str() );
                return false;
            }

            int32_t const strLength = ( ( compressedSize + 3 ) / 4 ) * 5;
            uint32_t const decodedDataSize = uint32_t( ( strLength + 4 ) / 5 ) * 4;
            uint32_t const encodedSize = strLength + 1;

            InlineString const rawDataVariableName = cd.GetCompileByteCodeVariableName( shader.m_name );
            stream << std::endl << "    constexpr uint32_t " << rawDataVariableName.c_str() << "_decompressedSize = " << cd.m_byteCode.size() << ";" << std::endl;
            stream << std::endl << "    constexpr uint32_t " << rawDataVariableName.c_str() << "_decodedSize = " << decodedDataSize << ";" << std::endl;
            stream << std::endl << "    constexpr uint32_t " << rawDataVariableName.c_str() << "_compressedSize = " << encodedSize << ";" << std::endl;
            stream << std::endl << "    static char const " << rawDataVariableName.c_str() << "[" << encodedSize << "] =" << std::endl;
            stream << "    {" << std::endl << "        \"";

            for ( int32_t src_i = 0; src_i < compressedSize; src_i += 4 )
            {
                uint32_t d = *(uint32_t*) ( compressedData.data() + src_i );
                for ( uint32_t n5 = 0; n5 < 5; n5++, d /= 85 )
                {
                    stream << Encoding::Base85::EncodeByte( d );
                }

                if ( ( src_i % 112 ) == 112 - 4 )
                {
                    stream << "\"" << std::endl << "        \"";
                }
            }

            stream << "\"";
            stream << "    };" << std::endl;
        }

        // Registration Code
        //-------------------------------------------------------------------------

        stream << std::endl;
        stream << "    // Registration Code\n";
        stream << "    //-------------------------------------------------------------------------\n\n";

        stream << "    void Register_" << shader.m_name.c_str() << "( RHI::Context* pContextRHI, TVector<MaterialShader>& materialShaders, TVector<SurfaceShader>& surfaceShaders, TVector<ComputeShader>& computeShaders )\n";
        stream << "    {" << std::endl;;
        stream << "        ByteCodeList shaderByteCodeParameters;" << std::endl;

        switch ( shader.m_type )
        {
            case Render::ShaderType::Material:
            {
                if ( !GenerateMaterialShaderRegistration( stream, shader ) )
                {
                    return false;
                }
            }
            break;

            case Render::ShaderType::Surface:
            {
                if ( !GenerateSurfaceShaderRegistration( stream, shader ) )
                {
                    return false;
                }
            }
            break;

            case Render::ShaderType::Compute:
            {
                if ( !GenerateComputeShaderRegistration( stream, shader ) )
                {
                    return false;
                }
            }
            break;
        }

        stream << "    }" << std::endl;

        // Namespace
        //-------------------------------------------------------------------------

        stream << "}";

        // File
        //-------------------------------------------------------------------------

        m_reflector.AddGeneratedFile( shader.m_compiledShaderPath, stream.str().c_str() );

        return true;
    }

    bool ShaderCodeGenerator::GenerateShaderRegistrationFiles()
    {
        //-------------------------------------------------------------------------
        // Header File
        //-------------------------------------------------------------------------

        {
            std::stringstream stream;
            stream.str( std::string() );
            stream.clear();
            CreateAutogeneratedHeader( stream );

            //------------------------------------------------------------------------- 

            stream << "#pragma once" << "\n\n";
            stream << "#include \"Engine/Render/Shaders/EngineShader.h\"\n";
            stream << "#include \"Base/Render/RHI.h\"\n\n";

            stream << "//-------------------------------------------------------------------------\n\n";
            stream << "namespace EE::Render::Shaders\n";
            stream << "{\n";
            stream << "    void Initialize( RHI::Context* pContextRHI, TVector<MaterialShader>& materialShaders, TVector<SurfaceShader>& surfaceShaders, TVector<ComputeShader>& computeShaders );\n\n";
            stream << "    //-------------------------------------------------------------------------\n\n";

            //-------------------------------------------------------------------------

            for ( ReflectedProject const& project : m_reflector.GetProjects() )
            {
                for ( ReflectedShader const& shader : project.m_shaders )
                {
                    stream << "    void Register_" << shader.m_name.c_str() << "( RHI::Context* pContextRHI, TVector<MaterialShader>& materialShaders, TVector<SurfaceShader>& surfaceShaders, TVector<ComputeShader>& computeShaders );\n";
                }
            }

            //-------------------------------------------------------------------------

            stream << "}";

            //-------------------------------------------------------------------------

            m_reflector.AddGeneratedFile( m_reflector.GetShaderRegistrationHeaderFilePath(), stream.str().c_str() );
        }

        //-------------------------------------------------------------------------
        // Source File
        //-------------------------------------------------------------------------

        {
            std::stringstream stream;
            stream.str( std::string() );
            stream.clear();
            CreateAutogeneratedHeader( stream );

            // Includes
            //-------------------------------------------------------------------------

            stream << "#pragma once\n\n";
            stream << "#include \"" << Settings::g_shaderRegistrationFileNameNoExtension << ".h\"\n\n";
            stream << "//-------------------------------------------------------------------------\n\n";

            // Namespace
            //-------------------------------------------------------------------------

            stream << "namespace EE::Render::Shaders\n";
            stream << "{\n";
            stream << "    // Shader Registration\n";
            stream << "    //-------------------------------------------------------------------------\n\n";

            stream << "    void Initialize( RHI::Context* pContextRHI, TVector<MaterialShader>& materialShaders, TVector<SurfaceShader>& surfaceShaders, TVector<ComputeShader>& computeShaders )\n";
            stream << "    {\n";

            for ( ReflectedProject const& project : m_reflector.GetProjects() )
            {
                for ( ReflectedShader const& shader : project.m_shaders )
                {
                    stream << "        Register_" << shader.m_name.c_str() << "( pContextRHI, materialShaders, surfaceShaders, computeShaders );\n";
                }
            }

            stream << "    }\n";

            // Namespace
            //-------------------------------------------------------------------------

            stream << "}";

            // File
            //-------------------------------------------------------------------------

            m_reflector.AddGeneratedFile( m_reflector.GetShaderRegistrationSourceFilePath(), stream.str().c_str() );
        }

        return true;
    }

    static char const* GetShaderStageString( Render::RHI::ShaderStage stage )
    {
        static char const* names[] =
        {
            "RHI::ShaderStage::Vertex",
            "RHI::ShaderStage::Pixel",
            "RHI::ShaderStage::Task",
            "RHI::ShaderStage::Mesh",
            "RHI::ShaderStage::Compute",
            "RHI::ShaderStage::RayTracing"
        };

        return names[(int32_t) stage];
    };

    bool ShaderCodeGenerator::GenerateMaterialShaderRegistration( std::stringstream& stream, ReflectedShader const& shader )
    {
        stream << "        shaderByteCodeParameters.clear();\n";
        for ( auto const & cd : shader.m_compiledData )
        {
            InlineString const viewVariableName = cd.GetCompileByteCodeVariableName( shader.m_name );
            stream
                << "        shaderByteCodeParameters.emplace_back( RHI::ShaderByteCode( "
                << GetShaderStageString( cd.GetStage() ) << ", StringID( \"" << cd.m_ID.c_str()
                << "\" ), " << viewVariableName.c_str() << ", "
                << viewVariableName.c_str() << "_decompressedSize, "
                << viewVariableName.c_str() << "_decodedSize ) );\n";
        }

        stream << "\n";
        stream << "        MaterialShader* pCreatedShader = &materialShaders.emplace_back( MaterialShader( pContextRHI, StringID( \"" << shader.m_name.c_str() << "\" ), shaderByteCodeParameters ) );\n";
        stream << "        pCreatedShader->m_allowBufferWritesInPixelShader = " << ( shader.m_allowBufferWritesInPixelShader ? "true" : "false" ) << ";\n";
        stream << "        pCreatedShader->m_showInResourceEditor = " << ( shader.m_showInResourceEditor ? "true" : "false" ) << ";\n";

        if ( !shader.m_customParametersStructName.empty() )
        {
            stream << "        pCreatedShader->m_parametersStructName = StringID( \"" << shader.m_customParametersStructName.c_str() << "\" );\n";
        }

        for ( ReflectedShader::ParameterInfo const& parameterInfo : shader.m_parameters )
        {
            stream << "        pCreatedShader->m_parameterInfo.emplace_back( StringID( \"" << parameterInfo.m_type.c_str() << "\" ), StringID( \"" << parameterInfo.m_name.c_str() << "\" ), " << parameterInfo.m_strideInBytes << ", " << parameterInfo.m_offsetInBytes << " );\n";
        }

        return true;
    }

    bool ShaderCodeGenerator::GenerateSurfaceShaderRegistration( std::stringstream& stream, ReflectedShader const& shader )
    {
        stream << "        shaderByteCodeParameters.clear();\n";
        for ( auto const & cd : shader.m_compiledData )
        {
            InlineString const viewVariableName = cd.GetCompileByteCodeVariableName( shader.m_name );
            stream
                << "        shaderByteCodeParameters.emplace_back( RHI::ShaderByteCode( "
                << GetShaderStageString( cd.GetStage() ) << ", StringID( \"" << cd.m_ID.c_str()
                << "\" ), " << viewVariableName.c_str() << ", "
                << viewVariableName.c_str() << "_decompressedSize, "
                << viewVariableName.c_str() << "_decodedSize ) );\n";
        }

        stream << "        surfaceShaders.emplace_back( SurfaceShader( pContextRHI, StringID( \"" << shader.m_name.c_str() << "\" ), shaderByteCodeParameters ) );\n";

        return true;
    }

    bool ShaderCodeGenerator::GenerateComputeShaderRegistration( std::stringstream& stream, ReflectedShader const& shader )
    {
        stream << "        shaderByteCodeParameters.clear();\n";
        for ( auto const & cd : shader.m_compiledData )
        {
            InlineString const viewVariableName = cd.GetCompileByteCodeVariableName( shader.m_name );
            stream
                << "        shaderByteCodeParameters.emplace_back( RHI::ShaderByteCode( "
                << GetShaderStageString( cd.GetStage() ) << ", StringID( \"" << cd.m_ID.c_str()
                << "\" ), " << viewVariableName.c_str() << ", "
                << viewVariableName.c_str() << "_decompressedSize, "
                << viewVariableName.c_str() << "_decodedSize ) );\n";
        }

        stream << "        computeShaders.emplace_back( ComputeShader( pContextRHI, StringID( \"" << shader.m_name.c_str() << "\" ), shaderByteCodeParameters ) );\n";

        return true;
    }

    //-------------------------------------------------------------------------
    // XML
    //-------------------------------------------------------------------------

    using namespace pugi;

    void ShaderCodeGenerator::GenerateXML()
    {
        xml_document doc;

        xml_node decl = doc.append_child( node_declaration );
        decl.append_attribute( "version" ) = "1.0";
        decl.append_attribute( "encoding" ) = "UTF-8";

        //-------------------------------------------------------------------------

        xml_node headerComment = doc.append_child( node_comment );
        headerComment.set_value( "Esoterica Shader Stage Metadata" );

        headerComment = doc.append_child( node_comment );
        headerComment.set_value( "This is an autogenerated file - DO NOT edit" );

        //-------------------------------------------------------------------------

        xml_node rootNode = doc.root().append_child( "CompiledShaderStages" );

        for ( ReflectedProject const& project : m_reflector.GetProjects() )
        {
            if ( project.m_isExcludedFromShaderReflection )
            {
                continue;
            }

            for ( ReflectedShader const& shader : project.m_shaders )
            {
                for ( ReflectedShader::StageToolMetadata const& stageToolMetadata : shader.m_shaderStageToolMetadata )
                {
                    xml_node compiledShader = rootNode.append_child( "CompiledShader" );
                    compiledShader.append_attribute( "Name" ).set_value( shader.m_name.c_str() );
                    compiledShader.append_attribute( "FilePath" ).set_value( shader.m_path.c_str() );
                    compiledShader.append_attribute( "EntryPoint" ).set_value( stageToolMetadata.m_pEntryPoint );
                    compiledShader.append_attribute( "Stage" ).set_value( stageToolMetadata.m_pStage );
                    compiledShader.append_attribute( "CommandLineDXC" ).set_value( "-HV 2021 -enable-16bit-types" );

                    TVector<String> macroDefinitions;
                    StringUtils::Split( String( stageToolMetadata.m_pMacroDefinitions ), macroDefinitions, ";" );

                    for ( String const& name : macroDefinitions )
                    {
                        xml_node macro = compiledShader.append_child( "MacroDefinition" );
                        macro.append_attribute( "Name" ).set_value( name.c_str() );
                        macro.append_attribute( "Value" ).set_value( "1" );
                    }
                }
            }
        }

        std::stable_sort( doc.begin(), doc.end(), [] ( xml_node node0, xml_node node1 )
        {
            return stricmp( node0.attribute( "Name" ).as_string(), node1.attribute( "Name" ).as_string() );
        } );

        //-------------------------------------------------------------------------

        String fileContents;
        Serialization::WriteXmlToString( doc, fileContents );
        m_reflector.AddGeneratedFile( m_reflector.GetShaderMetadataXMLFilePath(), fileContents.c_str() );
    }
}