#include "DeviceRadixSort.h"
#include "Engine/Render/RenderSystem.h"

#include <EASTL/utility.h>

#include "Base/Render/RHI.esh"

#define FFX_CPP
#include "../Shaders/FFX/FFX_ParallelSort.esh"

// Auto-generated resource table reflection headers
#include "Engine/_Module/_AutoGenerated/ShaderReflection/FFX_ParallelSort_SetupIndirect.esh"
#include "Engine/_Module/_AutoGenerated/ShaderReflection/FFX_ParallelSort_Count.esh"
#include "Engine/_Module/_AutoGenerated/ShaderReflection/FFX_ParallelSort_Reduce.esh"
#include "Engine/_Module/_AutoGenerated/ShaderReflection/FFX_ParallelSort_Scan.esh"
#include "Engine/_Module/_AutoGenerated/ShaderReflection/FFX_ParallelSort_ScanAdd.esh"
#include "Engine/_Module/_AutoGenerated/ShaderReflection/FFX_ParallelSort_Scatter.esh"
#include "Engine/_Module/_AutoGenerated/ShaderReflection/FFX_ParallelSort_ScatterPayload.esh"

// Shared indirect argument record definitions ( CPU + GPU )
#include "../Shaders/FFX/FFX_ParallelSort_SetupIndirect.esf"

namespace EE::Render
{
    void DeviceRadixSort::Initialize( RHI::Context* pContextRHI, RenderSystem* pRenderSystem )
    {
        EE_ASSERT( !m_pConstantBuffer );

        m_pContextRHI = pContextRHI;
        m_pRenderSystem = pRenderSystem;

        m_scratchBuffer.Initialize( pContextRHI, false );
        m_reducedScratchBuffer.Initialize( pContextRHI, false );

        m_pSetupIndirectShader = pRenderSystem->FindComputeShader( StringID( "FFX_ParallelSort_SetupIndirect" ) );
        m_pCountShader = pRenderSystem->FindComputeShader( StringID( "FFX_ParallelSort_Count" ) );
        m_pReduceShader = pRenderSystem->FindComputeShader( StringID( "FFX_ParallelSort_Reduce" ) );
        m_pScanShader = pRenderSystem->FindComputeShader( StringID( "FFX_ParallelSort_Scan" ) );
        m_pScanAddShader = pRenderSystem->FindComputeShader( StringID( "FFX_ParallelSort_ScanAdd" ) );
        m_pScatterShader = pRenderSystem->FindComputeShader( StringID( "FFX_ParallelSort_Scatter" ) );
        m_pScatterPayloadShader = pRenderSystem->FindComputeShader( StringID( "FFX_ParallelSort_ScatterPayload" ) );

        static_assert( sizeof( ShaderTypes::FFX_ParallelSort_CountIndirectArgument ) % RHI::g_indirectCommandAlignment == 0, "Indirect argument stride must be a multiple of g_indirectCommandAlignment" );
        static_assert( sizeof( ShaderTypes::FFX_ParallelSort_ReduceIndirectArgument ) % RHI::g_indirectCommandAlignment == 0, "Indirect argument stride must be a multiple of g_indirectCommandAlignment" );
        static_assert( sizeof( ShaderTypes::FFX_ParallelSort_ScanAddIndirectArgument ) % RHI::g_indirectCommandAlignment == 0, "Indirect argument stride must be a multiple of g_indirectCommandAlignment" );
        static_assert( sizeof( ShaderTypes::FFX_ParallelSort_ScatterIndirectArgument ) % RHI::g_indirectCommandAlignment == 0, "Indirect argument stride must be a multiple of g_indirectCommandAlignment" );
        static_assert( sizeof( ShaderTypes::FFX_ParallelSort_ScatterPayloadIndirectArgument ) % RHI::g_indirectCommandAlignment == 0, "Indirect argument stride must be a multiple of g_indirectCommandAlignment" );

        uint32_t const counterArgumentStride = sizeof( ShaderTypes::FFX_ParallelSort_CountIndirectArgument );
        uint32_t const reduceArgumentStride = sizeof( ShaderTypes::FFX_ParallelSort_ReduceIndirectArgument );
        uint32_t const scanAddArgumentStride = sizeof( ShaderTypes::FFX_ParallelSort_ScanAddIndirectArgument );
        uint32_t const scatterArgumentStride = sizeof( ShaderTypes::FFX_ParallelSort_ScatterIndirectArgument );
        uint32_t const scatterPayloadArgumentStride = sizeof( ShaderTypes::FFX_ParallelSort_ScatterPayloadIndirectArgument );

        RHI::BufferParameters constantBufferParameters = {};
        constantBufferParameters.m_bufferSize = sizeof( FFX_ParallelSortCB );
        constantBufferParameters.m_bufferStride = sizeof( uint32_t );
        constantBufferParameters.m_descriptorTypes = { RHI::DescriptorTypeFlags::ConstantBuffer, RHI::DescriptorTypeFlags::RWBuffer };
        constantBufferParameters.m_debugName = "DeviceRadixSort CB";
        m_pConstantBuffer = RHI::CreateBuffer( pContextRHI, constantBufferParameters );

        auto CreateArgumentsBuffer = [pContextRHI] ( char const* pDebugName, uint32_t argumentStride, uint32_t numArguments )
        {
            RHI::BufferParameters argumentsBufferParameters = {};
            argumentsBufferParameters.m_bufferSize = argumentStride * numArguments;
            argumentsBufferParameters.m_bufferStride = argumentStride;
            argumentsBufferParameters.m_alignment = RHI::g_indirectCommandAlignment;
            argumentsBufferParameters.m_descriptorTypes = { RHI::DescriptorTypeFlags::IndirectArgumentBuffer, RHI::DescriptorTypeFlags::RWBuffer };
            argumentsBufferParameters.m_debugName = pDebugName;
            return RHI::CreateBuffer( pContextRHI, argumentsBufferParameters );
        };

        m_pCountArgumentsBuffer = CreateArgumentsBuffer( "DeviceRadixSort Count Args", counterArgumentStride, 8 );
        m_pReduceArgumentsBuffer = CreateArgumentsBuffer( "DeviceRadixSort Reduce Args", reduceArgumentStride, 1 );
        m_pScanAddArgumentsBuffer = CreateArgumentsBuffer( "DeviceRadixSort ScanAdd Args", scanAddArgumentStride, 1 );
        m_pScatterArgumentsBuffer = CreateArgumentsBuffer( "DeviceRadixSort Scatter Args", scatterArgumentStride, 8 );
        m_pScatterPayloadArgumentsBuffer = CreateArgumentsBuffer( "DeviceRadixSort ScatterPayload Args", scatterPayloadArgumentStride, 8 );
    }

    void DeviceRadixSort::Shutdown( RHI::Context* pContextRHI )
    {
        RHI::DestroyBuffer( pContextRHI, eastl::move( m_pConstantBuffer ) );
        RHI::DestroyBuffer( pContextRHI, eastl::move( m_pCountArgumentsBuffer ) );
        RHI::DestroyBuffer( pContextRHI, eastl::move( m_pReduceArgumentsBuffer ) );
        RHI::DestroyBuffer( pContextRHI, eastl::move( m_pScanAddArgumentsBuffer ) );
        RHI::DestroyBuffer( pContextRHI, eastl::move( m_pScatterArgumentsBuffer ) );
        RHI::DestroyBuffer( pContextRHI, eastl::move( m_pScatterPayloadArgumentsBuffer ) );

        m_scratchBuffer.Shutdown( pContextRHI );
        m_reducedScratchBuffer.Shutdown( pContextRHI );
        m_maxNumKeys = 0;
    }

    void DeviceRadixSort::UpdateDeviceResources( uint32_t numKeys )
    {
        if ( numKeys <= m_maxNumKeys )
        {
            return;
        }

        numKeys = Math::Max( numKeys, 64U );
        m_maxNumKeys = numKeys;

        uint32_t scratchSize = 0;
        uint32_t reducedScratchSize = 0;
        FFX_ParallelSort_CalculateScratchResourceSize( numKeys, scratchSize, reducedScratchSize );

        m_scratchBuffer.UpdateDeviceResources( scratchSize, [&] ( RHI::Buffer* pOldBuffer, size_t newSize )
        {
            m_pRenderSystem->QueueResourceDelete( pOldBuffer );

            RHI::BufferParameters bp = {};
            bp.m_bufferSize = newSize;
            bp.m_bufferStride = sizeof( uint32_t );
            bp.m_descriptorTypes = RHI::DescriptorTypeFlags::RWBuffer;
            bp.m_debugName = "DeviceRadixSort Scratch";
            return RHI::CreateBuffer( m_pContextRHI, bp );
        } );

        m_reducedScratchBuffer.UpdateDeviceResources( reducedScratchSize, [&] ( RHI::Buffer* pOldBuffer, size_t newSize )
        {
            m_pRenderSystem->QueueResourceDelete( pOldBuffer );

            RHI::BufferParameters reducedScratchBufferParameters = {};
            reducedScratchBufferParameters.m_bufferSize = newSize;
            reducedScratchBufferParameters.m_bufferStride = sizeof( uint32_t );
            reducedScratchBufferParameters.m_descriptorTypes = RHI::DescriptorTypeFlags::RWBuffer;
            reducedScratchBufferParameters.m_debugName = "DeviceRadixSort Reduced Scratch";
            return RHI::CreateBuffer( m_pContextRHI, reducedScratchBufferParameters );
        } );
    }

    void DeviceRadixSort::DispatchSorting
    (
        RHI::CommandBuffer* pCommandBuffer,
        RHI::Buffer* pSrcKeys, RHI::Buffer* pDstKeys, RHI::Buffer* pNumKeysBuffer, uint32_t maxNumKeys, uint32_t numSortBits
    )
    {
        DispatchSorting( pCommandBuffer, pSrcKeys, pDstKeys, nullptr, nullptr, pNumKeysBuffer, maxNumKeys, numSortBits );
    }

    void DeviceRadixSort::DispatchSorting
    (
        RHI::CommandBuffer* pCommandBuffer,
        RHI::Buffer* pSrcKeys, RHI::Buffer* pDstKeys,
        RHI::Buffer* pSrcPayload, RHI::Buffer* pDstPayload,
        RHI::Buffer* pNumKeysBuffer, uint32_t maxNumKeys, uint32_t numSortBits
    )
    {
        EE_ASSERT( maxNumKeys <= m_maxNumKeys );
        EE_ASSERT( numSortBits >= 1 && numSortBits <= 32 );
        EE_ASSERT( m_scratchBuffer.m_pBuffer );
        EE_ASSERT( m_reducedScratchBuffer.m_pBuffer );
        EE_ASSERT( pSrcKeys );
        EE_ASSERT( pDstKeys );
        EE_ASSERT( pNumKeysBuffer );

        bool const hasPayload = pSrcPayload != nullptr;

        RHI::Buffer* pScratch = m_scratchBuffer.m_pBuffer;
        RHI::Buffer* pReduced = m_reducedScratchBuffer.m_pBuffer;

        RHI::Buffer* pConstantBuffer = m_pConstantBuffer;
        RHI::Buffer* pCountArgumentsBuffer = m_pCountArgumentsBuffer;
        RHI::Buffer* pReduceArgumentsBuffer = m_pReduceArgumentsBuffer;
        RHI::Buffer* pScanAddArgumentsBuffer = m_pScanAddArgumentsBuffer;
        RHI::Buffer* pScatterArgumentsBuffer = m_pScatterArgumentsBuffer;
        RHI::Buffer* pScatterPayloadArgumentsBuffer = m_pScatterPayloadArgumentsBuffer;

        uint32_t const countArgumentStride = sizeof( ShaderTypes::FFX_ParallelSort_CountIndirectArgument );
        uint32_t const scatterArgumentStride = sizeof( ShaderTypes::FFX_ParallelSort_ScatterIndirectArgument );
        uint32_t const scatterPayloadArgumentStride = sizeof( ShaderTypes::FFX_ParallelSort_ScatterPayloadIndirectArgument );

        // Compute the sort constants and indirect dispatch arguments on the GPU
        {
            uint16_t const keysAHandle = RHI::GetBufferHandle( pSrcKeys, RHI::DescriptorTypeFlags::RWBuffer );
            uint16_t const keysBHandle = RHI::GetBufferHandle( pDstKeys, RHI::DescriptorTypeFlags::RWBuffer );
            uint16_t const scratchHandle = RHI::GetBufferHandle( pScratch, RHI::DescriptorTypeFlags::RWBuffer );
            uint16_t const reducedHandle = RHI::GetBufferHandle( pReduced, RHI::DescriptorTypeFlags::RWBuffer );
            uint16_t const payloadAHandle = hasPayload ? RHI::GetBufferHandle( pSrcPayload, RHI::DescriptorTypeFlags::RWBuffer ) : 0;
            uint16_t const payloadBHandle = hasPayload ? RHI::GetBufferHandle( pDstPayload, RHI::DescriptorTypeFlags::RWBuffer ) : 0;

            ShaderTypes::FFX_ParallelSort_SetupIndirectResourceTableData setupIndirectResourceTable = {};
            setupIndirectResourceTable.m_maxThreadGroups = m_maxThreadGroups;
            setupIndirectResourceTable.SetRootCBVAddress( pConstantBuffer->m_deviceAddress );
            setupIndirectResourceTable.SetNumKeysBuffer( pNumKeysBuffer );
            setupIndirectResourceTable.SetConstantsBuffer( pConstantBuffer );
            setupIndirectResourceTable.SetCountArguments( pCountArgumentsBuffer );
            setupIndirectResourceTable.SetReduceArguments( pReduceArgumentsBuffer );
            setupIndirectResourceTable.SetScanAddArguments( pScanAddArgumentsBuffer );
            setupIndirectResourceTable.SetScatterArguments( pScatterArgumentsBuffer );
            setupIndirectResourceTable.SetScatterPayloadArgs( pScatterPayloadArgumentsBuffer );
            setupIndirectResourceTable.SetKeysAHandle( keysAHandle );
            setupIndirectResourceTable.SetKeysBHandle( keysBHandle );
            setupIndirectResourceTable.SetPayloadAHandle( payloadAHandle );
            setupIndirectResourceTable.SetPayloadBHandle( payloadBHandle );
            setupIndirectResourceTable.SetScratchHandle( scratchHandle );
            setupIndirectResourceTable.SetReducedHandle( reducedHandle );

            RHI::CmdSetPipeline( pCommandBuffer, m_pSetupIndirectShader->m_pPipeline );
            RHI::CmdSetRootConstants( pCommandBuffer, 0, &setupIndirectResourceTable, sizeof( setupIndirectResourceTable ) );
            RHI::CmdDispatchCompute( pCommandBuffer, 1, 1, 1 );
        }

        RHI::CmdBarrier( pCommandBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ComputeShader, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::UnorderedAccess );

        RHI::CmdBarrier( pCommandBuffer, pConstantBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::AllShader, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::ConstantBuffer );
        RHI::CmdBarrier( pCommandBuffer, pCountArgumentsBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ExecuteIndirect, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::IndirectArgument );
        RHI::CmdBarrier( pCommandBuffer, pReduceArgumentsBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ExecuteIndirect, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::IndirectArgument );
        RHI::CmdBarrier( pCommandBuffer, pScanAddArgumentsBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ExecuteIndirect, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::IndirectArgument );
        RHI::CmdBarrier( pCommandBuffer, pScatterArgumentsBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ExecuteIndirect, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::IndirectArgument );
        RHI::CmdBarrier( pCommandBuffer, pScatterPayloadArgumentsBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ExecuteIndirect, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::IndirectArgument );

        // Sort only the bits the keys actually use - an even number of passes keeps the sorted result in the source ( A ) buffers so the final copy stays valid
        uint32_t const numSortPasses = Math::Min( ( ( numSortBits + 7 ) & ~7U ) / FFX_PARALLELSORT_SORT_BITS_PER_PASS, 8U );

        for ( uint32_t pass = 0; pass < numSortPasses; ++pass )
        {
            uint32_t const shift = pass * FFX_PARALLELSORT_SORT_BITS_PER_PASS;

            // Count
            {
                if ( shift > 0 )
                {
                    RHI::CmdBarrier( pCommandBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ComputeShader, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::UnorderedAccess );
                }

                RHI::CmdSetPipeline( pCommandBuffer, m_pCountShader->m_pPipeline );
                RHI::CmdSetRootConstants( pCommandBuffer, 0, nullptr, sizeof( ShaderTypes::FFX_ParallelSort_CountResourceTableData ) );
                RHI::CmdExecuteIndirect( pCommandBuffer, m_pCountShader->m_pCommandSignature, 1, pCountArgumentsBuffer, ( shift / 4 ) * countArgumentStride, nullptr, 0 );
            }

            // Reduce
            {
                RHI::CmdBarrier( pCommandBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ComputeShader, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::UnorderedAccess );

                RHI::CmdSetPipeline( pCommandBuffer, m_pReduceShader->m_pPipeline );
                RHI::CmdSetRootConstants( pCommandBuffer, 0, nullptr, sizeof( ShaderTypes::FFX_ParallelSort_ReduceResourceTableData ) );
                RHI::CmdExecuteIndirect( pCommandBuffer, m_pReduceShader->m_pCommandSignature, 1, pReduceArgumentsBuffer, 0, nullptr, 0 );
            }

            // Scan prefix on reduced scratch
            {
                RHI::CmdBarrier( pCommandBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ComputeShader, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::UnorderedAccess );

                ShaderTypes::FFX_ParallelSort_ScanResourceTableData scanResourceTable = {};
                scanResourceTable.SetScanSrc( pReduced );
                scanResourceTable.SetScanDst( pReduced );

                RHI::CmdSetPipeline( pCommandBuffer, m_pScanShader->m_pPipeline );
                RHI::CmdSetRootConstants( pCommandBuffer, 0, &scanResourceTable, sizeof( scanResourceTable ) );
                RHI::CmdSetRootParameter( pCommandBuffer, 1, pConstantBuffer, 0 );
                RHI::CmdDispatchCompute( pCommandBuffer, 1, 1, 1 );
            }

            // ScanAdd on main scratch with partials
            {
                RHI::CmdBarrier( pCommandBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ComputeShader, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::UnorderedAccess );

                RHI::CmdSetPipeline( pCommandBuffer, m_pScanAddShader->m_pPipeline );
                RHI::CmdSetRootConstants( pCommandBuffer, 0, nullptr, sizeof( ShaderTypes::FFX_ParallelSort_ScanAddResourceTableData ) );
                RHI::CmdExecuteIndirect( pCommandBuffer, m_pScanAddShader->m_pCommandSignature, 1, pScanAddArgumentsBuffer, 0, nullptr, 0 );
            }

            // Scatter
            {
                RHI::CmdBarrier( pCommandBuffer, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::ComputeShader, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::UnorderedAccess );

                if ( hasPayload )
                {
                    RHI::CmdSetPipeline( pCommandBuffer, m_pScatterPayloadShader->m_pPipeline );
                    RHI::CmdSetRootConstants( pCommandBuffer, 0, nullptr, sizeof( ShaderTypes::FFX_ParallelSort_ScatterPayloadResourceTableData ) );
                    RHI::CmdExecuteIndirect( pCommandBuffer, m_pScatterPayloadShader->m_pCommandSignature, 1, pScatterPayloadArgumentsBuffer, ( shift / 4 ) * scatterPayloadArgumentStride, nullptr, 0 );
                }
                else
                {
                    RHI::CmdSetPipeline( pCommandBuffer, m_pScatterShader->m_pPipeline );
                    RHI::CmdSetRootConstants( pCommandBuffer, 0, nullptr, sizeof( ShaderTypes::FFX_ParallelSort_ScatterResourceTableData ) );
                    RHI::CmdExecuteIndirect( pCommandBuffer, m_pScatterShader->m_pCommandSignature, 1, pScatterArgumentsBuffer, ( shift / 4 ) * scatterArgumentStride, nullptr, 0 );
                }
            }
        }

        // The pass count is always even, so the sorted data is in the original source buffers.
        // Copy into the destination buffers - per-buffer barriers for the copy only.
        RHI::CmdBarrier( pCommandBuffer, pSrcKeys, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::Copy, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::CopySource );
        RHI::CmdBarrier( pCommandBuffer, pDstKeys, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::Copy, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::CopyDestination );
        RHI::CmdCopyBuffer( pCommandBuffer, pDstKeys, 0, pSrcKeys, 0, maxNumKeys * sizeof( uint32_t ) );

        if ( hasPayload )
        {
            RHI::CmdBarrier( pCommandBuffer, pSrcPayload, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::Copy, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::CopySource );
            RHI::CmdBarrier( pCommandBuffer, pDstPayload, RHI::PipelineStage::ComputeShader, RHI::PipelineStage::Copy, RHI::ResourceAccess::UnorderedAccess, RHI::ResourceAccess::CopyDestination );
            RHI::CmdCopyBuffer( pCommandBuffer, pDstPayload, 0, pSrcPayload, 0, maxNumKeys * sizeof( uint32_t ) );
        }
    }
}
